<div class="form-group">
  <label class="control-label" for="oldpassword"><?=$this->transEsc('password_old_field_label') ?>:</label>
  <input type="password" name="oldpassword" id="oldpassword" class="form-control" autocomplete="current-password" required>
  <div class="help-block with-errors"></div>
</div>
<div class="form-group">
  <label class="control-label" for="password"><?=$this->transEsc('password_new_field_label') ?>:</label>
  <input type="password" name="password" id="password" class="form-control" autocomplete="new-password" required>
  <div class="help-block with-errors"></div>
</div>
<div class="form-group">
  <label class="control-label" for="password2"><?=$this->transEsc('password_repeat_field_label') ?>:</label>
  <input type="password" name="password2" id="password2" class="form-control" required aria-required="true" data-match="#password" data-match-error="<?=$this->transEscAttr('Passwords do not match')?>" autocomplete="new-password">
  <div class="help-block with-errors"></div>
</div>
