---
# Listing of configured forms.
#
# Configured forms are listed in the top level 'forms' array and can accessed via the URL:
# /Feedback/Form/<form-id>
#
# The main Feedback form (id: FeedbackSite) can be accessed with a shorter URL /Feedback
#
# Form supports the following options:
#
#   enabled (boolean) Is the form enabled? (default = true)
#   useCaptcha (boolean) Should the form use Captcha validation? Requires the "feedback"
#                        option to be turned on in the config.ini [Captcha] form setting.
#                        (default = true, if Captcha turned on for feedback overall).
#   reportReferrer (boolean) Should the form report the page from which it was invoked
#   reportUserAgent (boolean) Should the form report the browser's user agent string
#   title (string) Form title (translation key)
#   onlyForLoggedUsers (boolean) Require the user to be logged in to see the form
#                                (default = false)
#   emailSubject (string) Email subject (translation key). (default = email_subject
#                         value from config.ini [Feedback] section, or 'VuFind Feedback')
#                         The subject may contain placeholders (for example %%receiver%%)
#                         that are replaced with submitted form values.
#   emailFrom (address in email envelope, separate from user's email)
#     name (string)  Sender name (default = sender_name setting from config.ini
#                    [Feedback] section)
#     email (string) Sender email (default = sender_email setting from
#                    config.ini [Feedback] section)
#   recipient
#     name (string)  Recipient name (default = recipient_name setting from config.ini
#                    [Feedback] section)
#     email (string) Recipient email address (default = recipient_email setting from
#                    config.ini [Feedback] section)
#
#   Multiple recipients can be configured using a list:
#
#   recipient:
#     - name: Recipient 1
#       email: recipient1@email
#     - name: Recipient 2
#       email: recipient2@email
#
#   response (string) Reponse after form submit (translation key)
#   senderInfoRequired (boolean)  Require sender to fill out name and email fields - deprecated
#   senderEmailRequired (boolean) Require sender to fill out email field
#   senderNameRequired (boolean)  Require sender to fill out name field
#
#   help
#     pre (string)  Help text displayed at the beginning of the form (translation key).
#     post (string) Help text displayed at the end of the form (translation key)
#
#     Help texts may contain HTML-formatting.
#
#   fields (array) List of form elements with the following options:
#
#     name (string)        Element name
#     label (string)       Element label (translation key)
#     required (boolean)   Is the element required? (for checkbox elements this means that
#                          all options have to be selected.)
#     requireOne (boolean) Require at least one checkbox option to be selected.
#     settings (array)     HTML attributes as key-value pairs, for example:
#       - [class, "custom-css-class another-class"]
#     type (string)        Element type (text|textarea|date|email|url|select|radio|checkbox|hidden)
#
#     help (string)        Element help text (translation key) that is displayed before the element.
#                          To include HTML formatting, use a translation key ending
#                          in '_html' here, and define markup in the language files.
#
#       or
#
#     help (array)
#      pre (string)      Like above.
#      post (string)     Like above but the help text is displayed after the element.
#
#
#     Additional settings for date element:
#
#     format             Date format to use in the resulting message  (default is
#                        displayDateFormat in config.ini). Format of the actual field
#                        displayed on the form is controlled by user's browser.
#     minValue           Minimum acceptable date. A string that PHP's strtotime can
#                        parse (e.g. 'now' or '2021-09-09').
#     maxValue           Maximum acceptable date. A string that PHP's strtotime can
#                        parse (e.g. 'now' or '2021-09-09').
#
#     Additional settings for select, radio and checkbox elements:
#
#     options (array) List of select values (translation keys)
#                     or a list of options with 'value' and 'label' (translation) keys.
#                       Examples:
#                         options:
#                           - option-1
#                           - option-2
#
#                         or
#
#                         options:
#                           - value: value-1
#                             label: label-1
#                           - value: value-2
#                             label: label-2
#
#     Alternative settings for select elements:
#
#     optionGroups (array) List of option groups with keys:
#       label (string) Group label (translation key)
#       options (array) List of select values (see above)
#
#     placeholder (string) Placeholder label (translation key). Used to instruct or force
#       (when combined with 'required' attribute) the user to make a selection from the
#       options-list. Only select elements with 'options' are supported.
#       For text, textarea, email and url elements, a placeholder text (translation key)
#       can be configured by adding a HTML-attribute via 'settings', for example:
#       settings:
#         - [placeholder, Please select...]
#
#-----------------------------------------------------------------------------------

forms:

  # Main Feedback form

  FeedbackSite:
    title: Feedback
    enabled: true
    useCaptcha: true
    reportReferrer: true
    reportUserAgent: true
    recipient:
      name: CPK
      email: cpk-support@mzk.cz

    onlyForLoggedUsers: false
    emailSubject: '%%subject%% - Knihovny.cz feedback'
    response: feedback_response
    senderNameRequired: false
    senderEmailRequired: true

    help:
      pre: feedback_help_pre
      post: feedback_help_post

    fields:
      - name: subject
        type: text
        label: Subject
        required: true
      - name: message
        type: textarea
        label: Comments
        required: true
        settings:
        # help: message_help


  PtejteSeKnihovny:
    title: Ask your library
    enabled: true
    useCaptcha: true
    reportReferrer: false
    reportUserAgent: false
    onlyForLoggedUsers: false
    response: Thank you for your question.
    senderNameRequired: false
    senderEmailRequired: true
    primaryHandler: asklibrary
    secondaryHandlers:
      - database

    help:
      pre: asklibrary_help_pre_html
      post: asklibrary_help_post_html

    fields:
      - name: library
        type: hidden
        settings:
          - [value, 'ABA001']
      - name: subject
        type: text
        label: Question
        required: true
      - name: message
        type: textarea
        label: Question details
        required: true
        settings:
      - name: category
        type: select
        label: Category
        required: true
        options:
          - value: "informace-o-knihovne"
            label: "Information about library"
          - value: "informace-o-vydanych-dokumentech"
            label: "Information about publications"
          - value: "antropologie-etnografie"
            label: "Anthropology, ethnography"
          - value: "biologicke-vedy"
            label: "Biology"
          - value: "divadlo-film-tanec"
            label: "Drama, film, dancing"
          - value: "ekonomicke-vedy-obchod"
            label: "Economy, business"
          - value: "filozofie-a-nabozenstvi"
            label: "Philosophy, religion"
          - value: "fyzika-a-pribuzne-vedy"
            label: "Physics"
          - value: "geografie-geologie-vedy-o-zemi"
            label: "Geography, geology"
          - value: "historie-a-pomocne-historicke-vedy-biograficke-studie"
            label: "History and auxiliary historical sciences"
          - value: "hudba"
            label: "Music"
          - value: "chemie-krystalografie-mineralogicke-vedy"
            label: "Chemistry, crystallography, mineralogy"
          - value: "jazyk-lingvistika-a-literatura"
            label: "Linguistic and literature"
          - value: "knihovnictvi-informatika-vseobecne-referencni-literatura"
            label: "Library science, informatics, reference literature"
          - value: "lekarstvi"
            label: "Medicine"
          - value: "matematika"
            label: "Mathematics"
          - value: "politicke-vedy-vojenstvi"
            label: "Political science, the military"
          - value: "pravo"
            label: "Law"
          - value: "psychologie"
            label: "Psychology"
          - value: "sociologie"
            label: "Sociology"
          - value: "technika-technologie-inzenyrstvi"
            label: "Technology, engineering"
          - value: "telesna-vychova-a-sport-rekreace"
            label: "Physical education and sport, recreation"
          - value: "umeni-architektura-muzeologie"
            label: "Art, architecture, museology"
          - value: "vychova-a-vzdelavani"
            label: "Education"
          - value: "vypocetni-technika"
            label: "Computing"
          - value: "zemedelstvi"
            label: "Agriculture"
