<h1>Geografické vyhledávání</h1>
<dl class="Content">
  <dt></dt>
  <dd>
    <ul>
      <li>Klikněte na tlačítko 'Označit vyhledávané území'.</li>
      <li>Kliknutím, tažením a puštěním tlačítka myši označíte na mapě obdélník vymezující prohledávané území.</li>
      <li>Pod mapou lze specifikovat měřítko vyhledaných dokumentů zadáním čísel nebo tažením posuvníku.</li>
      <li>Ve výsledcích vyhledávání budou zobrazeny kartografické dokumenty vztahující se k zadanému území a měřítku.</li>
      <li>Berte prosím na vědomí, že geografické vyhledávání vyhledá pouze ty kartografické dokumenty, jejichž bibliografický záznam obsahuje GPS souřadnice a měřítko.</li>
    </ul>
  </dd>
</dl>
