<?php
// Set page title.
$this->headTitle($this->translate('Ziskej::service_name'));

// Disable search box
$this->layout()->searchbox = false;
?>

<?=$this->flashmessages() ?>

<!-- ziskej select mode -->
<div class="card">
  <h3 class="card-header"><?=$this->translate('Ziskej::settings_title_mode') ?></h3>
  <div class="card-body">
    <form action="<?=$this->url('ziskej-admin') ?>" id="ziskejForm" method="post" name="ziskejForm">
      <div class="form-group">
        <label for="selectZiskejMode"><?=$this->translate('Ziskej::label_ziskej_mode') ?>: </label>
        <select name="ziskejMode" class="form-select" id="selectZiskejMode">
          <?php foreach ($this->ziskejMvs()->getModes() as $mode): ?>
            <option value="<?=$this->escapeHtmlAttr($mode) ?>" <?php if ($mode == $this->ziskejMvs()->getCurrentMode()): ?>selected="selected"<?php endif; ?>>
              <?=$this->translate(sprintf('Ziskej::mode_%s', $mode)) ?>
            </option>
          <?php endforeach; ?>
        </select>
      </div>
      <div class="form-group">
        <input class="btn btn-primary" type="submit" name="submitZiskej" title="<?=$this->translate('Ziskej::btn_save') ?>" value="<?=$this->translate('Ziskej::btn_save') ?>">
      </div>
    </form>
  </div>
</div>
<!-- /ziskej select mode -->

<?php if ($this->ziskejMvs()->isEnabled()): ?>

  <!-- user data -->
  <div class="card">
    <h3 class="card-header"><?=$this->translate('Ziskej::settings_title_user') ?></h3>
    <div class="card-body">
      <?php if (!empty($this->user)): ?>
        <div class="row">
          <div class="col-md-6">
            <dl class="dl-horizontal">
              <dt><?=$this->translate('Ziskej::settings_label_username') ?>:</dt>
              <dd><?=$this->user->username ?></dd>
            </dl>
          </div>
          <div class="col-md-6">
            <dl class="dl-horizontal">
              <dt><?=$this->translate('Ziskej::settings_label_name_first') ?>:</dt>
              <dd><?=$this->user->firstname ?></dd>
              <dt><?=$this->translate('Ziskej::settings_label_name_last') ?>:</dt>
              <dd><?=$this->user->lastname ?></dd>
              <dt><?=$this->translate('Ziskej::settings_label_email') ?>:</dt>
              <dd><?=$this->user->email ?></dd>
            </dl>
          </div>
        </div>
      <?php else: ?>
        <div class="alert alert-warning text-center">
          <?=$this->translate('Ziskej::message_no_user_logged_in') ?>
        </div>
      <?php endif; ?>
    </div>
  </div>
  <!-- /user data -->

  <!-- ziskej data -->
  <?php if (!empty($this->data)): ?>
    <div class="card card-with-tabs">
      <div class="card-header bg-transparent">
        <ul class="nav nav-tabs card-header-tabs" role="tablist">
        <?php $i = 1; ?>
        <?php foreach ($this->data as $eppn => $row): ?>
          <li role="presentation" class="nav-item">
            <a class="nav-link <?php if ($i === 1): ?>active<?php endif; ?>" href="#tab_<?=$i ?>" role="tab" data-bs-toggle="tab"><?=$eppn ?></a>
          </li>
          <?php $i++; ?>
        <?php endforeach; ?>
      </ul>
      </div>
      <div class="card-body tab-content">
        <?php $i = 1; ?>
        <?php foreach ($this->data as $eppn => $row): ?>
          <div class="tab-pane <?php if ($i === 1): ?>active<?php endif; ?>" id="tab_<?=$i ?>">
            <?php if ($row['isLibraryInZiskej']): ?>
              <?php
              /** @var Mzk\ZiskejApi\ResponseModel\Reader $reader */
              $reader = !empty($row['reader']) ? $row['reader'] : null;
              ?>
              <?php if ($reader): ?>
                <?php if (!$reader->isActive): ?>
                  <div class="alert alert-warning text-center">
                    <?=$this->translate('Ziskej::settings_alert_reader_not_active') ?>
                  </div>
                <?php endif; ?>
                <div class="panel panel-default">
                  <div class="panel-heading">
                    <h3 class="panel-title"><?=$this->translate('Ziskej::settings_label_reader') ?></h3>
                  </div>
                  <div class="panel-body">
                    <div class="row">
                      <div class="col-md-6">
                        <dl class="dl-horizontal">
                          <dt><?=$this->translate('Ziskej::settings_label_is_active') ?></dt>
                          <dd><?=$reader->isActive ? $this->translate('Ziskej::yes') : $this->translate('Ziskej::no') ?></dd>
                          <dt><?=$this->translate('Ziskej::settings_label_eppn') ?>:</dt>
                          <dd><?=$eppn ?></dd>
                          <dt><?=$this->translate('Ziskej::settings_label_sigla') ?></dt>
                          <dd><?=$reader->sigla ?></dd>
                        </dl>
                      </div>
                      <div class="col-md-6">
                        <dl class="dl-horizontal">
                          <dt><?=$this->translate('Ziskej::settings_label_name_first') ?>:</dt>
                          <dd><?=$reader->firstName ?></dd>
                          <dt><?=$this->translate('Ziskej::settings_label_name_last') ?>:</dt>
                          <dd><?=$reader->lastName ?></dd>
                          <dt><?=$this->translate('Ziskej::settings_label_email') ?>:</dt>
                          <dd><?=$reader->email ?></dd>
                        </dl>
                      </div>
                    </div>
                  </div>
                </div>
                <?php if ($reader->isActive): ?>
                  <?php
                  /** @var array $tickets */
                  $tickets = $row['tickets'];
                  ?>
                  <div class="panel panel-default">
                    <div class="panel-heading">
                      <h3 class="panel-title"><?=$this->translate('Ziskej::settings_label_tickets') ?> <span class="badge"><?=is_countable($tickets) ? count($tickets) : 0 ?></span></h3>
                    </div>
                    <div class="panel-body">
                      <?php if (is_countable($tickets) && count($tickets)): ?>
                        <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
                          <?php
                          /** @var \Mzk\ZiskejApi\ResponseModel\TicketMvs|\Mzk\ZiskejApi\ResponseModel\TicketEdd $ticket */
                          foreach ($tickets as $ticketDuo):
                            $ticket = $ticketDuo['ticket'];
                            ?>
                            <div class="panel panel-default">
                              <div class="panel-heading" role="tab">
                                <h4 class="panel-title">
                                  <a role="button" data-bs-toggle="collapse" href="#ticket_<?=$ticket->hid ?>">
                                    <?=$this->dateTime()->convertToDisplayDateAndTime('U', $ticket->createdAt->getTimestamp()) ?>
                                    | <?=$ticket->id ?>
                                    <span class="float-right">
                                      <?php if (is_countable($ticketDuo['messages']) && count($ticketDuo['messages'])): ?>
                                        <span class="badge"><?=$this->translate('Ziskej::settings_label_count_messages') ?>: <?=count($ticketDuo['messages']) ?></span>
                                      <?php endif; ?>
                                    </span>
                                  </a>
                                </h4>
                              </div>
                              <div id="ticket_<?=$ticket->hid ?>" class="panel-collapse collapse out" role="tabpanel">
                                <div class="panel-body">
                                  <div class="row">
                                    <div class="col-md-6">
                                      <dl class="dl-horizontal">
                                        <dt><?=$this->translate('Ziskej::settings_label_id') ?>:</dt>
                                        <dd><?=$ticket->id ?></dd>
                                        <dt><?=$this->translate('Ziskej::settings_label_hid') ?>:</dt>
                                        <dd><?=$ticket->hid ?></dd>
                                        <dt><?=$this->translate('Ziskej::settings_label_is_open') ?>:</dt>
                                        <dd><?=$ticket->isOpen ?></dd>
                                        <dt><?=$this->translate('Ziskej::settings_label_doc_id') ?>:</dt>
                                        <dd><?=$ticket->documentId ?></dd>
                                        <dt><?=$this->translate('Ziskej::settings_label_sigla') ?>:</dt>
                                        <dd><?=$ticket->sigla ?></dd>
                                        <dt><?=$this->translate('Ziskej::settings_label_status_reader') ?>:</dt>
                                        <dd><?=$ticket->status->value ?></dd>
                                      </dl>
                                    </div>
                                    <div class="col-md-6">
                                      <dl>
                                        <dt><?=$this->translate('Ziskej::settings_label_date_created') ?>:</dt>
                                        <dd><?=$this->dateTime()->convertToDisplayDateAndTime('U', $ticket->createdAt->getTimestamp()) ?></dd>
                                        <dt><?=$this->translate('Ziskej::settings_label_date_requested') ?>:</dt>
                                        <dd>
                                          <?=!empty($ticket->requestedAt)
                                            ? $this->dateTime()->convertToDisplayDate('U', $ticket->requestedAt->getTimestamp())
                                            : '–'
                                          ?>
                                        </dd>
                                        <dt><?=$this->translate('Ziskej::settings_label_date_return') ?>:</dt>
                                        <dd>
                                          <?=!empty($ticket->returnAt)
                                            ? $this->dateTime()->convertToDisplayDate('U', $ticket->returnAt->getTimestamp())
                                            : '–'
                                          ?>
                                        </dd>
                                      </dl>
                                    </div>
                                  </div>
                                  <hr>
                                </div>
                              </div>
                            </div>
                          <?php endforeach; ?>
                        </div>
                      <?php else: ?>
                        <div class="alert alert-info text-center">
                          <?=$this->translate('Ziskej::settings_label_no_tickets') ?>
                        </div>
                      <?php endif; ?>
                    </div>
                  </div>
                <?php endif; ?>
              <?php else: ?>
                <div class="alert alert-warning text-center">
                  <?=$this->translate('Ziskej::settings_label_no_reader') ?>
                </div>
              <?php endif; ?>
            <?php else: ?>
              <div class="alert alert-warning text-center">
                <?=$this->translate('Ziskej::settings_label_no_library') ?>
              </div>
            <?php endif ?>
          </div>
          <?php $i++; ?>
        <?php endforeach; ?>
      </div>
    </div>
  <?php endif; ?>
  <!-- /ziskej data -->

<?php endif; ?>
