<?php
$openUrl = $this->driver->getOpenUrl();
$fullTextLinks = $this->driver->getFullTextLinks($this->recordLinker());
$dataFulltext = (!empty($fullTextLinks)) ? 'true' : 'false';
$dataLazy = ($this->lazy) ? 'true' : 'false';
$dataDropdown = ($this->dropdown) ? 'true' : 'false';
?>
<div class="context-help">
  <h5 class="context-text mt-0"><?=$this->transEsc('sfx_availability')?>:</h5>
  <?=$this->contextHelp('ci-links', 'heading')?>
</div>
<?php if(!empty($fullTextLinks)): ?>
  <div class="records-in-libraries-title">
    <strong class="header"><?=$this->transEsc('Fulltext is free')?></strong>
    <?php foreach($fullTextLinks as $label => $url): ?>
      <ul class="list-unstyled">
        <li>
          <a href="<?=$this->escapeHtml($url)?>" title="<?=$this->translate($label)?>" target="_blank"><?=$this->transEsc($label)?></a>
        </li>
      </ul>
    <?php endforeach; ?>
  </div>
<?php endif; ?>
<div class='dedupInformation'>
  <span class="openurl" data-fulltext="<?=$dataFulltext?>" data-lazy="<?=$dataLazy?>" data-dropdown="<?=$dataDropdown?>" data-openurl="<?=$this->escapeHtml($openUrl)?>">
    <?php if($this->lazy): ?>
      <button type="button" class="btn btn-primary">
        <strong><?=$this->transEsc("Check fulltext availability")?></strong>
      </button>
    <?php else: ?>
      <?=$this->icon('spinner')?>
    <?php endif; ?>
  </span>
</div>
