<?php
$openUrl = $this->driver->getOpenUrl();
$fullTextLinks = $this->driver->getFullTextLinks($this->recordLinker());
?>
<div class="context-help">
  <h5 class="context-text mt-0"><?=$this->transEsc('sfx_availability')?>:</h5>
  <?=$this->contextHelp('ci-links', 'heading')?>
</div>
<?php if(!empty($fullTextLinks)): ?>
  <div class="records-in-libraries-title">
    <strong><?=$this->transEsc('Fulltext is free')?></strong>
    <?php foreach($fullTextLinks as $label => $url): ?>
      <ul class="list-unstyled">
        <li>
          <a href="<?=$this->escapeHtml($url)?>" title="<?=$this->translate($label)?>" target="_blank"><?=$this->transEsc($label)?></a>
        </li>
      </ul>
    <?php endforeach; ?>
  </div>
<?php else: ?>
  <div class='dedupInformation'>
    <span class="openurl" data-lazy="<?=($this->lazy)?'true':'false'?>" data-dropdown="<?=($this->dropdown)?'true':'false'?>" data-openurl="<?=$this->escapeHtml($openUrl)?>">
      <?php if($this->lazy): ?>
        <button type="button" class="btn btn-primary">
          <strong><?=$this->transEsc("Check fulltext availability")?></strong>
        </button>
      <?php else: ?>
        <?=$this->icon('spinner')?>
      <?php endif; ?>
    </span>
  </div>
<?php endif; ?>
