stages:
  - build

variables:
  REGISTRY_URL: registry.app.knihovny.cz
  TARGET_IMAGE_NAME: moravianlibrary/vufind
  BUILD_DEBUG: 'true'
  #DOCKER_BUILDKIT: 1

Build multistage image:
  stage: build
  rules:
    - if: ( $CI_MERGE_REQUEST_IID == "233")
  image: docker:20.10-git
  services:
    - docker:20.10-dind
  before_script:
    - apk update
    - apk add make bash
    - mkdir -p $HOME/.docker
    - cp ${REGISTRY_AUTH_FILE} $HOME/.docker/config.json
  script:
    - cd ${CI_PROJECT_DIR}
    - make -C build IMAGE_NAME=${REGISTRY_URL}/knihovny-cz/vufind:build
    - docker push ${REGISTRY_URL}/knihovny-cz/vufind:build

Build container image:
  stage: build
  rules:
    - if:
          ( $CI_PIPELINE_SOURCE == "push" ) &&
          ( $CI_COMMIT_BRANCH =~ /^ci/ )
  image: docker:19.03.12
  services:
    - docker:19.03.12-dind
  before_script:
    - apk update
    - apk add bash docker-compose
    - mkdir -p $HOME/.docker
    - cp ${REGISTRY_AUTH_FILE} $HOME/.docker/config.json
  script:
    - cd ${CI_PROJECT_DIR}
    - cp docker/deploy.env.example docker/deploy.env
    - cp docker/local.env.example docker/local.env
#    - bin/run.sh --no-run --image localhost/vufind:build --private-registry
    # build the image
    - bin/run.sh --no-run -t deploy --service vufind6 --branch ${CI_COMMIT_REF}
    # upload image to the registry
    - docker tag moravianlibrary/knihovny_cz:latest ${REGISTRY_URL}/${TARGET_IMAGE_NAME}:build
    - docker push ${REGISTRY_URL}/${TARGET_IMAGE_NAME}:build
    - docker tag moravianlibrary/knihovny_cz:latest ${REGISTRY_URL}/${TARGET_IMAGE_NAME}:${CI_COMMIT_REF_SLUG}-${CI_PIPELINE_IID}-${CI_COMMIT_SHORT_SHA}
    - docker push ${REGISTRY_URL}/${TARGET_IMAGE_NAME}:${CI_COMMIT_REF_SLUG}-${CI_PIPELINE_IID}-${CI_COMMIT_SHORT_SHA}
