stages:
  - build

variables:
  REGISTRY_URL: registry.app.knihovny.cz
  TARGET_IMAGE_NAME: moravianlibrary/vufind

Build container image:
  stage: build
  only:
    refs:
      - cicd-test
      - master
      - /^issue-.*/
  image: docker:19.03.12
  services:
    - docker:19.03.12-dind
  before_script:
    - apk update
    - apk add bash docker-compose
    - mkdir -p $HOME/.docker
    - cp ${REGISTRY_AUTH_FILE} $HOME/.docker/config.json
  script:
    - cd ${CI_PROJECT_DIR}
    - cp docker/deploy.env.example docker/deploy.env
    - cp docker/local.env.example docker/local.env
    - bin/run.sh --no-run --image ${TARGET_IMAGE_NAME}:${CI_COMMIT_BRANCH}-${CI_PIPELINE_IID}-${CI_COMMIT_SHORT_SHA} --private-registry
