<?php
  $form = $this->form;
  $form->prepare();
  $title = $form->getTitle();
  $title = !empty($title) ? $this->translate($title) : null;
?>
<?php if (!$this->inLightbox): ?><div class="feedback-content"><?php endif; ?>

<?php if ($title): ?>
  <?=$this->component('page-title', ['title' => $title, 'level' => 1]);?>
<?php endif; ?>
<?=$this->flashmessages()?>
<div role="status" class="alert alert-success">
  <?=$this->translate($this->successMessage) ?>
</div>
<?php if (!$this->inLightbox): ?></div><?php endif; ?>
