#!/usr/bin/env bash

# Set default values to use in bootstrap scripts
if [ -z "$PARAM_VUFIND_SRC" ]; then
    export PARAM_VUFIND_SRC="/var/www/knihovny-cz"
fi;

if [ -z "$PARAM_VUFIND_CONFIG_DIR" ]; then
    export PARAM_VUFIND_CONFIG_DIR="knihovny.cz"
fi;

if [[ -n "$PARAM_VUFIND_ROBOTS_TXT" && -e "${PARAM_VUFIND_SRC}/public/$PARAM_VUFIND_ROBOTS_TXT" ]]; then
    cp "${PARAM_VUFIND_SRC}/public/$PARAM_VUFIND_ROBOTS_TXT" "${PARAM_VUFIND_SRC}/public/robots.txt"
fi;

# Export common configuration
PARAM_VUFIND_CONFIG_ABS_DIR="${PARAM_VUFIND_SRC}/local/${PARAM_VUFIND_CONFIG_DIR}"

# Backward compability with previous configuration layout
if [[ "$PARAM_VUFIND_CONFIG_DIR" == "knihovny.cz" && ! -d "$PARAM_VUFIND_CONFIG_ABS_DIR" ]] ; then
    PARAM_VUFIND_CONFIG_ABS_DIR="${PARAM_VUFIND_SRC}/local/"
fi;
export PARAM_VUFIND_CONFIG_ABS_DIR

# List all environment variables
# WARNING: possible threat of exploiting the secrets here (by saving `env` output to the docker logs)
env

# Run all start files
if test -d /onstart; then
    for FILE in /onstart/*; do
        if test -x "$FILE"; then
            "$FILE" || test "${IGNORE_BOOTSTRAP_FAILURE:-false}" == "true" || exit $?
        else
            echo "Warning: found non-executable file at '$FILE'" >&2
        fi
    done
fi

# This has to be done so that the server can create caches & logs
chgrp -R www-data "${PARAM_VUFIND_SRC:-/var/www/src}"
chmod -R g+w "${PARAM_VUFIND_SRC:-/var/www/src}"

echo
echo " --- Bootstrapping done! "
echo

apache2-foreground || \
    test "${IGNORE_BOOTSTRAP_FAILURE:-false}" == "true" && \
    echo "ERROR: apache start failed !" >&2 && \
    while true; do sleep 1; done
