<?php
    // Check if "Renew All" button can be displayed:
    $renewAll = !$this->ilsPaging || !$paginator;
    $itemIndex = 1;
?>
<?=$this->flashmessages()?>
<?php if (!empty($this->transactions)): ?>
  <nav class="search-header hidden-print">
    <?php if ($paginator): ?>
      <div class="search-stats">
      <?php
        $abs = $paginator->getAbsoluteItemNumber($paginator->getItemCountPerPage());
        $end = min($abs, $paginator->getTotalItemCount());
        $itemIndex = $this->paginator->getAbsoluteItemNumber(1);
        $transParams = [
          '%%start%%' => $this->localizedNumber($paginator->getAbsoluteItemNumber(1)),
          '%%end%%' => $this->localizedNumber($end),
          '%%total%%' => $this->localizedNumber($paginator->getTotalItemCount()),
        ];
      ?>
      <?=$this->translate('showing_items_of_html', $transParams); ?>
      </div>
    <?php endif; ?>
    <?php if ($this->sortList): ?>
      <?=$this->context($this)->renderInContext('myresearch/controls/sort.phtml', ['sortList' => $this->sortList]); ?>
    <?php endif; ?>
  </nav>
  <?php if ($this->renewForm): ?>
    <form name="renewals" method="post" id="renewals" data-clear-account-cache="checkedOut" data-disable-on-submit>
      <input type="hidden" value="<?=$this->escapeHtmlAttr($this->auth()->getManager()->getCsrfHash())?>" name="csrf">
      <input type="hidden" id="submitType" name="renewSelected" value="1">
      <input type="hidden" value="<?=$this->escapeHtmlAttr($this->params['page'] ?? '1')?>" name="page">
      <div class="toolbar">
        <div class="checkbox">
          <label>
            <input type="checkbox" name="selectAll" class="checkbox-select-all">
              <?=$this->transEsc('select_all_on_page')?>
          </label>
          <?=
            $this->component(
                'confirm-button',
                [
                    'buttonId' => 'renewSelected',
                    'buttonName' => 'renewSelected',
                    'buttonLabel' => 'renew_selected',
                    'header' => 'confirm_renew_selected_text',
                    'confirmId' => 'confirm_renew_selected_yes',
                    'cancelClass' => 'confirm_renew_no',
                    'ignoreLightbox' => true,
                ]
            )
          ?>
          <?php if ($renewAll): ?>
            <?=
              $this->component(
                  'confirm-button',
                  [
                      'buttonId' => 'renewAll',
                      'buttonName' => 'renewAll',
                      'buttonLabel' => 'renew_all',
                      'header' => 'confirm_renew_all_text',
                      'confirmId' => 'confirm_renew_all_yes',
                      'cancelClass' => 'confirm_renew_no',
                      'ignoreLightbox' => true,
                  ]
              )
            ?>
          <?php endif; ?>
        </div>
      </div>
  <?php endif; ?>


  <?php foreach ($hiddenTransactions as $ilsDetails): ?>
    <?php if (isset($this->renewResult[$ilsDetails['item_id']])): ?>
      <?php $renewDetails = $this->renewResult[$ilsDetails['item_id']]; ?>
      <?php $prefix = $ilsDetails['title'] ?? $ilsDetails['item_id']; ?>
      <?php if (isset($renewDetails['success']) && $renewDetails['success']): ?>
        <div class="alert alert-success"><?=$this->escapeHtml($prefix . ': ') . $this->transEsc('renew_success')?></div>
      <?php else: ?>
        <div class="alert alert-danger"><?=$this->escapeHtml($prefix . ': ') . $this->transEsc('renew_fail')?><?php if (isset($renewDetails['sysMessage'])): ?>: <?=$this->escapeHtml($renewDetails['sysMessage'])?><?php endif; ?></div>
      <?php endif; ?>
    <?php endif; ?>
    <?php if (isset($ilsDetails['renewable']) && $ilsDetails['renewable'] && isset($ilsDetails['renew_details'])): ?>
      <?php $safeId = preg_replace('/[^a-zA-Z0-9]/', '', $ilsDetails['renew_details']); ?>
      <input class="pull-left flip" type="hidden" name="renewAllIDS[]" value="<?=$this->escapeHtmlAttr($ilsDetails['renew_details'])?>" >
    <?php endif; ?>
  <?php endforeach; ?>

  <ul class="record-list">
    <?php $i = 0;
    foreach ($this->transactions as $resource): ?>
      <?php $ilsDetails = $resource->getExtraDetail('ils_details'); ?>
        <li id="record<?=$this->escapeHtmlAttr($resource->getUniqueId())?>" class="result">
        <div>
          <strong class="pull-left order"><?= $itemIndex++ ?>.</strong>
          <?php if ($this->renewForm): ?>
            <div class="checkbox">
              <?php if (isset($ilsDetails['renewable']) && $ilsDetails['renewable'] && isset($ilsDetails['renew_details'])): ?>
                <?php $safeId = preg_replace('/[^a-zA-Z0-9]/', '', $ilsDetails['renew_details']); ?>
                  <label>
                    <input class="checkbox-select-item" type="checkbox" name="renewSelectedIDS[]" value="<?=$this->escapeHtmlAttr($ilsDetails['renew_details'])?>" id="checkbox_<?=$safeId?>" >
                  </label>
                  <input type="hidden" name="selectAllIDS[]" value="<?=$this->escapeHtmlAttr($ilsDetails['renew_details'])?>" >
                  <input type="hidden" name="renewAllIDS[]" value="<?=$this->escapeHtmlAttr($ilsDetails['renew_details'])?>" >
              <?php else: ?>
                <label> </label>
              <?php endif; ?>
            </div>
          <?php endif; ?>
        </div>

        <?php
          $coverDetails = $this->record($resource)->getCoverDetails('checkedout', 'small', $this->recordLinker()->getUrl($resource));
          $cover = $coverDetails['html'];
          $thumbnail = false;
          $thumbnailAlignment = $this->record($resource)->getThumbnailAlignment('account');
          if ($cover):
            ob_start(); ?>
            <div class="media-<?=$thumbnailAlignment ?> <?=$this->escapeHtmlAttr($coverDetails['size'])?>">
                <?=$cover ?>
            </div>
            <?php $thumbnail = ob_get_contents(); ?>
            <?php ob_end_clean(); ?>
          <?php endif; ?>
          <div class="media">
            <?php if ($thumbnail && $thumbnailAlignment == 'left'): ?>
              <?=$thumbnail ?>
            <?php endif ?>
              <div class="media-body">
                <?=$this->record($resource)->renderTemplate('account-entry.phtml')?>
                <?php if ($this->displayItemBarcode && !empty($ilsDetails['barcode'])): ?>
                <strong><?=$this->transEsc('Barcode')?>:</strong> <?=$this->escapeHtml($ilsDetails['barcode'])?>
                <br>
              <?php endif; ?>

              <?php if (!empty($ilsDetails['institution_name']) && (empty($ilsDetails['borrowingLocation']) || $ilsDetails['institution_name'] != $ilsDetails['borrowingLocation'])): ?>
                <strong><?=$this->transEscWithPrefix('location_', $ilsDetails['institution_name'])?></strong>
                <br>
              <?php endif; ?>

              <?php if (!empty($ilsDetails['borrowingLocation'])): ?>
                <strong><?=$this->transEsc('Borrowing Location')?>:</strong> <?=$this->transEscWithPrefix('location_', $ilsDetails['borrowingLocation'])?>
                <br>
              <?php endif; ?>

              <?php if (isset($ilsDetails['renew'])): ?>
                <strong><?=$this->transEsc('Renewed')?>:</strong> <?=$this->transEsc($ilsDetails['renew'])?>
                <?php if (isset($ilsDetails['renewLimit'])): ?>
                  / <?=$this->transEsc($ilsDetails['renewLimit'])?>
                <?php endif; ?>
                <br>
              <?php endif; ?>

              <?php if (!empty($ilsDetails['checkoutDate'])): ?>
                <strong><?=$this->transEsc('Checkout Date')?>:</strong> <?=$this->escapeHtml($ilsDetails['checkoutDate'])?><?php if (isset($ilsDetails['checkoutTime'])): ?> <span class="checkout-time"><?=$this->escapeHtml($ilsDetails['checkoutTime'])?><?php endif; ?></span>
                <br>
              <?php endif; ?>

              <?php $showStatus = true; ?>

              <?php if (isset($this->renewResult[$ilsDetails['item_id']])): ?>
                <?php $renewDetails = $this->renewResult[$ilsDetails['item_id']]; ?>
                <?php if (isset($renewDetails['success']) && $renewDetails['success']): ?>
                  <?php $showStatus = false; ?>
                  <strong><?=$this->transEsc('Due Date')?>:</strong> <?=$this->escapeHtml($renewDetails['new_date'])?> <?php if (isset($renewDetails['new_time'])): ?><?=$this->escapeHtml($renewDetails['new_time'])?><?php endif; ?>
                  <div class="alert alert-success"><?=$this->transEsc('renew_success')?></div>
                <?php else: ?>
                  <strong><?=$this->transEsc('Due Date')?>:</strong> <?=$this->escapeHtml($ilsDetails['duedate'])?><?php if (isset($ilsDetails['dueTime'])): ?> <?=$this->escapeHtml($ilsDetails['dueTime'])?><?php endif; ?>
                  <div class="alert alert-danger"><?=$this->transEsc('renew_fail')?><?php if (isset($renewDetails['sysMessage'])): ?>: <?=$this->escapeHtml($renewDetails['sysMessage'])?><?php endif; ?></div>
                <?php endif; ?>
                <?php else: ?>
                  <strong><?=$this->transEsc('Due Date')?>:</strong> <?=$this->escapeHtml($ilsDetails['duedate'])?><?php if (isset($ilsDetails['dueTime'])): ?> <?=$this->escapeHtml($ilsDetails['dueTime'])?><?php endif; ?>
                <?php if ($showStatus): ?>
                  <?php if (isset($ilsDetails['dueStatus']) && $ilsDetails['dueStatus'] == 'overdue'): ?>
                    <div class="alert alert-danger"><?=$this->transEsc('renew_item_overdue')?></div>
                  <?php elseif (isset($ilsDetails['dueStatus']) && $ilsDetails['dueStatus'] == 'due'): ?>
                    <div class="alert alert-info"><?=$this->transEsc('renew_item_due')?></div>
                  <?php endif; ?>
                <?php endif; ?>
              <?php endif; ?>

              <?php if ($showStatus && isset($ilsDetails['message']) && !empty($ilsDetails['message'])): ?>
                <div class="alert alert-info"><?=$this->transEsc($ilsDetails['message'])?></div>
              <?php endif; ?>
              <?php if (isset($ilsDetails['renewable']) && $ilsDetails['renewable'] && isset($ilsDetails['renew_link'])): ?>
                <a href="<?=$this->escapeHtmlAttr($ilsDetails['renew_link'])?>"><?=$this->transEsc('renew_item')?></a>
              <?php endif; ?>
              <?php if (!empty($ilsDetails['fine'])): ?>
                <strong><?=$this->transEsc('Checkout Fine')?>:</strong> <span class="label label-danger"><?=$ilsDetails['fine']?> Kč</span>
              <?php endif; ?>
            </div>
            <?php if ($thumbnail && $thumbnailAlignment == 'right'): ?>
              <?=$thumbnail ?>
            <?php endif ?>
          </div>
          <?=$resource->tryMethod('supportsCoinsOpenUrl') ? '<span class="Z3988" title="' . $this->escapeHtmlAttr($resource->getCoinsOpenUrl()) . '"></span>' : ''?>
        </li>
      <?php endforeach; ?>
    </ul>
  <?php if ($this->renewForm): ?></form><?php endif; ?>
  <?=$paginator ? $this->paginationControl($paginator, 'Sliding', 'Helpers/pagination.phtml', ['params' => $this->params]) : ''?>
<?php elseif (!(isset($this->error) && $this->error)): ?>
  <div class="alert alert-info">
    <?=$this->transEsc('You do not have any items checked out')?>.
  </div>
<?php endif; ?>

<?=$this->inlineScript(\Laminas\View\Helper\HeadScript::FILE, 'checkouts.js') ?>
