<?php
    // Set up page title:
    $this->headTitle($this->translate('Checked Out Items'));

    // Set up breadcrumbs:
    $this->layout()->breadcrumbs = '<li><a href="' . $this->url('myresearch-home') . '">' . $this->transEsc('Your Account') . '</a></li> <li class="active">' . $this->transEsc('Checked Out Items') . '</li>';

    // Check if "Renew All" button can be displayed:
    $renewAll = !$this->ilsPaging || !$paginator;

    $loadJsCheckedOut = <<<JS
          function loadCheckedOut(element) {
            VuFind.covers.init();
            // Checkbox select all
            $(element).find('.checkbox-select-all').on('change', function selectAllCheckboxes() {
              var form = this.form ? $(this.form) : $(this).closest('form');
              if (this.checked) {
                form.find('.checkbox-select-item:not(:checked)').trigger('click');
              } else {
                form.find('.checkbox-select-item:checked').trigger('click');
              }
              $('[form="' + form.attr('id') + '"]').prop('checked', this.checked);
              form.find('.checkbox-select-all').prop('checked', this.checked);
              $('.checkbox-select-all[form="' + form.attr('id') + '"]').prop('checked', this.checked);
            });

            var confirmRenewRequest = function confirmRenewRequest(link, action) {
              $(element).find('#cancelConfirm').val(1);
              $(element).find('#submitType').attr('name', action);
              $(link).parents('form').submit();
            };

            $(element).find('#confirm_renew_selected_yes').click(function cancelSelectedRequests(e) {
              e.preventDefault();
              confirmRenewRequest(this, 'renewSelected');
            });
            $(element).find('#confirm_renew_all_yes').click(function cancelAllRequests(e) {
              e.preventDefault();
              confirmRenewRequest(this, 'renewAll');
            });
            $(element).find('.confirm_renew_no').click(function doNotCancelRequest(e) {
              e.preventDefault();
            });
            $(element).find('#update_selected').click(function updateSelected() {
              // Change submitType to indicate that this is not a cancel request:
              $(element).find('#submitType').attr('name', 'updateSelected');
            });

            $(element).find("form").submit(function onSubmit(event) {
              event.preventDefault();
              hideLibraryCardContent(element);
              var button = $(document.activeElement);
              var form = $(this);
              var page = form.find('input[name="page"]').val();
              var url = $(element).data('action') + '?page=' + page;
              var data = form.serialize() + '&' + button.attr('id') + '=' + button.val()
                + '&cardId=' + $(element).data('card-id');
              $.ajax({
                type: "POST",
                url: url,
                data: data,
                success: function onSuccess(content) {
                  showLibraryCardContent(element, content, function onComplete() {
                    loadCheckedOut(element);
                  });
                }
              });
            });
            $(element).find("ul.pagination>li>a").click(function onClick(event){
              event.preventDefault();
              hideLibraryCardContent(element);
              link = $(this).attr('href');
              $.ajax({
                type: "GET",
                url: link,
                success: function onSuccess(content) {
                  showLibraryCardContent(element, content, function onComplete() {
                    loadCheckedOut(element);
                  });
                }
              });
            });
          };
        JS;

    $loadJsHistory = <<<JS
          function loadHistoricLoans(element) {
            VuFind.covers.init();
            const reloadContent = function reloadContent(link){
              hideLibraryCardContent(element, true);
              reloadLibraryCardContent(element, link);
            };
            $(element).find("ul.pagination>li>a").click(function onClick(event){
              event.preventDefault();
              link = $(this).attr('href');
              reloadContent(link);
            });
            $(element).find("select.sublibrary").on('change', function onChange(event){
              event.preventDefault();
              const link = $(this).find(":selected").data('href');
              reloadContent(link);
            });

            var confirmPurgeRequest = function confirmPurgeRequest(link, action) {
              $('#submitType').attr('name', action);
              $(link).parents('form').trigger("submit");
            }
            // Purge loan history:
            $('#confirm_purge_selected_yes').on("click", function renewSelectedRequests(e) {
              e.preventDefault();
              confirmPurgeRequest(this, 'purgeSelected');
            });
            $('#confirm_purge_all_yes').on("click", function renewAllRequests(e) {
              e.preventDefault();
              confirmPurgeRequest(this, 'purgeAll');
            });
            $('.confirm_purge_no').on("click", function doNotRenewRequest(e) {
              e.preventDefault();
            });
          };
        JS;
?>

<a class="search-filter-toggle visible-xs" href="#myresearch-sidebar" data-bs-toggle="offcanvas" title="Expand Sidebar">
  <?=$this->transEsc('Your Account') ?>
</a>

<div class="<?=$this->layoutClass('mainbody')?>">
  <div class="context-help">
    <h2 class="context-text"><?=$this->transEsc('Checked Out Items')?></h2>
    <?=$this->contextHelp('checked-out', 'heading')?>
  </div>
  <?=$this->flashmessages();?>
  <p>
    <?=$this->context($this)->renderInContext('librarycards/listcards.phtml', [
      'user' => $this->auth()->getUserObject(),
      'action' => [
        'current_loans' => $this->url('myresearch-checkedoutajax'),
        'loan_history' => $this->url('checkouts-historyajax'),
      ],
      'callback' => [
        'current_loans' => 'loadCheckedOut',
        'loan_history' => 'loadHistoricLoans',
      ],
      'tabNames' => [
        'current_loans' => $this->transEsc('Your Checked Out Items'),
        'loan_history' => $this->transEsc('Loan History'),
      ],
      'useTabsForCardIds' => $this->isLoanHistoryAvailableForCardIds,
    ]);
    ?>
  </p>
</div>

<div class="<?=$this->layoutClass('sidebar')?>" id="myresearch-sidebar">
  <?=$this->accountMenu()->render('checkedout')?>
</div>

<?=$this->render('myresearch/notify-account-status.phtml', ['method' => 'checkedOut', 'accountStatus' => $this->accountStatus]); ?>

<?=$this->assetManager()->outputInlineScriptString($loadJsCheckedOut)?>
<?php if (!empty($this->isLoanHistoryAvailableForCardIds)):
  echo $this->assetManager()->outputInlineScriptString($loadJsHistory);
endif;?>
<noscript><?=$this->transEsc('Please enable JavaScript.')?></noscript>
