<?=$this->flashmessages()?>
<?php if (!empty($this->checkouts) || !empty($this->checkoutsHistory)): ?>
  <div class="card card-with-tabs">
    <div class="card-header bg-transparent">
      <ul class="nav nav-tabs card-header-tabs" role="tablist">
      <li role="presentation" class="nav-item">
        <a href="#current_<?=$userCard->card_name?>" class="nav-link active" aria-controls="current_<?=$userCard->card_name?>" role="tab" data-bs-toggle="tab">
          <?=$this->transEsc('ebooks_lending_current_checkouts')?>
        </a>
      </li>
      <li role="presentation" class="nav-item">
        <a href="#history_<?=$userCard->card_name?>" class="nav-link" aria-controls="history_<?=$userCard->card_name?>" role="tab" data-bs-toggle="tab">
          <?=$this->transEsc('ebooks_lending_history')?>
        </a>
      </li>
    </ul>
    </div>
    <div class="card-body tab-content">
      <div role="tabpanel" class="tab-pane active" id="current_<?=$userCard->card_name?>">
        <?=$this->render('_palmknihy_checkouts.phtml', [
          'checkouts' => $this->checkouts ?? [],
          'lendingInterval' => $this->lendingInterval ?? 0,
        ])?>
      </div>
      <div role="tabpanel" class="tab-pane" id="history_<?=$userCard->card_name?>">
        <?=$this->render('_palmknihy_checkouts.phtml', [
          'checkouts' => $this->checkoutsHistory ?? [],
          'lendingInterval' => $this->lendingInterval ?? 0,
        ])?>
      </div>
    </div>
  </div>
<?php else: ?>
  <div class="alert alert-info">
    <?=$this->transEsc('ebooks_lending_no_checkouts')?>.
  </div>
<?php endif; ?>
