<?=$this->flashmessages();?>
<?php if (!empty($this->fines)): ?>
  <?php if (isset($this->paymentLink)):?>
    <a href="<?=$this->paymentLink?>" class="btn btn-primary payment-link">
      <?=$this->transEsc('online_payment_fine_link_text')?>
    </a>
  <?php endif; ?>
  <?php if ($this->paymentLinkText != null): ?>
    <div class="alert alert-info"><?=$this->paymentLinkText?></div>
  <?php endif; ?>

  <?php
    $fines = [
      'Not paid fines' => array_filter($this->fines, fn ($fine) => !($fine['accruing'] ?? false)),
      'Accruing checkout fines' => array_filter($this->fines, fn ($fine) => ($fine['accruing'] ?? false)),
    ];
    $fines = array_filter($fines);
    foreach ($fines as $heading => $finesPart) {
      echo '<h2>' . $this->transEsc($heading) . '</h2>';
      echo $this->render('myresearch/_fines_table.phtml', ['fines' => $finesPart, 'caption' => $heading]);
    }
  ?>

  <?php if (isset($this->missingEmailLink)):?>
    <div class="alert alert-danger">
      <?=$this->translate('payment_warning_missing_email_in_profile_with_link', ['%%url%%' => $this->missingEmailLink])?>
    </div>
  <?php endif; ?>

<?php elseif (!(isset($this->error) && $this->error)): ?>
  <div class="alert alert-info">
    <?=$this->transEsc('You do not have any fines')?>
  </div>
<?php endif; ?>
