<?php
    // Set up page title:
    $this->headTitle($this->translate('Interlibrary Loan Requests'));

    // Set up breadcrumbs:
    $this->layout()->breadcrumbs = '<li><a href="' . $this->url('myresearch-home') . '">' . $this->transEsc('Your Account') . '</a></li>'
        . '<li class="active">' . $this->transEsc('Interlibrary Loan Requests') . '</li>';
?>

<a class="search-filter-toggle visible-xs" href="#myresearch-sidebar" data-toggle="offcanvas" title="Expand Sidebar">
  <?=$this->transEsc('Your Account') ?>
</a>

<div class="<?=$this->layoutClass('mainbody')?>">
  <?=$this->render('myresearch/illrequests-form.phtml');?>
</div>


<div class="<?=$this->layoutClass('sidebar')?>" id="myresearch-sidebar">
  <?=$this->context($this)->renderInContext("myresearch/menu.phtml", ['active' => 'ILLRequests'])?>
</div>
