<?=$this->flashmessages()?>
<?php
    $itemIndex = 1;
?>

<?php if (isset($this->forms)): ?>
  <ul>
    <?php foreach($this->forms as $label => $link):?>
      <li>
        <a data-lightbox href='<?=$link?>'><?=$this->transEsc($label)?></a>
      </li>
    <?php endforeach; ?>
  </ul>
<?php endif; ?>

<?php if (!empty($this->recordList)): ?>
  <?php if ($this->cancelForm): ?>
    <form name="updateForm" class="inline" method="post" id="cancelILLRequest" data-clear-account-cache="illRequests">
      <input type="hidden" id="submitType" name="cancelSelected" value="1">
      <input type="hidden" id="cancelConfirm" name="confirm" value="0">
      <div class="btn-group">
        <input id="cancelSelected" name="cancelSelected" type="submit" value="<?=$this->transEscAttr('ill_request_cancel_selected') ?>" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
        <ul class="dropdown-menu">
          <li class="disabled"><a><?=$this->transEsc('confirm_ill_request_cancel_selected_text') ?></a></li>
          <li><a href="#" id="confirm_cancel_selected_yes"><?=$this->transEsc('confirm_dialog_yes') ?></a></li>
          <li><a href="#" class="confirm_cancel_no"><?=$this->transEsc('confirm_dialog_no')?></a></li>
        </ul>
      </div>
      <div class="btn-group">
        <input id="cancelAll" name="cancelAll" type="submit" value="<?=$this->transEscAttr('ill_request_cancel_all') ?>" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
        <ul class="dropdown-menu">
          <li class="disabled"><a><?=$this->transEsc('confirm_ill_request_cancel_all_text') ?></a></li>
          <li><a href="#" id="confirm_cancel_all_yes"><?=$this->transEsc('confirm_dialog_yes') ?></a></li>
          <li><a href="#" class="confirm_cancel_no"><?=$this->transEsc('confirm_dialog_no')?></a></li>
        </ul>
      </div>
  <?php endif; ?>

  <ul class="record-list">
    <?php $iteration = 0; ?>
    <?php foreach ($this->recordList as $resource): ?>
      <?php $iteration++; ?>
      <?php $ilsDetails = $resource->getExtraDetail('ils_details'); ?>
      <li id="record<?=$this->escapeHtmlAttr($resource->getUniqueId()) ?>" class="result">
        <strong class="pull-left order"><?= $itemIndex++ ?>.</strong>
        <?php if ($this->cancelForm && isset($ilsDetails['cancel_details'])): ?>
          <?php $safeId = preg_replace('/[^a-zA-Z0-9]/', '', $resource->getUniqueId()); ?>
          <div class="checkbox">
            <input type="hidden" name="cancelAllIDS[]" value="<?=$this->escapeHtmlAttr($ilsDetails['cancel_details']) ?>">
            <label>
              <input type="checkbox" name="cancelSelectedIDS[]" value="<?=$this->escapeHtmlAttr($ilsDetails['cancel_details']) ?>" id="checkbox_<?=$safeId?>">
            </label>
          </div>
        <?php endif; ?>

        <?php
          $link = null;
          if (!is_a($resource, 'VuFind\\RecordDriver\\Missing')) {
              $link = $this->recordLinker()->getUrl($resource);
          }
          $coverDetails = $this->record($resource)->getCoverDetails('illrequests', 'small', $link);
          $cover = $coverDetails['html'];
          $thumbnail = false;
          $thumbnailAlignment = $this->record($resource)->getThumbnailAlignment('account');
          if ($cover):
            ob_start(); ?>
            <div class="media-<?=$thumbnailAlignment ?> <?=$this->escapeHtmlAttr($coverDetails['size'])?>">
              <?=$cover ?>
            </div>
            <?php $thumbnail = ob_get_contents(); ?>
          <?php ob_end_clean(); ?>
        <?php endif; ?>
        <div class="media">
          <?php if ($thumbnail && $thumbnailAlignment == 'left'): ?>
            <?=$thumbnail ?>
          <?php endif ?>
          <div class="media-body">
            <?=$this->record($resource)->renderTemplate('account-entry.phtml')?>
            <?php if (isset($ilsDetails['imprint']) && !empty($ilsDetails['imprint'])): ?>
              <strong><?=$this->transEsc('ill_imprint')?>:</strong> <?=$this->escapeHtml($ilsDetails['imprint'])?><br>
            <?php endif; ?>

            <?php if (isset($ilsDetails['article_title']) && !empty($ilsDetails['article_title'])): ?>
              <strong><?=$this->transEsc('ill_article_title')?>:</strong> <?=$this->escapeHtml($ilsDetails['article_title'])?><br>
            <?php endif; ?>

            <?php if (isset($ilsDetails['article_author']) && !empty($ilsDetails['article_author'])): ?>
              <strong><?=$this->transEsc('ill_article_author')?>:</strong> <?=$this->escapeHtml($ilsDetails['article_author'])?><br>
            <?php endif; ?>

            <?php if (isset($ilsDetails['pickup_location']) && !empty($ilsDetails['pickup_location'])): ?>
              <strong><?=$this->transEsc('ill_pickup_location')?>:</strong> <?=$this->escapeHtml($ilsDetails['pickup_location'])?><br>
            <?php endif; ?>

            <?php if (isset($ilsDetails['media']) && !empty($ilsDetails['media'])): ?>
              <strong><?=$this->transEsc('ill_request_type')?>:</strong> <?=$this->transEsc(['ILL', 'media_' . $ilsDetails['media']], [], $ilsDetails['media'])?><br>
            <?php endif; ?>

            <?php if (isset($ilsDetails['price']) && !empty($ilsDetails['price'])): ?>
              <strong><?=$this->transEsc('ill_price')?>:</strong> <?=$this->transEsc(['ILL', 'price_' . $ilsDetails['price']], [], $ilsDetails['price'])?><br>
            <?php endif; ?>

            <?php if (isset($ilsDetails['docno']) && !empty($ilsDetails['docno'])): ?>
              <strong><?=$this->transEsc('ill_request_no')?>:</strong> <?=$this->escapeHtml($ilsDetails['docno'])?><br>
            <?php endif; ?>

            <?php /* Depending on the ILS driver, the "location" value may be a string or an ID; figure out the best
              value to display... */ ?>
            <?php $pickupDisplay = ''; ?>
            <?php $pickupTranslate = false; ?>
            <?php if (isset($ilsDetails['location'])): ?>
              <?php if ($this->pickup): ?>
                <?php foreach ($this->pickup as $library): ?>
                  <?php if ($library['locationID'] == $ilsDetails['location']): ?>
                    <?php $pickupDisplay = $library['locationDisplay']; ?>
                    <?php $pickupTranslate = true; ?>
                  <?php endif; ?>
                <?php endforeach; ?>
              <?php endif; ?>
              <?php if (empty($pickupDisplay)): ?>
                <?php $pickupDisplay = $ilsDetails['location']; ?>
              <?php endif; ?>
            <?php endif; ?>
            <?php if (!empty($pickupDisplay)): ?>
              <strong><?=$this->transEsc('pick_up_location') ?>:</strong>
              <?=$pickupTranslate ? $this->transEsc($pickupDisplay) : $this->escapeHtml($pickupDisplay)?>
              <br>
            <?php endif; ?>

            <?php if (!empty($ilsDetails['create'])): ?>
              <strong><?=$this->transEsc('Created') ?>:</strong> <?=$this->escapeHtml($ilsDetails['create']) ?>
              <?php if (!empty($ilsDetails['expire'])): ?>|<?php endif; ?>
            <?php endif; ?>
            <?php if (!empty($ilsDetails['expire'])): ?>
              <strong><?=$this->transEsc('ill_request_expires') ?>:</strong> <?=$this->escapeHtml($ilsDetails['expire']) ?>
            <?php endif; ?>
            <br>

            <?php if (isset($this->cancelResults['items'])): ?>
              <?php foreach ($this->cancelResults['items'] as $itemId => $cancelResult): ?>
                <?php if ($itemId == $ilsDetails['item_id'] && $cancelResult['success'] == false): ?>
                  <div class="alert alert-danger"><?=$this->transEsc($cancelResult['status']) ?><?php if ($cancelResult['sysMessage']) {
                  echo ' : ' . $this->transEsc($cancelResult['sysMessage']);
                  } ?></div>
                <?php endif; ?>
              <?php endforeach; ?>
            <?php endif; ?>

            <?php if (isset($ilsDetails['in_transit']) && $ilsDetails['in_transit']): ?>
              <div class="text-success"><?=$this->transEsc('request_in_transit') . (is_string($ilsDetails['in_transit']) ? ': ' . $this->transEsc('institution_' . $ilsDetails['in_transit'], [], $ilsDetails['in_transit']) : '') ?></div>
            <?php endif; ?>
            <?php if (isset($ilsDetails['processed']) && $ilsDetails['processed']): ?>
              <div class="text-success"><?=$this->transEsc('ill_request_processed') . (is_string($ilsDetails['processed']) ? ': ' . $ilsDetails['processed'] : '') ?></div>
            <?php endif; ?>
            <?php if (isset($ilsDetails['available']) && $ilsDetails['available']): ?>
              <div class="text-success"><?=$this->transEsc('ill_request_available') ?></div>
            <?php endif; ?>
            <?php if (isset($ilsDetails['canceled']) && $ilsDetails['canceled']): ?>
              <div class="text-success"><?=$this->transEsc('ill_request_canceled') . (is_string($ilsDetails['canceled']) ? ': ' . $ilsDetails['canceled'] : '') ?></div>
            <?php endif; ?>
            <?php if (isset($ilsDetails['cancel_link'])): ?>
              <p><a href="<?=$this->escapeHtmlAttr($ilsDetails['cancel_link']) ?>"><?=$this->transEsc('ill_request_cancel') ?></a></p>
            <?php endif; ?>
          </div>
          <?php if ($thumbnail && $thumbnailAlignment == 'right'): ?>
            <?=$thumbnail ?>
          <?php endif ?>
        </div>
        <?=$resource->tryMethod('supportsCoinsOpenUrl') ? '<span class="Z3988" title="' . $this->escapeHtmlAttr($resource->getCoinsOpenUrl()) . '"></span>' : ''?>
      </li>
    <?php endforeach; ?>
  </ul>
  <?php if ($this->cancelForm): ?></form><?php endif; ?>
<?php elseif (!(isset($this->error) && $this->error)): ?>
  <div class="alert alert-info">
    <?=$this->transEsc('You do not have any interlibrary loan requests placed') ?>.
  </div>
<?php endif; ?>
