<?php
    // Set up page title:
    $this->headTitle($this->translate('Interlibrary Loan Requests'));

    // Set up breadcrumbs:
    $this->layout()->breadcrumbs = '<li><a href="' . $this->url('myresearch-home') . '">' . $this->transEsc('Your Account') . '</a></li>'
        . '<li class="active">' . $this->transEsc('Interlibrary Loan Requests') . '</li>';
?>

<a class="search-filter-toggle visible-xs" href="#myresearch-sidebar" data-bs-toggle="offcanvas" title="Expand Sidebar">
  <?=$this->transEsc('Your Account') ?>
</a>

<div class="<?=$this->layoutClass('mainbody')?>">

  <?php $this->slot('ill-requests-title')->start(); ?>
    <h2><?=$this->transEsc('Interlibrary Loan Requests')?></h2>
  <?=$this->slot('ill-requests-title')->end(); ?>

  <?=$this->flashmessages()?>
    <?=$this->context($this)->renderInContext('librarycards/listcards.phtml', [
      'user' => $this->auth()->getUserObject(),
      'action' => $this->url('myresearch-illrequestsajax'),
    ]);
    ?>
</div>


<div class="<?=$this->layoutClass('sidebar')?>" id="myresearch-sidebar">
  <?=$this->accountMenu()->render('ILLRequests')?>
</div>

<?=$this->render('myresearch/notify-account-status.phtml', ['method' => 'fines', 'accountStatus' => $this->accountStatus]); ?>
