<?=$this->component('hide-offcanvas-button')?>
<?php foreach ($this->menu as $menuGroup): ?>
<div class="card text-bg-light border-0">
  <div class="card-body">
    <h3 class="card-title" id="<?=$this->idPrefix ?? ''?><?=$menuGroup['id']?>"><?=$this->transEsc($menuGroup['label'])?></h3>
    <nav class="myresearch-menu" aria-labelledby="<?=$this->idPrefix ?? ''?><?=$menuGroup['id']?>">
      <div class="list-group list-group-flush <?=!empty($menuGroup['class']) ? $menuGroup['class'] : ''?>">
        <?php foreach ($menuGroup['MenuItems'] as $item): ?>
          <?=$this->render($item['template'] ?? 'myresearch/menu-item.phtml', ['active' => $this->active, ...$item])?>
        <?php endforeach; ?>
      </div>
    </nav>
  </div>
</div>
<?php endforeach ?>
