<?php if (isset($this->menu['Account'])): ?>
<?php $menuGroup = $this->menu['Account'] ?>
<ul class="dropdown-menu dropdown-menu dropdown-menu-end myresearch-menu<?=!empty($menuGroup['class']) ? ' ' . $menuGroup['class'] : ''?>">
  <?php foreach ($menuGroup['MenuItems'] as $item): ?>
    <?=$this->render($item['template'] ?? 'myresearch/menu-header-item.phtml', ['active' => $this->active, ...$item])?>
  <?php endforeach; ?>
</ul>
<?=$this->assetManager()->outputInlineScriptString(<<<'JS'
    document.getElementById("account-home-nav")?.addEventListener("show.bs.dropdown", function() {
      VuFind.account.notify("fines", { total: NaN });
    });
    JS)?>
<?php endif; ?>
