<?php
  // Grab list object from search results (if applicable):
  $list = $this->results->getListObject();

  // Set up page title:
  $this->headTitle(isset($list) ? $list->getTitle() : $this->translate('saved_items'));

  // Set up breadcrumbs:
  $currPage = isset($list) ? 'List' : 'saved_items';
  $this->breadcrumbs()->set($this->translate('Your Account'), $this->url('myresearch-home'))
    ->add($this->translate($currPage), active: true);

  // Load Javascript dependencies into header:
  $this->assetManager()->appendScriptLink('check_item_statuses.js');

  // Load Javascript only if list view parameter is NOT full:
  if ($this->params->getOptions()->getListViewOption() != 'full') {
    $this->assetManager()->appendScriptLink('record.js');
    $this->assetManager()->appendScriptLink('embedded_record.js');
  }

  $recordTotal = $this->results->getResultTotal();

  // Convenience variable:
  $account = $this->auth()->getManager();
  $user = $this->auth()->getUserObject();
?>

<?=$this->component('show-account-menu-button')?>

<div class="<?=$this->layoutClass('mainbody')?>">
  <div class="context-help">
    <h2 class="context-text"><?=$list ? $this->escapeHtml($list->getTitle()) : $this->transEsc('saved_items')?></h2>
    <?=$this->contextHelp('my-list', 'heading')?>
  </div>

  <?php if ($list && $user && $list->getUser()->getId() === $user->getId() && $list->isPublic()): ?>
    <strong>
      <?=$this->icon('user-public-list-indicator', 'user-list__public-icon') ?>
      <?=$this->transEscAttr('public_list_indicator') ?>
    </strong>
  <?php endif; ?>

  <?=$this->flashmessages()?>

  <?php if ($user && $user->couldManageInspirationLists() && $list): ?>
    <form id="category-selector-form" method="POST">
      <label for="list-category-selector"><?=$this->translate('list_category')?></label>:
      <select id="list-category-selector" name="category">
        <?php foreach ($this->categories as $category): ?>
          <option value="<?=$category->category?>"<?=($list->category === $category->category) ? ' selected="selected"' : ''?>><?=$category->description?></option>
        <?php endforeach; ?>
      </select>
    </form>
  <?php endif; ?>

  <nav class="search-header hidden-print">
    <div class="search-stats">
      <?php if ($recordTotal > 0): ?>
        <?php
          $transParams = [
            '%%start%%' => $this->localizedNumber($this->results->getStartRecord()),
            '%%end%%' => $this->localizedNumber($this->results->getEndRecord()),
            '%%total%%' => $this->localizedNumber($recordTotal),
          ];
        ?>
        <?=$this->translate('showing_items_of_html', $transParams); ?>
      <?php endif; ?>
    </div>
    <div class="search-controls">
      <?php if (isset($list)): ?>
        <?php if ($this->userlist()->userCanEditList($account->getUserObject(), $list)): ?>
          <a href="<?=$this->url('editList', ['id' => $list->getId()]) ?>" class="btn btn-link icon-link">
            <?=$this->icon('user-list-edit', 'icon-link__icon') ?>
            <span class="icon-link__label"><?=$this->transEsc('edit_list')?></span>
          </a>
          <?=
            $this->component(
                'confirm-button',
                [
                    'buttonLink' => $this->url('myresearch-deletelist', [], ['query' => ['listID' => $list->getId()]]),
                    'buttonIcon' => 'user-list-delete',
                    'buttonLabel' => 'delete_list',
                    'confirmLink' => $this->url('myresearch-deletelist', [], ['query' => ['listID' => $list->getId(), 'confirm' => 1]]),
                    'header' => 'confirm_delete_list_text',
                ]
            )
          ?>
        <?php endif; ?>
      <?php endif; ?>
      <?php if ($recordTotal > 0): ?>
        <?=$this->render('search/controls/limit.phtml')?>
        <?=$this->render('search/controls/sort.phtml')?>
      <?php endif; ?>
    </div>
  </nav>
  <?php if ($list && !empty($listDescription = $list->getDescription())): ?>
    <p><?=$this->escapeHtml($listDescription)?></p>
  <?php endif; ?>
  <?php if (!empty($listTags)): ?>
    <div><strong><?=$this->transEsc('Tags')?>:</strong> <span class="list-tags"><?=implode(', ', array_map([$this, 'escapeHtml'], $listTags))?></span></div>
  <?php endif; ?>
  <?php if ($this->listBlock && $list && $list->public): ?>
    <a href="#" id="show-list-search-url" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#modal-search"><?=$this->translate('list-show-search-url')?></a>
    <a href="#" id="show-list-detail-url" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#modal-detail"><?=$this->translate('list-show-detail-url')?></a>
    <div id="modal-search" class="modal fade hidden-print" tabindex="-1" aria-labelledby="modal-search-label" aria-hidden="true">
      <div class="modal-dialog modal-lg">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
            <h2 id="modal-search-label"><?=$this->transEsc('list-search-url') ?></h2>
            <pre id="searchUrl" class="alert alert-light"><?=$this->escapeHtml($this->serverUrl() . $this->listBlock['searchUrl'])?></pre>
            <?=$this->copyToClipboardButton('#searchUrl', false);?>
          </div>
        </div>
      </div>
    </div>
    <div id="modal-detail" class="modal fade hidden-print" tabindex="-1" aria-labelledby="modal-detail-label" aria-hidden="true">
      <div class="modal-dialog modal-lg">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
            <h2 id="modal-detail-label"><?=$this->transEsc('list-detail-url') ?></h2>
            <pre id="listUrl" class="alert alert-light"><?=$this->escapeHtml($this->serverUrl() . $this->listBlock['listUrl'])?></pre>
            <?=$this->copyToClipboardButton('#listUrl', false);?>
          </div>
        </div>
      </div>
    </div>
  <?php endif; ?>
  <?php if ($recordTotal > 0): ?>
    <?php $multiPageSelection = ($this->config()->get('config')['Social']['multi_page_favorites_selection'] ?? true) ? ' multi-page-selection' : ''; ?>
    <form class="form-inline<?= $multiPageSelection ?>" id="form-favorites<?=($listId = $list?->getId()) ? '-' . $listId : ''?>" method="post" name="bulkActionForm" action="<?=$this->url('cart-myresearchbulk')?>" data-lightbox data-lightbox-onsubmit="bulkFormHandler">
      <?=$this->context($this)->renderInContext('myresearch/bulk-action-buttons.phtml', ['idPrefix' => '', 'list' => $list ?? null, 'account' => $this->account])?>
      <input class="hidden all-ids-global" type="text" name="all_ids_global" value="<?= $this->escapeHtmlAttr(json_encode($this->results->getAllIds())) ?>">
      <ul class="record-list">
        <?php foreach ($this->results->getResults() as $i => $current): ?>
          <?=$this->record($current)->getListEntry($list, $user)?>
        <?php endforeach; ?>
      </ul>
      <?=$this->context($this)->renderInContext('myresearch/bulk-action-buttons.phtml', ['isBottom' => true, 'list' => $list ?? null, 'account' => $this->account])?>
    </form>
    <?=$this->paginationControl($this->results->getPaginator(), 'Sliding', 'Helpers/pagination.phtml', ['params' => ['results' => $this->results]])?>
  <?php else: ?>
    <p><?=$this->transEsc('You do not have any saved resources')?></p>
  <?php endif; ?>
</div>

<div class="<?=$this->layoutClass('sidebar')?>" id="myresearch-sidebar" role="navigation" aria-label="<?=$this->transEsc('account_menu_label')?>">
  <?=$this->accountMenu()->render(isset($list) ? 'list' . $list->getId() : 'favorites')?>
  <?php foreach ($this->results->getRecommendations('side') as $current): ?>
    <?=$this->recommend($current)?>
  <?php endforeach; ?>
</div>

<?php
$script = <<<JS
                $('#list-category-selector').change(function changeCategory() {
                  $('#category-selector-form').submit();
                });
              JS;
?>
<?=$this->assetManager()->outputInlineScriptString($script)?>
