<?php
    // Set up page title:
    $this->headTitle($this->translate('My Profile'));

    // Set up breadcrumbs:
    $this->layout()->breadcrumbs = '<li><a href="' . $this->url('myresearch-home') . '">' . $this->transEsc('Your Account') . '</a></li> <li class="active">' . $this->transEsc('Profile') . '</li>';

?>

<a class="search-filter-toggle visible-xs" href="#myresearch-sidebar" data-bs-toggle="offcanvas" title="Expand Sidebar">
  <?=$this->transEsc('Your Account') ?>
</a>

<div class="<?=$this->layoutClass('mainbody')?>">
  <div class="context-help">
    <h2 class="context-text"><?=$this->transEsc('Library Catalog Profile')?></h2>
    <?=$this->contextHelp('profile', 'heading')?>
  </div>
  <?=$this->flashmessages();?>
  <p>
    <?=$this->context($this)->renderInContext('librarycards/listcards.phtml', [
      'user' => $this->auth()->getUserObject(),
      'action' => $this->url('myresearch-profileajax'),
      ]);
    ?>
  </p>
</div>

<div class="<?=$this->layoutClass('sidebar')?>" id="myresearch-sidebar">
  <?=$this->accountMenu()->render('profile')?>
</div>

<?=$this->render('myresearch/notify-account-status.phtml', ['method' => 'fines', 'accountStatus' => $this->accountStatus]); ?>
