<?php
    // Set up page title:
    $this->headTitle($this->translate('My Profile'));

    // Set up breadcrumbs:
    $this->layout()->breadcrumbs = '<li><a href="' . $this->url('myresearch-home') . '">' . $this->transEsc('Your Account') . '</a></li> <li class="active">' . $this->transEsc('Profile') . '</li>';

    // Template for use by the renderArray helper:
    $arrTemplate = '<tr><th>%%LABEL%%:</th><td> %%VALUE%%</td></tr>';
?>

<a class="search-filter-toggle visible-xs" href="#myresearch-sidebar" data-toggle="offcanvas" title="Expand Sidebar">
  <?=$this->transEsc('Your Account') ?>
</a>

<div class="<?=$this->layoutClass('mainbody')?>">
  <?=$this->flashmessages();?>

  <div id="account-actions">
    <?php if ($this->auth()->getManager()->supportsEmailChange()): ?>
      <a class="btn btn-default" href="<?=$this->url('myresearch-changeemail') ?>">
        <?=$this->icon('profile-email') ?> <?=$this->transEsc('Change Email Address') ?>
      </a>
    <?php endif; ?>

    <?php if ($this->auth()->getManager()->supportsPasswordChange()): ?>
      <a class="btn btn-default" href="<?=$this->url('myresearch-changepassword') ?>">
        <?=$this->icon('profile-change-password') ?> <?=$this->transEsc('Change Password') ?>
      </a>
    <?php endif; ?>

    <?php if ($this->accountDeletion): ?>
      <a class="btn btn-default" href="<?=$this->url('myresearch-deleteaccount') ?>" data-lightbox>
        <?=$this->icon('profile-delete') ?> <?=$this->transEsc('delete_account_title') ?>
      </a>
    <?php endif; ?>
  </div>

  <?php if (is_array($this->profile)): ?>
    <h2><?=$this->transEsc('Library Catalog Profile')?></h2>
    <p>
      <?=$this->context($this)->renderInContext('librarycards/selectcard.phtml', ['user' => $this->user]); ?>
    </p>
    <table class="table table-striped">
      <?php
        $profile = $this->profile;
        if (!empty($this->user['email'])) {
          $profile['email'] = $this->user['email'];
        }
      ?>
      <?=
        $this->renderArray(
            $arrTemplate,
            $this->profile,
            [
              $this->transEsc('First Name') => 'firstname',
              $this->transEsc('Last Name') => 'lastname',
              $this->transEsc('Email') => 'email',
              $this->transEsc('Address') . ' 1' => 'address1',
              $this->transEsc('Address') . ' 2' => 'address2',
              $this->transEsc('Zip') => 'zip',
              $this->transEsc('City') => 'city',
              $this->transEsc('Country') => 'country',
              $this->transEsc('Phone Number') => 'phone',
              $this->transEsc('Mobile Number') => 'mobile_phone',
              $this->transEsc('Group') => 'group',
              $this->transEsc('patron_account_expires') => 'expiration_date'
            ]
        );
      ?>
    </table>
  <?php elseif ('ils-none' !== $this->ils()->getOfflineMode() && $this->patronLoginView && !empty($this->patronLoginView->getTemplate())): ?>
    <?=$this->partial($this->patronLoginView);?>
  <?php endif; ?>
</div>

<div class="<?=$this->layoutClass('sidebar')?>" id="myresearch-sidebar">
  <?=$this->context($this)->renderInContext("myresearch/menu.phtml", ['active' => 'profile'])?>
</div>
