<?php
    // Set up page title:
    $this->headTitle($this->translate('My Profile'));

    // Set up breadcrumbs:
    $this->layout()->breadcrumbs = '<li><a href="' . $this->url('myresearch-home') . '">' . $this->transEsc('Your Account') . '</a></li> <li class="active">' . $this->transEsc('Profile') . '</li>';

    // Template for use by the renderArray helper:
    $arrTemplate = '<tr><th>%%LABEL%%:</th><td> %%VALUE%%</td></tr>';
?>

<a class="search-filter-toggle visible-xs" href="#myresearch-sidebar" data-toggle="offcanvas" title="<?=$this->transEsc('sidebar_expand')?>">
  <?=$this->transEsc('Your Account') ?>
</a>

<div class="<?=$this->layoutClass('mainbody')?>">
  <?=$this->flashmessages();?>

  <div id="account-actions">
    <?php if ($this->auth()->getManager()->supportsEmailChange()): ?>
      <a class="btn btn-default icon-link" href="<?=$this->url('myresearch-changeemail') ?>">
        <?=$this->icon('profile-email', 'icon-link__icon') ?>
        <span class="icon-link__label"><?=$this->transEsc('Change Email Address') ?></span>
      </a>
    <?php endif; ?>

    <?php if ($this->auth()->getManager()->supportsPasswordChange()): ?>
      <a class="btn btn-default icon-link" href="<?=$this->url('myresearch-changepassword') ?>">
        <?=$this->icon('profile-change-password', 'icon-link__icon') ?>
        <span class="icon-link__label"><?=$this->transEsc('Change Password') ?></span>
      </a>
    <?php endif; ?>

    <?php if ($this->accountDeletion): ?>
      <a class="btn btn-default icon-link" href="<?=$this->url('myresearch-deleteaccount') ?>" data-lightbox>
        <?=$this->icon('profile-delete', 'icon-link__icon') ?>
        <span class="icon-link__label"><?=$this->transEsc('delete_account_title') ?></span>
      </a>
    <?php endif; ?>
  </div>

  <?php if (is_array($this->profile)): ?>
    <h2><?=$this->transEsc('Library Catalog Profile')?></h2>
    <p>
      <?=$this->context($this)->renderInContext('librarycards/selectcard.phtml', ['user' => $this->user]); ?>
    </p>
    <table class="table table-striped catalog-profile">
      <?php
        $profile = $this->profile;
        if (!empty($this->user['email'])) {
          $profile['email'] = $this->user['email'];
        }
      ?>
      <?=
        $this->renderArray(
            $arrTemplate,
            $this->profile,
            [
              $this->transEsc('First Name') => 'firstname',
              $this->transEsc('Last Name') => 'lastname',
              $this->transEsc('Email') => 'email',
              $this->transEsc('Address') . ' 1' => 'address1',
              $this->transEsc('Address') . ' 2' => 'address2',
              $this->transEsc('Zip') => 'zip',
              $this->transEsc('City') => 'city',
              $this->transEsc('Country') => 'country',
              $this->transEsc('Phone Number') => 'phone',
              $this->transEsc('Mobile Number') => 'mobile_phone',
              $this->transEsc('Group') => 'group',
              $this->transEsc('patron_account_expires') => 'expiration_date',
            ]
        );
      ?>
    </table>
    <?php
      $proxyValues = [];
      if (!empty($this->proxiedUsers)) {
        $proxyValues['proxy_list_for'] = $this->proxiedUsers;
      }
      if (!empty($this->proxyingUsers)) {
        $proxyValues['proxy_list_by'] = $this->proxyingUsers;
      }
    ?>
    <?php if (!empty($proxyValues)): ?>
      <h3><?=$this->transEsc('proxy_list_heading')?></h3>
      <p><?=$this->transEsc('proxy_list_description')?></p>
      <?php foreach ($proxyValues as $proxyHeading => $proxyValueGroup): ?>
        <h4><?=$this->transEsc($proxyHeading)?></h4>
        <?php natsort($proxyValueGroup); ?>
        <ul>
          <?php foreach ($proxyValueGroup as $proxyValue): ?>
            <li><?=$this->escapeHtml($proxyValue)?></li>
          <?php endforeach; ?>
        </ul>
      <?php endforeach; ?>
    <?php endif; ?>
  <?php elseif ('ils-none' !== $this->ils()->getOfflineMode() && $this->patronLoginView && !empty($this->patronLoginView->getTemplate())): ?>
    <?=$this->partial($this->patronLoginView);?>
  <?php endif; ?>
</div>

<div class="<?=$this->layoutClass('sidebar')?>" id="myresearch-sidebar" role="navigation" aria-label="<?=$this->transEsc('account_menu_label')?>">
  <?=$this->context($this)->renderInContext('myresearch/menu.phtml', ['active' => 'profile'])?>
</div>
