<?php if (!empty($this->links)):?>
  <ul>
    <?php foreach ($this->links as $link): ?>
      <li>
        <a href="<?=$this->recordLinker()->getUrl($link['id'])?>"><?=$this->transEsc($link['label'])?></a>
      </li>
    <?php endforeach; ?>
  </ul>
<?php endif; ?>

<?=$this->flashmessages()?>

<?php if (!empty($this->recordList)): ?>
  <?php if ($this->cancelForm): ?>
    <form name="updateForm" class="inline" method="post" action="<?=$this->escapeHtmlAttr($this->url('myresearch-shortloans'))?>" id="update_short_loans" data-clear-account-cache="shortloans" data-lightbox>
    <input type="hidden" value="<?=$this->escapeHtmlAttr($this->auth()->getManager()->getCsrfHash())?>" name="csrf">
    <input type="hidden" id="submitType" name="cancelSelected" value="1">
    <input type="hidden" id="cancelConfirm" name="confirm" value="0">
    <div class="toolbar">
      <div class="checkbox">
        <label>
          <input type="checkbox" name="selectAll" class="checkbox-select-all">
            <?=$this->transEsc('select_all_on_page')?>
        </label>
        <?php if ($this->cancelForm || true): ?>
          <?=
            $this->component(
                'confirm-button',
                [
                    'buttonId' => 'cancelSelected',
                    'buttonName' => 'cancelSelected',
                    'buttonLabel' => 'short_loan_cancel_selected',
                    'header' => 'short_loan_confirm_cancel_selected',
                    'confirmId' => 'confirm_cancel_selected_yes',
                    'cancelClass' => 'confirm_cancel_no',
                    'ignoreLightbox' => true,
                ]
            )
          ?>
          <?=
            $this->component(
                'confirm-button',
                [
                    'buttonId' => 'cancelAll',
                    'buttonName' => 'cancelAll',
                    'buttonLabel' => 'short_loan_cancel_all',
                    'header' => 'short_loan_confirm_cancel_all',
                    'confirmId' => 'confirm_cancel_all_yes',
                    'cancelClass' => 'confirm_cancel_no',
                    'ignoreLightbox' => true,
                ]
            )
          ?>
        <?php endif; ?>
      </div>
    </div>
  <?php endif; ?>

  <table class="table table-striped result">
    <tr>
      <th></th>
      <th><?=$this->transEsc('short_loan_request_start')?></th>
      <th><?=$this->transEsc('short_loan_request_end')?></th>
      <th><?=$this->transEsc('Title')?></th>
      <th><?=$this->transEsc('Description')?></th>
    </tr>
    <?php foreach ($this->recordList as $resource): ?>
      <?php $ilsDetails = $resource->getExtraDetail('ils_details');?>
      <tr>
        <td>
          <div>
            <?php if ($this->cancelForm && isset($ilsDetails['cancel_details'])): ?>
              <?php $checkboxId = $this->escapeElementId('checkbox_' . $ilsDetails['cancel_details']); ?>
              <input type="hidden" name="cancelAllIDS[]" value="<?=$this->escapeHtmlAttr($ilsDetails['cancel_details']) ?>">
                <label>
                  <input type="checkbox" name="selectedIDS[]" value="<?=$this->escapeHtmlAttr($ilsDetails['cancel_details']) ?>" id="<?=$checkboxId?>" class="checkbox-select-item">
                </label>
            <?php elseif ($this->cancelForm): ?>
              <?php // Reserve space for the checkbox to keep columns aligned ?>
                <label></label>
            <?php endif; ?>
          </div>
        </td>
        <td><?=$this->transEsc($ilsDetails['start'])?></td>
        <td><?=$this->transEsc($ilsDetails['end'])?></td>
        <td>
          <a href="<?=$this->recordLinker()->getUrl($resource)?>"><?=$this->escapeHtml($resource->getTitle())?></a>
        </td>
        <td><?=$this->transEsc($ilsDetails['callnumber'])?></td>
      </tr>
    <?php endforeach; ?>
  </table>

  <?php if ($this->cancelForm): ?></form><?php endif; ?>
<?php endif; ?>
