<?php
// Set up page title:
$this->headTitle($this->translate('My Holds'));

// Set up breadcrumbs:
$this->layout()->breadcrumbs = '<li><a href="' . $this->url('myresearch-home') . '">' . $this->transEsc('Your Account') . '</a></li> <li class="active">' . $this->transEsc('My Holds') . '</li>';

$this->headScript()->appendFile('holds.js');
?>

<a class="search-filter-toggle visible-xs" href="#myresearch-sidebar" data-toggle="offcanvas" title="Expand Sidebar">
  <?=$this->transEsc('Your Holds and Recalls') ?>
</a>

<div class="<?=$this->layoutClass('mainbody')?>">
  <div class="context-help">
    <h2 class="context-text"><?=$this->transEsc('Your Holds and Recalls')?></h2>
    <?=$this->contextHelp('holds', 'heading')?>
  </div>
  <?=$this->flashmessages()?>

  <?=$this->context($this)->renderInContext('librarycards/listcards.phtml', [
    'user' => $this->auth()->isLoggedIn(),
    'action' => $this->url('holds-listajax'),
    'callback' => 'loadHolds',
  ]);
  ?>

</div>

<div class="<?=$this->layoutClass('sidebar')?>" id="myresearch-sidebar">
  <?=$this->context($this)->renderInContext("myresearch/menu.phtml", ['active' => 'holds'])?>
</div>

<?=$this->render('myresearch/notify-account-status.phtml', ['method' => 'holds', 'accountStatus' => $this->accountStatus]); ?>

<noscript><?=$this->transEsc('Please enable JavaScript.')?></noscript>
