<?php
// Set page title.
$this->headTitle($this->translate('Inspiration'));
$this->layout()->breadcrumbs = false;
?>
<div class="row">
  <?=implode('', array_map([$this, 'contentBlock'], $blocks ?? []))?>
</div>
<div class="row">
  <div class="col-xs-12">
    <h2><?=$this->translate('more_inspiration_lists')?></h2>
  </div>
  <?php $categoryIterator = 0; ?>
  <?php foreach($this->widgets as $category => $list): ?>
    <?php $categoryIterator++; ?>
    <div class="col-sm-4">
      <h3><?=$this->translate('widget_category_' . $category)?></h3>
      <?php
        foreach ($list as $widget):
          $options = $this->searchOptions($widget['searchClassId']);
          $searchAction = $options->getSearchAction();
          $listUrl = $this->url($searchAction) . "?" . http_build_query(
              [
                'lookfor' => $widget['facetField'] . ':"' . $widget['slug'] . '"',
                'type' => $widget['searchType'],
              ]
          );
          $title = $widget['list']->title_cs ?? $widget['list']->title ?? '';
      ?>
        <a href="<?=$listUrl?>" title="<?=$title?>"><?=$title?></a><br />
      <?php endforeach; ?>
    </div>
    <?php if ($categoryIterator % 3 == 0): ?>
      <div class="clearfix"></div>
    <?php endif; ?>
  <?php endforeach; ?>
</div>
