<?php
$coverDetails = $this->record($this->item)->getCoverDetails('result-list', 'medium', $this->recordLinker()->getUrl($this->item));
$cover = $coverDetails['html'];
$thumbnail = false;
$thumbnailAlignment = $this->record($this->item)->getThumbnailAlignment('result');
if ($cover):
  ob_start(); ?>
  <div class="media-<?=$thumbnailAlignment ?> <?=$this->escapeHtmlAttr($coverDetails['size'])?>">
    <?=$cover ?>
  </div>
  <?php $thumbnail = ob_get_contents(); ?>
  <?php ob_end_clean(); ?>
<?php endif; ?>
<?php $itemUrl = $this->recordLinker()->getUrl($this->item); ?>
<div class="col-xs-12 col-md-6">
  <div class="record">
    <div class="well">
      <div class="media">
        <?php $formats = $this->item->getFormats(); ?>
        <?php if ($thumbnail): ?>
          <?=$thumbnail?>
        <?php elseif (!empty($formats)): ?>
          <div class="iconlabel">
            <i class="cover-icon <?= $this->record($this->item)->getFormatClass(end($formats)) ?>"></i>
          </div>
        <?php else: ?>
          <img class="recordcover"
               src="<?= $this->url('cover-unavailable') ?>"
               alt="<?= $this->transEsc('No Cover Image') ?>">
        <?php endif; ?>
        <div class="media-body">
          <h4>
            <a href="<?=$this->escapeHtmlAttr($itemUrl) ?>">
              <?=$this->item->getTitle() ?>
            </a>
          </h4>
          <p>
            <?php $authors = $this->item->getPrimaryAuthors();
            if (!empty($authors)): ?>
              <em><?=$authors[0] ?></em>
            <?php else: ?>
              <?php $corpAuthors = $this->item->getCorporateAuthors();
              if (!empty($corpAuthors)): ?>
                <em><?=$corpAuthors[0] ?></em>
              <?php endif; ?>
            <?php endif; ?>
          </p>

          <?php $field773Data = $this->item->getField773();
          if (!empty($field773Data)): ?>
            <p>
              <span><?=$this->transEsc('field773')?></span>: <?=$this->record($this->item)->renderTemplate('data-7xx-field.phtml', ['data' => $field773Data, 'driver' => $this->item])?>
            </p>
          <?php endif; ?>

          <p>
            <?=$this->record($this->item)->getFormatList($this->item->getFormats()) ?>
          </p>

          <?=$this->record($this->item)->renderTemplate('summary.phtml', ['driver' => $this->item, 'length' => 200, 'expandable' => false])?>

          <?php $links = $this->item->getLinks();
          if (!empty($links)): ?>
            <?php $online = array_filter($links, function ($link) { return $link['status'] == 'online'; }); ?>
            <?php $dnnt = array_filter($links, function ($link) { return $link['status'] == 'dnnt'; }); ?>
            <?php if (!empty($online)): ?>
              <?php
              foreach ($online as $onlineLink) {
                if (str_ends_with($onlineLink['url'], 'pdf')) {
                  $link = $onlineLink;
                  break;
                }
              }
              $link ??= array_shift($online); ?>
              <div class="text-end">
                <a class="btn btn-primary" target="_blank" href="<?=$this->escapeHtmlAttr($link['url']) ?>"><?=$this->transEsc('read_online') ?></a>
              </div>
            <?php elseif (!empty($dnnt)): ?>
              <?php $link = array_shift($dnnt); ?>
              <div class="text-end">
                <a class="btn btn-primary" target="_blank" href="<?=$this->escapeHtmlAttr($link['url']) ?>"><?=$this->transEsc('read_online_dnnt') ?></a>
              </div>
            <?php endif; ?>
          <?php endif; ?>
        </div>
      </div>
    </div>
  </div>
</div>
