<?php
$coverDetails = $this->record($this->item)->getCoverDetails('result-list', 'medium', $this->recordLinker()->getUrl($this->item));
$cover = $coverDetails['html'];
$thumbnail = false;
$thumbnailAlignment = $this->record($this->item)->getThumbnailAlignment('result');
if ($cover):
  ob_start(); ?>
  <div class="media-<?=$thumbnailAlignment ?> <?=$this->escapeHtmlAttr($coverDetails['size'])?>">
    <?=$cover ?>
  </div>
  <?php $thumbnail = ob_get_contents(); ?>
  <?php ob_end_clean(); ?>
<?php endif; ?>
<?php $itemUrl = $this->recordLinker()->getUrl($this->item); ?>
<div class='col-xs-12 col-md-6' style='margin-bottom: 1em'>
  <div class='row'>
    <?php
    $formats = $this->item->getFormats(); ?>
    <div class='col-xs-3 col-sm-2 col-md-3'>
      <?php if ($thumbnail): ?>
        <?=$thumbnail?>
      <?php elseif (!empty($formats)): ?>
        <div class='iconlabel'>
          <i class='cover-icon <?= $this->record($this->item)->getFormatClass(end($formats)) ?>'></i>
        </div>
      <?php else: ?>
        <img class='recordcover'
             src='<?= $this->url('cover-unavailable') ?>'
             alt='<?= $this->transEsc('No Cover Image') ?>'>
      <?php endif; ?>
    </div>

    <div class='col-xs-9 col-sm-10 col-md-9 content'>
      <div class='col-xs-12 content'>
        <a href='<?=$this->escapeHtmlAttr($itemUrl) ?>'>
          <h4>
            <?=$this->item->getTitle() ?>
          </h4>
        </a>
        <p>
          <?php $authors = $this->item->getPrimaryAuthors(); if (!empty($authors)): ?>
            <em><?=$authors[0] ?></em>
          <?php else: ?>
            <?php $corpAuthors = $this->item->getCorporateAuthors(); if (!empty($corpAuthors)): ?>
              <em><?=$corpAuthors[0] ?></em>
            <?php endif; ?>
          <?php endif; ?>
        </p>
        <p>
          <?=$this->record($this->item)->getFormatList($this->item->getFormats()) ?>
        </p>
        <?php $summary = $this->item->getSummary(); $summary = isset($summary[0]) ? $this->escapeHtml($summary[0]) : false; ?>
        <?php if ($summary): ?>
          <?php $splitText = $this->splitText($summary, 200); ?>
          <p><?=$this->escapeHtml($splitText->first())?><?php if ($splitText->last()):?> …<?php endif;?></p>
        <?php endif; ?>
        <?php $links = $this->item->getLinks(); if (!empty($links)): ?>
          <?php $online = array_filter($links, function ($link) { return $link['status'] == 'online'; }); ?>
          <?php $dnnt = array_filter($links, function ($link) { return $link['status'] == 'dnnt'; }); ?>
          <?php if (!empty($online)): ?>
            <?php
              foreach($online as $onlineLink) {
                if (str_ends_with($onlineLink['url'], 'pdf')) {
                  $link = $onlineLink;
                  break;
                }
              }
              $link = $link ?? array_shift($online); ?>
            <p>
              <a class="btn btn-primary" target="_blank" href='<?=$this->escapeHtmlAttr($link['url']) ?>'><?=$this->transEsc('read_online') ?></a>
            </p>
          <?php elseif (!empty($dnnt)): ?>
            <?php $link = array_shift($dnnt); ?>
            <p>
              <a class="btn btn-primary" target="_blank" href='<?=$this->escapeHtmlAttr($link['url']) ?>'><?=$this->transEsc('read_online_dnnt') ?></a>
            </p>
          <?php endif; ?>
        <?php endif; ?>
      </div>
    </div>
  </div>
</div>
