<?php
$listName = $this->list->title_cs ?? $this->list->title ?? '';
// Set page title.
$this->headTitle($listName);
$this->layout()->breadcrumbs .= '<li class="active">' . $this->escapeHtml($listName) . '</li>';
$this->layout()->searchbox = false;
?>
<h1><?=$listName?></h1>
<?php if (!empty($this->list->description)): ?>
  <p><?=$this->list->description?></p>
<?php endif; ?>
<div class="row">
  <?php $i = 0; ?>
  <?php foreach ($this->items as $item):?>
    <?php if (get_class($item) === \VuFind\RecordDriver\Missing::class): ?>
      <?php continue; ?>
    <?php endif; ?>
    <?php $i++; ?>
    <?=$this->context($this)->renderInContext('item', ['item' => $item]); ?>
    <?php if ($i % 2 == 0): ?>
      <div class="clearfix"></div>
    <?php endif; ?>
    <?php endforeach; ?>
</div>
