<?php if(!$this->Ziskej()->isProduction()
  || ($this->ZiskejEdd()->isEnabled() && !$this->ZiskejEdd()->isProduction())
): ?>
  <div class="bar-ziskej">
    <i class="fa fa-fw fa-exclamation-triangle" aria-hidden="true"></i>
    <?php if(!$this->Ziskej()->isProduction()): ?>
      <?=$this->translate('Ziskej::ziskej_bar_info', ['%%mode%%' => $this->Ziskej()->getCurrentMode()]) ?>
    <?php endif; ?>
    <?php if ($this->ZiskejEdd()->isEnabled() && !$this->ZiskejEdd()->isProduction()): ?>
      <?=$this->translate('Ziskej::ziskej_bar_info_edd', ['%%mode%%' => $this->ZiskejEdd()->getCurrentMode()]) ?>
    <?php endif; ?>
    <a href="<?=$this->url('ziskej-admin') ?>" title="<?=$this->translate('Ziskej::ziskej_bar_change_mode_title') ?>"><?=$this->translate('Ziskej::ziskej_bar_change_mode') ?></a>
  </div>
<?php endif; ?>
