<?php
  $user = $this->auth()->isLoggedIn();
  $patron = $user ? $this->auth()->getILSPatron() : false;
  $capabilityParams = $patron ? ['patron' => $patron] : [];
  if ($user) {
    $capabilityParams['user'] = $user;
  }
  $ilsOnline = ('ils-none' !== $this->ils()->getOfflineMode());

  $active = [
    'myresearch' => [
      'checkedout-all' => 'checkedout',
      'shortloans-all' => 'shortloans',
      'history-all' => 'historicloans',
      'illrequests-all' => 'ILLRequests',
      'fines-all' => 'fines',
      'profile-all' => 'profile',
      'usersettings' => 'usersettings',
      'mylist' => 'mylist',
    ],
    'myresearchziskej' => [
      'list-all' => 'ziskej',
    ],
    'holds' => [
      'list-all' => 'holds',
    ],
    'librarycards' => [
      'home' => 'librarycards',
    ],
    'search' => [
      'history' => 'history'
    ],
  ];
  if (isset($active[$this->layout()->templateDir][$this->layout()->templateName])) {
    $this->active = $active[$this->layout()->templateDir][$this->layout()->templateName];
  }
?>

<?php if ($ilsOnline && $this->ils()->checkCapability('getMyTransactions', $capabilityParams)): ?>
<li class="<?=$this->active == 'checkedout' ? 'active' : ''?>">
  <a href="<?=$this->url('myresearch-checkedout')?>" class="flex checkedout">
    <span class="flex-col">
      <?=$this->icon('user-checked-out', 'icon-link__icon fa-fw') ?>
      <span class="icon-link__label"><?=$this->transEsc('Checked Out Items')?></span>
    </span>
    <span class="checkedout-status status hidden"><?=$this->icon('spinner') ?></span>
  </a>
</li>
<?php endif; ?>
<?php if ($ilsOnline && $this->ils()->checkCapability('getMyShortLoans', $capabilityParams)): ?>
<li class="<?=$this->active == 'shortloans' ? 'active' : ''?>">
  <a href="<?=$this->url('myresearch-shortloans')?>?require_login" class="flex">
    <span class="flex-col">
      <?=$this->icon('short-loans', 'icon-link__icon fa-fw') ?>
      <span class="icon-link__label"><?=$this->transEsc('short_loan_title_text')?></span>
    </span>
  </a>
</li>
<?php endif; ?>
<?php if ($ilsOnline && $this->ils()->checkFunction('getMyTransactionHistory', $capabilityParams)): ?>
<li class="<?=$this->active == 'historicloans' ? 'active' : ''?>">
  <a href="<?=$this->url('checkouts-history')?>" class="flex">
    <span class="flex-col">
      <?=$this->icon('user-loan-history', 'icon-link__icon fa-fw') ?>
      <span class="icon-link__label"><?=$this->transEsc('Loan History')?></span>
    </span>
  </a>
</li>
<?php endif; ?>
<?php if ($this->ziskejMvs()->isEnabled()): ?>
<li class="<?=$this->active == 'ziskej' ? 'active' : ''?>">
  <a href="<?=$this->url('myresearch-ziskej-mvs-home')?>" class="flex ziskej">
    <span class="flex-col">
      <?=$this->icon('user-ziskej', 'icon-link__icon fa-fw') ?>
      <span class="icon-link__label"><?=$this->transEsc('ZiskejMvs::service_name')?></span>
    </span>
    <span class="ziskej-status status hidden"><?=$this->icon('spinner') ?></span>
  </a>
</li>
<?php endif; ?>
<?php if ($this->ziskejEdd()->isEnabled()): ?>
  <li class="<?=$this->active == 'ziskej-edd' ? 'active' : ''?>">
    <a href="<?=$this->url('myresearch-ziskej-edd-home')?>" class="flex ziskej">
    <span class="flex-col">
      <?=$this->icon('user-ziskej-edd', 'icon-link__icon fa-fw') ?>
      <span class="icon-link__label"><?=$this->transEsc('ZiskejEdd::service_name')?></span>
    </span>
      <span class="ziskej-status status hidden"><?=$this->icon('spinner') ?></span>
    </a>
  </li>
<?php endif; ?>
<?php if ($ilsOnline && $this->ils()->checkCapability('getMyHolds', $capabilityParams)): ?>
<li class="<?=$this->active == 'holds' ? 'active' : ''?>">
  <a href="<?=$this->url('holds-list')?>" class="flex">
    <span class="flex-col">
      <?=$this->icon('user-holds', 'icon-link__icon fa-fw') ?>
      <span class="icon-link__label"><?=$this->transEsc('Holds and Recalls')?></span>
    </span>
    <span class="holds-status status hidden"><?=$this->icon('spinner') ?></span>
  </a>
</li>
<?php endif; ?>
<?php if ($ilsOnline && $this->ils()->checkFunction('StorageRetrievalRequests', $capabilityParams)): ?>
<li class="<?=$this->active == 'storageRetrievalRequests' ? 'active' : ''?>">
  <a href="<?=$this->url('myresearch-storageretrievalrequests')?>" class="flex">
    <span class="flex-col">
      <?=$this->icon('user-storage-retrievals', 'icon-link__icon fa-fw') ?>
      <span class="icon-link__label"><?=$this->transEsc('Storage Retrieval Requests')?></span>
    </span>
  </a>
</li>
<?php endif; ?>
<?php if ($ilsOnline && $this->ils()->checkFunction('ILLRequests', $capabilityParams)): ?>
<li class="<?=$this->active == 'ILLRequests' ? 'active' : ''?>">
  <a href="<?=$this->url('myresearch-illrequests')?>" class="flex">
    <span class="flex-col">
      <?=$this->icon('user-ill-requests', 'icon-link__icon fa-fw') ?>
      <span class="icon-link__label"><?=$this->transEsc('Interlibrary Loan Requests')?></span>
    </span>
  </a>
</li>
<?php endif; ?>
<?php if ($ilsOnline && $this->ils()->checkCapability('getMyFines', $capabilityParams)): ?>
<li class="<?=$this->active == 'fines' ? 'active' : ''?>">
  <a href="<?=$this->url('myresearch-fines')?>" class="flex">
    <?php
      // Use a "fines" icon based on the configured default currency symbol:
      $currencyIcon = 'currency-' . strtolower($this->config()->get('config')->Site->defaultCurrency ?? 'usd');
    ?>
    <span class="flex-col">
      <?=$this->icon($currencyIcon, 'icon-link__icon fa-fw') ?>
      <span class="icon-link__label"><?=$this->transEsc('Fines')?></span>
    </span>
  </a>
</li>
<?php endif; ?>
<li class="<?=$this->active == 'profile' ? 'active' : ''?>">
  <a href="<?=$this->url('myresearch-profile')?>" class="flex">
    <span class="flex-col">
      <?=$this->icon('profile', 'icon-link__icon fa-fw') ?>
      <span class="icon-link__label"><?=$this->transEsc('Profile')?></span>
    </span>
  </a>
</li>
<?php if ($ilsOnline && $user && $user->libraryCardsEnabled()): ?>
<li class="<?=$this->active == 'librarycards' ? 'active' : ''?>">
  <a href="<?=$this->url('librarycards-home')?>" class="flex">
    <span class="flex-col">
      <?=$this->icon('barcode', 'icon-link__icon fa-fw') ?>
      <span class="icon-link__label"><?=$this->transEsc('Library Cards')?></span>
    </span>
  </a>
</li>
<?php endif; ?>
<?php if ($this->overdrive()->showMyContentLink()):?>
<li class="<?=$this->active == 'dgcontent' ? 'active' : ''?>">
   <a href="<?=$this->url('overdrive-mycontent')?>" class="flex">
     <span class="flex-col">
      <?=$this->icon('overdrive', 'icon-link__icon fa-fw') ?>
      <span class="icon-link__label"><?=$this->transEsc('Overdrive Content')?></span>
     </span>
  </a>
</li>
<?php endif; ?>
<?php if ($this->accountCapabilities()->getSavedSearchSetting() === 'enabled'): ?>
<li class="<?=$this->active == 'history' ? 'active' : ''?>">
  <a href="<?=$this->url('search-history')?>?require_login" class="flex">
    <span class="flex-col">
      <?=$this->icon('search', 'icon-link__icon fa-fw') ?>
      <span class="icon-link__label"><?=$this->transEsc('history_saved_searches')?></span>
    </span>
  </a>
</li>
<?php endif; ?>
<li class="<?=$this->active == 'usersettings' ? 'active' : ''?>">
  <a href="<?=$this->url('myresearch-usersettings')?>?require_login" class="flex">
    <span class="flex-col">
      <?=$this->icon('user-settings', 'icon-link__icon fa-fw') ?>
      <span class="icon-link__label"><?=$this->transEsc('User settings')?></span>
    </span>
  </a>
</li>
<?php if ($user && $this->userlist()->getMode() !== 'disabled'): ?>
<li class="<?=$this->active == 'mylist' ? 'active' : ''?>">
  <a href="<?=$this->url('myresearch-favorites')?>" class="flex">
    <span class="flex-col">
      <?=$this->icon('user-favorites', 'icon-link__icon fa-fw') ?>
      <span class="icon-link__label"><?=$this->transEsc('Your Favorites')?></span>
    </span>
  </a>
</li>
<?php endif ?>
<?php if ($user): ?>
<li role="separator" class="divider"></li>
<li>
  <a href="<?=$this->url('myresearch-logout')?>" class="flex">
    <span class="flex-col">
      <?=$this->icon('sign-out', 'icon-link__icon fa-fw') ?>
      <span class="icon-link__label"><?=$this->transEsc("Log Out")?></span>
    </span>
  </a>
</li>
<?php endif; ?>
