<?php
$loginTarget = $this->loginTarget ?? $this->url('myresearch-userlogin');
$account = $this->auth()->getManager();
$accountLabel = $this->translate('Your Account');
$user = $account->getIdentity();
if ($user && $user->firstname && $user->lastname) {
  $accountLabel = $user->firstname . ' ' . $user->lastname;
}
?>
<nav class="banner navbar navbar-expand-sm">
  <div class="container">
    <a class="navbar-brand lang-<?=$this->layout()->userLang ?>" href="<?=$this->url('home')?>">
      <img class="knihovny-logo" src="<?=$this->render('layout/logoimagelink.phtml');?>" alt="<?= $this->translate('logo_alt') ?>">
    </a>
    <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#header-collapse" aria-label="<?=$this->transEscAttr('mobile_toggle_navigation_text')?>">
      <?=$this->icon('ui-menu') ?>
    </button>
    <?php if (!isset($this->layout()->renderingError)): ?>
      <div class="collapse navbar-collapse justify-content-end" id="header-collapse">

        <ul class="nav navbar-nav">

          <?php // inspirations: ?>
          <?php $this->slot('inspiration-link')->start(); ?>
          <li class="nav-item">
            <a class="nav-link" href="<?=$this->url('inspiration') ?>"><?=$this->icon('inspiration', 'fa-fw')?> <?=$this->transEsc('Inspiration') ?></a>
          </li>
          <?=$this->slot('inspiration-link')->end(); ?>

          <?php if ($this->feedback()->tabEnabled()): ?>
            <li class="nav-item">
              <a class="nav-link icon-link" id="feedbackLink" data-lightbox href="<?=$this->url('feedback-home') ?>">
                <?=$this->icon('feedback', 'icon-link__icon') ?>
                <span class="icon-link__label"><?=$this->transEsc('Feedback')?></span>
              </a>
            </li>
          <?php endif; ?>
          <?php $cart = $this->cart(); ?>
          <?php if ($cart->isActive()): ?>
            <li class="nav-item" id="cartSummary" aria-live="polite" aria-atomic="true">
              <a id="cartItems" class="nav-link icon-link position-relative" data-lightbox title="<?=$this->transEscAttr('View Book Bag')?>" href="<?=$this->url('cart-home')?>">
                <?=$this->icon('cart', 'icon-link__icon') ?>
                <?=$this->transEsc('Book Bag')?>
                <sup class="badge text-bg-info">
                  <small>
                    <span role="status"><strong><?=count($cart->getItems())?></strong> <span class="visually-hidden"><?=$this->transEsc('items')?></span></span>
                    <span class="full<?=!$cart->isFull() ? ' hidden' : '' ?>">(<?=$this->transEsc('bookbag_full') ?>)</span>
                  </small>
                </sup>
              </a>
            </li>
          <?php endif; ?>

          <?php if (isset($this->layout()->themeOptions) && count($this->layout()->themeOptions) > 1): ?>
              <?=$this->component('menu-button', [
                  'toggleLabel' => 'Theme',
                  'toggleAttrs' => [
                    'class' => 'nav-link dropdown-toggle',
                  ],
                  'wrapperClass' => 'nav-item theme-selector',
                  'wrapperTag' => 'li',
                  'iconName' => 'theme',
                  'menuItems' => array_map(
                      function ($item) {
                          $item['label'] = $item['desc'];
                          $item['url'] = $this->url()->addQueryParameters(['ui' => $item['name']]);

                          return $item;
                      },
                      $this->layout()->themeOptions
                  ),
              ]) ?>
          <?php endif; ?>

          <?php if (isset($this->layout()->allLangs) && count($this->layout()->allLangs) > 1): ?>
            <li class="nav-item dropdown language">
              <button type="button" class="nav-link dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false" aria-haspopup="true">
                <span class="fi flags flag-<?=$this->layout()->userLang ?>" role="img" aria-hidden="true"></span>
                <?=$this->displayLanguageOption($this->layout()->allLangs[$this->layout()->userLang]) ?>
              </button>
              <ul class="dropdown-menu">
                <?php foreach ($this->layout()->allLangs as $langCode => $langName): ?>
                  <?php if ($langCode !== $this->layout()->userLang): ?>
                    <li>
                      <a class="dropdown-item" href="<?=$this->url()->addQueryParameters(['lng' => $langCode]) ?>" rel="nofollow">
                        <span class="fi flags flag-<?=$langCode ?>" role="img" aria-hidden="true"></span>
                        <?=$this->displayLanguageOption($langName) ?>
                      </a>
                    </li>
                  <?php endif; ?>
                <?php endforeach; ?>
              </ul>
            </li>
          <?php endif; ?>

          <?php if (is_object($account) && $account->loginEnabled()): // hide login/logout if unavailable ?>
            <?php if ($account->getIdentity()): ?>
              <li id="account-home-nav" class="nav-item dropdown">
                <button type="button" class="nav-link dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false" aria-haspopup="true">
                  <span id="account-icon"><?=$this->icon('my-account') ?></span>
                  <?=$this->escapeHtml($accountLabel)?>
                </button>
                <?=$this->accountMenu()->render('', 'header_')?>
              </li>
            <?php endif; ?>
          <?php endif; ?>
        </ul>

        <?php // register/login button: ?>
        <?php if (!$account->getIdentity()): ?>
          <div class="navbar-form navbar-right" id="loginOptions">
            <?=$this->slot('registration-link')->set('');?>
            <?php if ($account->getSessionInitiator($this->serverUrl($this->url('myresearch-home')))): ?>
              <a href="<?=$loginTarget?>" class="btn btn-primary">
                <?=$this->icon('sign-in') ?>
                <?=$this->transEsc('Institutional Login')?>
              </a>
            <?php else: ?>
              <a href="<?=$this->url('myresearch-userlogin')?>" data-lightbox class="btn btn-primary">
                <?=$this->icon('sign-in') ?>
                <?=$this->transEsc('Login')?>
              </a>
            <?php endif; ?>
          </div>
        <?php endif ?>

        <div class="dropdown portal-selector">
          <button class="btn btn-outline-primary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false" title="<?=$this->transEscAttr('portal_selector_dropdown_title') ?>">
            <span class="ikcz-dots" role="img" aria-hidden="true"></span>
            <span class="sr-only"><?=$this->translate('portal_selector_dropdown_title') ?></span>
          </button>
          <ul class="dropdown-menu dropdown-menu-sm-end shadow" aria-labelledby="dropdownMenuButton">
            <li>
              <a class="dropdown-item portal-selector-knihovny" href="<?=$this->transEscAttr('portal_selector_knihovny_link')?>" target="_blank" rel="nofollow" title="<?=$this->transEscAttr('portal_selector_knihovny_title')?>">
                <img class="knihovny-logo" src="<?=$this->transEscAttr('portal_selector_knihovny_img')?>" alt="<?=$this->transEscAttr('portal_selector_knihovny_alt')?>">
              </a>
            </li>
            <li>
              <h6 class="dropdown-header fs-5 fw-bold p-2 bg-body-secondary"><?=$this->translate('portal_selector_subheading_catalogs') ?></h6>
            </li>
            <li class="border-bottom">
              <a class="dropdown-item portal-selector-mzk" href="<?=$this->transEscAttr('portal_selector_mzk_link')?>" target="_blank" rel="nofollow" title="<?=$this->transEscAttr('portal_selector_mzk_title')?>">
                <img class="knihovny-logo" src="<?=$this->transEscAttr('portal_selector_mzk_img')?>" alt="<?=$this->transEscAttr('portal_selector_mzk_alt')?>">
              </a>
            </li>
            <li>
              <a class="dropdown-item portal-selector-nkp" href="<?=$this->transEscAttr('portal_selector_nkp_link')?>" target="_blank" rel="nofollow" title="<?=$this->transEscAttr('portal_selector_nkp_title')?>">
                <img class="knihovny-logo" src="<?=$this->transEscAttr('portal_selector_nkp_img')?>" alt="<?=$this->transEscAttr('portal_selector_nkp_alt')?>">
              </a>
            </li>
            <li>
              <h6 class="dropdown-header fs-5 fw-bold p-2 bg-body-secondary"><?=$this->translate('portal_selector_subheading_other') ?></h6>
            </li>
            <li class="border-bottom">
              <a class="dropdown-item" href="<?=$this->transEscAttr('portal_selector_portals_link')?>" target="_blank" title="<?=$this->transEscAttr('portal_selector_portals_text')?>">
                <?=$this->translate('portal_selector_portals_text') ?>
              </a>
            </li>
            <li>
              <a class="dropdown-item" href="<?=$this->transEscAttr('portal_selector_microportals_link')?>" target="_blank" title="<?=$this->transEscAttr('portal_selector_microportals_text')?>">
                <?=$this->translate('portal_selector_microportals_text') ?>
              </a>
            </li>
          </ul>
        </div>

      </div>
    <?php endif; ?>
  </div>
</nav>
