<?php
  $account = $this->auth()->getManager();
  $accountLabel = $this->translate('Your Account');
  $user = $account->isLoggedIn();
  if ($user && $user->firstname && $user->lastname) {
    $accountLabel = $user->firstname . ' ' . $user->lastname;
  }
?>
<div class="banner container navbar">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#header-collapse" aria-label="<?=$this->transEscAttr('mobile_toggle_navigation_text')?>">
      <?=$this->icon('ui-menu', 'fa-fw') ?>
    </button>
    <a class="navbar-brand lang-<?=$this->layout()->userLang ?>" href="<?=$this->url('home') ?>">
      <img class="knihovny-logo" src="<?=$this->render('layout/logoimagelink.phtml');?>" alt="<?= $this->translate('logo_alt') ?>">
    </a>
  </div>
  <?php if (!isset($this->layout()->renderingError)): ?>
    <div class="collapse navbar-collapse" id="header-collapse">
      <nav>
        <ul class="nav navbar-nav navbar-right flip">
          <li>
            <a href="<?=$this->url('inspiration') ?>"><?=$this->icon('inspiration', 'fa-fw')?> <?=$this->transEsc('Inspiration') ?></a>
          </li>
          <?php if ($this->feedback()->tabEnabled()): ?>
            <li>
              <a class="icon-link" id="feedbackLink" data-lightbox href="<?=$this->url('feedback-home') ?>">
                <?=$this->icon('feedback', 'icon-link__icon') ?>
                <span class="icon-link__label"><?=$this->transEsc('Feedback')?></span>
              </a>
            </li>
          <?php endif; ?>
          <?php $cart = $this->cart(); ?>
          <?php if ($cart->isActive()): ?>
            <li id="cartSummary">
              <a id="cartItems" class="icon-link"  title="<?=$this->transEscAttr('View Book Bag')?>" href="<?=$this->url('cart-home')?>">
                <span role="status"><span class="sr-only"><?=$this->transEsc('Book Bag')?>:</span>
                  <sup class="badge badge-info">
                    <strong><?=count($cart->getItems())?></strong><span class="sr-only"> <?=$this->transEsc('items')?></span>
                  </sup>
                  <?=$this->icon('cart', 'icon-link__icon') ?>
                </span>
                <span class="icon-link__label"><?=$this->transEsc('Book Bag')?></span>
                <span class="full<?=!$cart->isFull() ? ' hidden' : '' ?>">(<?=$this->transEsc('bookbag_full') ?>)</span>
              </a>
            </li>
          <?php endif; ?>
          <?php if (is_object($account) && $account->loginEnabled()): // hide login/logout if unavailable ?>
            <?php if($account->isLoggedIn()): ?>
            <li class="dropdown">
              <a href="#" data-toggle="dropdown" class="icon-link">
                <span id="account-icon"><?=$this->icon('my-account', 'icon-link__icon') ?></span>
                <?=$this->escapeHtml($accountLabel)?><?=$this->icon('dropdown-caret') ?>
              </a>
              <ul class="dropdown-menu">
                <?=$this->render('accountmenu'); ?>
              </ul>
            </li>
            <?php endif ?>
            <?php if (!$account->isLoggedIn()): ?>
            <li id="loginOptions">
              <?php if ($account->getSessionInitiator($this->serverUrl($this->url('myresearch-home')))): ?>
                <a href="<?=$this->url('myresearch-userlogin')?>" class="icon-link">
                  <?=$this->icon('sign-in', 'icon-link__icon') ?>
                  <span class="icon-link__label"><?=$this->transEsc('Institutional Login')?></span>
                </a>
              <?php else: ?>
                <a href="<?=$this->url('myresearch-userlogin')?>" data-lightbox class="icon-link">
                  <?=$this->icon('sign-in', 'icon-link__icon') ?>
                  <span class="icon-link__label"><?=$this->transEsc('Login')?></span>
                </a>
              <?php endif; ?>
            </li>
	    <?php endif ?>

          <?php endif; ?>
          <?php if (isset($this->layout()->themeOptions) && count($this->layout()->themeOptions) > 1): ?>
              <?=$this->component('menu-button', [
                  'toggleLabel' => 'Theme',
                  'wrapperTag' => 'li',
                  'menuItems' => array_map(
                      function ($item) {
                          $item['label'] = $item['desc'];
                          $item['url'] = $this->url()->addQueryParameters(['ui' => $item['name']]);

                          return $item;
                      },
                      $this->layout()->themeOptions
                  ),
              ]) ?>
          <?php endif; ?>
          <?php if (isset($this->layout()->allLangs) && count($this->layout()->allLangs) > 1): ?>
              <?=$this->component('menu-button', [
                  'toggleLabel' => 'Language',
                  'wrapperClass' => 'language',
                  'wrapperTag' => 'li',
                  'iconName' => 'language-select',
                  'menuItems' => array_map(
                      function ($langCode, $langName) {
                          return [
                            'label' => $this->displayLanguageOption($langName),
                            'url' => $this->url()->addQueryParameters(['lng' => $langCode]),
                            'selected' => $this->layout()->userLang == $langCode,
                          ];
                      },
                      array_keys($this->layout()->allLangs),
                      array_values($this->layout()->allLangs),
                  ),
              ]) ?>
          <?php endif; ?>
        </ul>
      </nav>
    </div>
  <?php endif; ?>
</div>
