<?php

use Mzk\ZiskejApi\Enum\StatusName;

?>
<?=$this->flashmessages()?>

<?php
/** @var \KnihovnyCz\Db\Row\UserCard $userCard */
$userCard = $this->userCard;
$error = ($this->error ?? false);
?>
<?php if ($userCard && $userCard->eppn): ?>
  <?php if ($this->isZiskejModeEnabled): ?>
    <?php if ($this->isLibraryInZiskej): ?>
      <?php
      /** @var \Mzk\ZiskejApi\ResponseModel\Reader|null $reader */
      $reader = $this->reader;
      ?>
      <?php if ($reader): ?>
        <div class="well">
          <?=$this->icon('profile', 'fa-fw text-muted')?> <?=$reader->firstName?> <?=$reader->lastName?>
          <br>
          <?=$this->icon('profile-email', 'fa-fw text-muted')?> <?=$reader->email?>
        </div>
        <?php if (is_countable($this->tickets) && count($this->tickets)): ?>
          <?php
          $dateLimit = new DateTime('-14 days');
          $currentTickets = [];
          $archivedTickets = [];
          foreach ($this->tickets as $item) {
            /** @var \Mzk\ZiskejApi\ResponseModel\TicketEdd $ticket */
            $ticket = $item['ticket'];
            switch ($ticket->status) {
              case StatusName::CLOSED:
              case StatusName::CANCELLED:
                $archivedTickets[] = $item;
                break;
              case StatusName::REJECTED:
                if ($ticket->updatedAt >= $dateLimit) {
                  $currentTickets[] = $item;
                } else {
                  $archivedTickets[] = $item;
                }
                break;
              default:
                $currentTickets[] = $item;
                break;
            }
          }
          ?>
          <div class="card card-with-tabs">
            <div class="card-header bg-transparent">
              <ul class="nav nav-tabs card-header-tabs" role="tablist">
              <li role="presentation" class="nav-item">
                <a href="#current_<?=$userCard->card_name?>" class="nav-link active" aria-controls="current_<?=$userCard->card_name?>" role="tab" data-bs-toggle="tab">
                  <?=$this->transEsc('ZiskejEdd::tab_active')?>
                </a>
              </li>
              <li role="presentation" class="nav-item">
                <a href="#history_<?=$userCard->card_name?>" class="nav-link" aria-controls="history_<?=$userCard->card_name?>" role="tab" data-bs-toggle="tab">
                  <?=$this->transEsc('ZiskejEdd::tab_history')?>
                </a>
              </li>
            </ul>
            </div>
            <div class="card-body tab-content">
              <div role="tabpanel" class="tab-pane active" id="current_<?=$userCard->card_name?>">
                <?php if (count($currentTickets)): ?>
                  <?=$this->render('_ziskej-tickets-list.phtml', [
                    'ticketsData' => $currentTickets,
                    'userCard' => $userCard,
                  ])?>
                <?php else: ?>
                  <div class="alert alert-info">
                    <?=$this->transEsc('ZiskejEdd::message_no_current_orders')?>
                  </div>
                <?php endif; ?>
              </div>
              <div role="tabpanel" class="tab-pane" id="history_<?=$userCard->card_name?>">
                <?php if (count($archivedTickets)): ?>
                  <?=$this->render('_ziskej-tickets-list.phtml', [
                    'ticketsData' => $archivedTickets,
                    'userCard' => $userCard,
                  ])?>
                <?php else: ?>
                  <div class="alert alert-info">
                    <?=$this->transEsc('ZiskejEdd::message_no_history_orders')?>
                  </div>
                <?php endif; ?>
              </div>
            </div>
          </div>
        <?php elseif (!$error): ?>
          <div class="alert alert-info">
            <?=$this->transEsc('ZiskejEdd::info_no_items')?>
          </div>
        <?php endif; ?>
      <?php else: ?>
        <div class="alert alert-info">
          <?=$this->transEsc('ZiskejEdd::message_no_current_orders')?>
        </div>
      <?php endif; ?>
    <?php else: ?>
      <div class="alert alert-danger">
        <?=$this->transEsc('ZiskejEdd::library_not_found_in_ziskej')?>
      </div>
    <?php endif; ?>
  <?php else: ?>
    <div class="alert alert-danger">
      <?=$this->transEsc('ZiskejEdd::mode_disabled')?>
    </div>
  <?php endif; ?>
<?php else: ?>
  <div class="alert alert-danger">
    <?=$this->transEsc('ZiskejEdd::user_card_not_found')?>
  </div>
<?php endif; ?>
