<?php
  // Set up page title:
  $pageTitle = empty($this->card->id) ? 'Add a Library Card' : 'Edit Library Card';
  $this->headTitle($this->translate($pageTitle));

  // Set up breadcrumbs:
  $this->layout()->breadcrumbs = '<li><a href="' . $this->url('myresearch-home') . '">' . $this->transEsc('Your Account') . '</a></li>'
    . '<li><a href="' . $this->url('librarycards-home') . '">' . $this->transEsc('Library Cards') . '</a></li>'
    . '<li>' . $this->transEsc($pageTitle) . '</li>';
?>

<?=$this->flashmessages()?>

<h2><?=$this->transEsc($pageTitle); ?></h2>

<form class="form-edit-card" method="post" name="<?=empty($this->card->id) ? 'newCardForm' : 'editCardForm'?>" autocomplete="off" data-clear-account-cache>
  <input type="hidden" name="id" value="<?=empty($this->card->id) ? 'NEW' : $this->escapeHtmlAttr($this->card->id) ?>"/>
  <div class="form-group">
    <label class="control-label" for="card_name"><?=$this->transEsc('Library Card Name'); ?>:</label>
    <input id="card_name" class="form-control" type="text" name="card_name" value="<?=$this->escapeHtmlAttr($this->cardName)?>"/>
  </div>
  <div class="form-group">
    <input class="btn btn-primary" type="submit" name="submit" value="<?=$this->transEscAttr('Save') ?>"/>
  </div>
</form>

<?php
  if (null !== $targets) {
    $methods = json_encode($this->loginMethods);
    $script = "setupMultiILSLoginFields($methods, 'login_');";

    // Inline the script for lightbox compatibility
    echo $this->inlineScript(\Laminas\View\Helper\HeadScript::SCRIPT, $script, 'SET');
  }
?>
