<?php
    // Set up page title:
    $this->headTitle($this->translate('Library Cards'));

    // Set up breadcrumbs:
    $this->layout()->breadcrumbs = '<li><a href="' . $this->url('myresearch-home') . '">' . $this->transEsc('Your Account') . '</a></li> <li class="active">' . $this->transEsc('Library Cards') . '</li>';
    $delete = count($this->libraryCards) > 1;
?>
<div class="<?=$this->layoutClass('mainbody')?>">

  <?=$this->flashmessages()?>

  <h2><?=$this->transEsc('Library Cards')?></h2>
  <?php if ($this->libraryCards->count() == 0): ?>
    <div><?=$this->transEsc('You do not have any library cards')?></div>
  <?php else: ?>
    <table class="table table-striped">
      <caption class="sr-only"><?=$this->transEsc('Library Cards')?></caption>
    <tr>
      <th><?=$this->transEsc('Library Card Name')?></th>
      <th><?=$this->transEsc('Username')?></th>
      <th>&nbsp;</th>
    </tr>
    <?php foreach ($this->libraryCards as $record): ?>
      <tr>
        <td><?=$this->transEsc('Source::' . $record['card_name'])?></td>
        <?php $username = $record['cat_username']; if ($this->multipleTargets): ?>
          <?php $target = ''; ?>
          <?php if (strstr($username, '.')): ?>
            <?php [$target, $username] = explode('.', $username, 2); ?>
          <?php endif; ?>
        <?php endif; ?>
        <td><?=$this->escapeHtml($username)?></td>
        <td>
          <div class="btn-group">
            <?php if ($delete): ?>
              <a class="btn btn-link dropdown-toggle" data-toggle="dropdown" href="<?=$this->url('librarycards-deletecard') ?>?cardID=<?=urlencode($record['id'])?>">
                <i class="fa fa-trash-o" aria-hidden="true"></i> <?=$this->transEsc('Delete')?>
              </a>
            <?php endif; ?>
            <ul class="dropdown-menu">
              <li><a href="<?=$this->url('librarycards-deletecard') ?>?cardID=<?=urlencode($record['id'])?>&amp;confirm=1" data-clear-account-cache><?=$this->transEsc('confirm_dialog_yes') ?></a></li>
              <li><a href="#"><?=$this->transEsc('confirm_dialog_no')?></a></li>
            </ul>
          </div>
        </td>
      </tr>
    <?php endforeach; ?>
    </table>
  <?php endif; ?>

  <div class="btn-group">
    <?php if ($this->allowConnectingCards): ?>
      <a href="<?=$this->url('librarycards-connectcardlogin') ?>" class="btn btn-link"><i class="fa fa-edit" aria-hidden="true"></i> <?=$this->transEsc('Add a Library Card using login')?></a>
    <?php endif;?>
  </div>

</div>

<div class="<?=$this->layoutClass('sidebar')?>">
  <?=$this->context($this)->renderInContext("myresearch/menu.phtml", ['active' => 'librarycards'])?>
</div>

<div class="btn-group pull-right">
  <a class="btn btn-link dropdown-toggle" data-toggle="dropdown" href="<?=$this->url('myresearch-deleteuser') ?>">
    <i class="fa fa-trash-o" aria-hidden="true"></i> <?=$this->transEsc('delete_user_account')?>
  </a>
  <ul class="dropdown-menu">
    <pre><?=$this->translate('delete_user_account_confirm')?></pre>
    <li>
      <form action="<?=$this->url('myresearch-deleteuser') ?>" method="post">
        <input type='hidden' name='csrf' value="<?=$this->escapeHtml($this->csrfHash)?>"/>
        <input type='hidden' name='confirm' value='1'/>
        <button type='submit' class="btn btn-link"><?=$this->transEscAttr('confirm_dialog_yes') ?></button>
      </form>
    </li>
    <button type='submit' class="btn btn-link"><?=$this->transEscAttr('confirm_dialog_no') ?></button>
  </ul>
</div>
