<?php
    // Set up page title:
    $this->headTitle($this->translate('Library Cards'));

    // Set up breadcrumbs:
    $this->breadcrumbs()->set($this->translate('Your Account'), $this->url('myresearch-home'))->add($this->translate('Library Cards'), active: true);
    $delete = count($this->libraryCards) > 1;

    $loadJs = <<<JS
          function initLibraryCards() {
            $('.confirm_delete_library_card_yes').each(function onEach() {
              $(this).on('click', function onClick(e) {
                e.preventDefault();
                let form = $(this).parents('form');
                form.find('input[name="confirm"]').val(1);
                form.submit();
              });
            });
            $('.confirm_delete_library_card_no').on("click", function doNotDeleteCard(e) {
              e.preventDefault();
            });
          }
          initLibraryCards();
        JS;
?>
<div class="<?=$this->layoutClass('mainbody')?>">

  <?=$this->flashmessages()?>

  <div class="context-help">
    <h2 class="context-text"><?=$this->transEsc('Library Cards')?></h2>
    <?=$this->contextHelp('library-cards', 'heading')?>
  </div>
  <?php if (count($this->libraryCards) == 0): ?>
    <div><?=$this->transEsc('You do not have any library cards')?></div>
  <?php else: ?>
    <table class="table table-striped">
      <caption class="visually-hidden"><?=$this->transEsc('Library Cards')?></caption>
      <thead>
        <tr>
          <th style="width: 15%"></th>
          <th><?=$this->transEsc('Library Card Name')?></th>
          <th style="width: 30%"></th>
        </tr>
      </thead>
    <?php $records = $this->userCards($this->libraryCards)->getSortedByLibraryName(); ?>
    <?php foreach ($records as $record): ?>
      <tr>
        <td>
          <?php
          $institution = $record->home_library;
          $imageLink = sprintf('institutions/logos/%s/%s_small.png', $institution, $institution);
          ?>
          <img height="30" src="<?=$this->imageLink($imageLink)?>" alt="<?=$this->transEsc('Source::' . $institution) ?>">
        </td>
        <td>
          <?=$this->transEsc('Source::' . $record->getCardName())?>
        </td>
        <td>
          <div class="btn-group">
            <?php if ($delete): ?>
              <div class="btn-group">
                <form method="post" action="<?=$this->url('librarycards-deletecard') ?>">
                  <input type="hidden" name="cardID" value="<?=$this->escapeHtmlAttr($record->getId())?>"/>
                  <input type='hidden' name='csrf' value="<?=$this->escapeHtml($this->csrfHash)?>">
                  <input type="hidden" name="confirm" value="0"/>
                  <?=
                    $this->component(
                        'confirm-button',
                        [
                        'buttonId' => 'delete_card_' . $record->getId(),
                        'buttonName' => 'deleteCard',
                        'buttonIcon' => 'profile-card-delete',
                        'buttonLabel' => 'Disconnect identity',
                        'buttonClass' => 'btn btn-primary',
                        'header' => 'confirm_delete_library_card_brief',
                        'confirmId' => 'confirm_delete_library_card_yes' . $record->getId(),
                        'confirmClass' => 'confirm_delete_library_card_yes',
                        'cancelClass' => 'confirm_delete_library_card_no',
                        'clearAccountCache' => true,
                        'ignoreLightbox' => true,
                      ]
                    )
                  ?>
                </form>
              </div>
            <?php endif; ?>
          </div>
        </td>
      </tr>
    <?php endforeach; ?>
    </table>
  <?php endif; ?>

  <?php if ($this->allowConnectingCards): ?>
    <h2><?=$this->translate('Library card connect warning label')?></h2>
    <p class="alert alert-danger" role="alert"><?=$this->translate('Library card connect warning 1')?></p>
    <p><?=$this->translate('Library card connect warning 2')?></p>
    <p><?=$this->translate('Library card connect warning 3')?></p>
    <div class="btn-group">
      <a href="<?=$this->url('librarycards-connectcardlogin') ?>" id="connectCardInitializeBtn" class="add-card-login btn btn-primary" role="button" aria-pressed="true">
        <?=$this->icon('ui-add', 'icon-link__icon') ?>
        <span class="icon-link__label"><?=$this->transEsc('Add a Library Card using login')?></span>
      </a>
    </div>
  <?php endif;?>

  <hr>

  <div>
    <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#deleteUserAccountModal">
      <?=$this->icon('ui-delete') ?> <?=$this->transEsc('delete_user_account')?>
    </button>
  </div>

</div>

<div class="modal fade" id="deleteUserAccountModal" tabindex="-1" aria-labelledby="deleteUserAccountModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <h2 class="modal-title fs-2" id="deleteUserAccountModalLabel"><?=$this->transEsc('delete_user_account')?></h2>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <div class="alert alert-warning"><?=$this->translate('delete_user_account_confirm')?></div>
        <form action="<?=$this->url('myresearch-deleteuser') ?>" method="post">
          <input type='hidden' name='csrf' value="<?=$this->escapeHtml($this->csrfHash)?>">
          <input type='hidden' name='confirm' value='1'>
          <button type='submit' class="btn btn-primary"><?=$this->transEscAttr('confirm_dialog_yes') ?></button>
          <button type="button" class="btn btn-link" data-bs-dismiss="modal"><?=$this->transEscAttr('confirm_dialog_no') ?></button>
        </form>
      </div>
    </div>
  </div>
</div>

<div class="<?=$this->layoutClass('sidebar')?>" id="myresearch-sidebar" role="navigation" aria-label="<?=$this->transEsc('account_menu_label')?>">
  <?=$this->accountMenu()->render('librarycards')?>
</div>

<?=$this->assetManager()->outputInlineScriptString($loadJs)?>
<noscript><?=$this->transEsc('Please enable JavaScript.')?></noscript>
