<?php
    $loadJs = <<<JS
          function loadMyAccount() {
            $('.library-card-ajax').each(function onEachLibraryCard() {
              hideLibraryCardContent(this, false);
              const link = $(this).data('action') + "?cardId=" + $(this).data('card-id');
              reloadLibraryCardContent(this, link);
          })}
          loadMyAccount();

          function reloadLibraryCardContent(element, link) {
            const callback = $(element).data('callback');
            const ajaxCall = {
              dataType: "html",
              url: link,
              method: "GET",
              success: function show(content) {
                showLibraryCardContent(element, content, function onComplete() {
                  if (callback != '') {
                    window[callback](element);
                  }
                });
              }
            };
            $.ajax(ajaxCall);
          }

          function showLibraryCardContent(element, content, callback) {
            $(element).hide(500, function onComplete() {
              $(element).parent('.panel-body').find('.loading-overlay').fadeOut(200);
              $(element).html(content).slideDown(500, function onComplete(){
                if (window.location.hash != null) {
                  const fragment = window.location.hash.substring(1);
                  if ($(element).data('card-id') == fragment || $(element).data('card-name') == fragment) {
                    scrollIntoView(element);
                  }
                }
              });
              if (callback != null) {
                callback();
              }
            });
          }

          function hideLibraryCardContent(element, scroll = false) {
            $(element).hide(500, function onComplete() {
              $(element).html(VuFind.spinner()).show(0);
              if (scroll) {
                scrollIntoView(element);
              }
            });
          }

          function scrollIntoView(element) {
            $(element).closest('.panel').get(0).scrollIntoView();
          }

        JS;

?>
<?php if ($this->user != null): ?>
  <?php
    $cards = $this->userCards($this->user->getLibraryCardsWithILS())->getSortedByLibraryName();
    $singleCard = $this->user->isSingleCard() && count($cards) == 1;
    $libraryCardEnabled = !($this->user->isSingleCard() || $this->user->hasLibraryCardsFilter());
    $i = 1;
  ?>
  <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
    <?php foreach ($cards as $card): ?>
      <div class="panel panel-default">
        <?php if (!$singleCard): ?>
          <?php
            $institution = $card->home_library;
            $imageLink = sprintf('institutions/logos/%s/%s_small.png', $institution, $institution);
          ?>
          <div class="panel-heading panel-heading-with-img bg-white clearfix pointer" role="tab" data-toggle="collapse" data-target="#card_<?=$i?>">
            <h3 class="panel-title pull-left">
              <?=$this->transEsc('Source::' . $institution) ?>
            </h3>
            <img class="pull-right" height="30" src="<?=$this->imageLink($imageLink)?>" alt="<?=$this->transEsc('Source::' . $institution) ?>">
          </div>
        <?php endif;?>

        <div id="card_<?=$i ?>" class="panel-collapse collapse in" role="tabpanel">
          <div class="panel-body">
            <div class="loading-overlay"></div>
            <div class='library-card-ajax' data-card-id='<?=$card->id?>' data-card-name="<?=$card->card_name?>" data-action='<?=$action?>' data-callback='<?=$this->callback?>'>
            </div>
          </div>
        </div>

      </div>
    <?php $i++ ?>
    <?php endforeach; ?>
  </div>
  <?php if ($this->user->isSocial()): ?>
    <?php if ($libraryCardEnabled): ?>
      <p class="alert alert-warning" role="alert">
        <?=$this->translate('notif_you_have_user_dummy', ['%%url%%' => $this->url('librarycards-home')])?>
      </p>
      <div class="btn-group">
        <a href="<?=$this->url('librarycards-home') ?>" class="btn btn-primary" role="button" aria-pressed="true">
          <?=$this->transEsc('Library Cards')?>
        </a>
      </div>
    <?php else: ?>
      <p class="alert alert-warning" role="alert">
        <?=$this->translate('notif_you_have_user_dummy_no_library_cards')?>
      </p>
    <?php endif; ?>
  <?php endif; ?>
<?php endif; ?>

<?=$this->inlineScript(\Laminas\View\Helper\HeadScript::SCRIPT, $loadJs, 'SET')?>
<noscript><?=$this->transEsc('Please enable JavaScript.')?></noscript>
