<?php
    $loadJs = <<<JS
          function loadMyAccount() {
            $('.library-card-ajax').each(function onEachLibraryCard() {
              hideLibraryCardContent(this, false);
              const link = $(this).data('action') + "?cardId=" + $(this).data('card-id');
              reloadLibraryCardContent(this, link);
          })}
          loadMyAccount();

          function reloadLibraryCardContent(element, link) {
            const callback = $(element).data('callback');
            const ajaxCall = {
              dataType: "html",
              url: link,
              method: "GET",
              success: function show(content) {
                showLibraryCardContent(element, content, function onComplete() {
                  if (callback != '') {
                    window[callback](element);
                  }
                });
              }
            };
            $.ajax(ajaxCall);
          }

          function showLibraryCardContent(element, content, callback) {
            $(element).hide(500, function onComplete() {
              $(element).parents('.card-body').find('.loading-overlay').first().fadeOut(200);
              $(element).html(content).slideDown(500, function onComplete(){
                if (window.location.hash != null) {
                  const fragment = window.location.hash.substring(1);
                  if ($(element).data('card-id') == fragment || $(element).data('card-name') == fragment) {
                    $(element).closest('.card').get(0).scrollIntoView();
                  }
                }
              });
              if (callback != null) {
                callback();
              }
            });
          }

          function hideLibraryCardContent(element, scroll = false) {
            $(element).hide(500, function onComplete() {
              $(element).html(VuFind.spinner()).show(0);
              if (scroll) {
                scrollIntoView(element);
              }
            });
          }

          function scrollIntoView(element) {
            $(element).closest('.card').get(0).scrollIntoView();
          }

        JS;

?>
<?php if ($this->user != null): ?>
  <?php
    $cards = $this->userCards($this->user->getLibraryCardsWithILS())->getSortedByLibraryName();
    $singleCard = $this->user->isSingleCard() && count($cards) == 1;
    $libraryCardEnabled = !($this->user->isSingleCard() || $this->user->hasLibraryCardsFilter());
    $i = 1;
  ?>
  <div id="accordion" role="tablist" aria-multiselectable="true">
    <?php foreach ($cards as $card): ?>
      <div class="card">
        <?php if (!$singleCard): ?>
          <?php
            $institution = $card->home_library;
            $imageLink = sprintf('institutions/logos/%s/%s_small.png', $institution, $institution);
          ?>
          <div class="card-header d-flex justify-content-between align-items-center pointer" role="tab" data-bs-toggle="collapse" data-bs-target="#card_<?=$i?>" aria-expanded="true">
            <h4 class="card-title m-0"><?=$this->transEsc('Source::' . $institution) ?></h4>
            <img height="30" src="<?=$this->imageLink($imageLink)?>" alt="<?=$this->transEsc('Source::' . $institution) ?>">
          </div>
        <?php endif;?>

        <div id="card_<?=$i ?>" class="collapse multi-collapse show" role="tabpanel">
          <div class="card-body position-relative">
            <div class="loading-overlay"></div>
            <?php if (isset($this->tabNames) &&
              is_array($this->tabNames) &&
              is_array($this->callback) &&
              is_array($this->action) &&
              in_array($card->getId(), $this->useTabsForCardIds)): ?>
            <?php $firstTabId = array_key_first($this->tabNames);?>
            <div class="card card-with-tabs">
              <div class="card-header bg-transparent">
                <ul class="nav nav-tabs card-header-tabs" role="tablist">
                <?php foreach ($this->tabNames as $tabId => $tabName): ?>
                  <li role="presentation" class="nav-item">
                    <a href="#<?=$card->id . $tabId?>" class="nav-link<?=$tabId === $firstTabId ? ' active' : '';?>" aria-controls="<?=$card->id . $tabId?>" role="tab" data-bs-toggle="tab">
                      <?=$tabName?>
                    </a>
                  </li>
                <?php endforeach; ?>
                </ul>
              </div>
              <div class="card-body tab-content">
                <?php foreach ($this->tabNames as $tabId => $tabName): ?>
                <div role="tabpanel" class="tab-pane<?=$tabId === $firstTabId ? ' active' : '';?>" id="<?=$card->id . $tabId?>">
                  <div class='library-card-ajax' data-card-id='<?=$card->id?>' data-card-name="<?=$card->card_name?>" data-action='<?=$this->action[$tabId]?>' data-callback='<?=$this->callback[$tabId]?>'>
                  </div>
                </div>
                <?php endforeach; ?>
              </div>
            </div>
            <?php else: ?>
              <?php $action = is_array($this->action) ? $this->action[array_key_first($this->action)] : $this->action; ?>
              <?php $callback = is_array($this->callback) ? $this->callback[array_key_first($this->callback)] : $this->callback; ?>
              <div class='library-card-ajax' data-card-id='<?=$card->id?>' data-card-name="<?=$card->card_name?>" data-action='<?=$action?>' data-callback='<?=$callback?>'>
              </div>
            <?php endif ?>
          </div>
        </div>

      </div>
    <?php $i++ ?>
    <?php endforeach; ?>
  </div>
  <?php if ($this->user->isSocial()): ?>
    <?php if ($libraryCardEnabled): ?>
      <p class="alert alert-warning" role="alert">
        <?=$this->translate('notif_you_have_user_dummy', ['%%url%%' => $this->url('librarycards-home')])?>
      </p>
      <div class="btn-group">
        <a href="<?=$this->url('librarycards-home') ?>" class="btn btn-primary" role="button" aria-pressed="true">
          <?=$this->transEsc('Library Cards')?>
        </a>
      </div>
    <?php else: ?>
      <p class="alert alert-warning" role="alert">
        <?=$this->translate('notif_you_have_user_dummy_no_library_cards')?>
      </p>
    <?php endif; ?>
  <?php endif; ?>
<?php endif; ?>

<?=$this->assetManager()->outputInlineScriptString($loadJs)?>
<noscript><?=$this->transEsc('Please enable JavaScript.')?></noscript>
