<?php
    $loadJs = <<<JS
  function loadMyAccount() {
    $('.library-card-ajax').each(function onEachLibraryCard() {
      var element = this;
      hideLibraryCardContent(element);
      var callback = $(element).data('callback');
      var ajaxCall = {
        dataType: "html",
        url: $(element).data('action') + "?cardId=" + $(element).data('card-id'),
        method: "GET",
        success: function show(content) {
          showLibraryCardContent(element, content, function onComplete() {
            if (callback != '') {
              window[callback](element);
            }
          });
        }
      };
      $.ajax(ajaxCall);
  })}
  loadMyAccount();

  function showLibraryCardContent(element, content, callback) {
    $(element).hide(500, function onComplete() {
      $(element).html(content).show(500);
      if (callback != null) {
        callback();
      }
    });
  }

  function hideLibraryCardContent(element) {
    $(element).hide(500, function onComplete() {
      $(element).html(VuFind.spinner()).show(0);
    });
  }

JS;

?>
<?php if ($this->user): ?>
  <?php foreach ($this->user->getLibraryCards() as $card): ?>
    <?php
    $institution = $card->home_library;
    $imageLink = sprintf('institutions/logos/%s/%s_small.png', $institution, $institution);
    ?>
    <div class="well row blickable clearfix">
      <h3 class="pull-left"><?=$this->transEsc('Source::' . $institution) ?></h3>
      <img class="pull-right" height="32" src="<?=$this->imageLink($imageLink)?>" alt="<?=$this->transEsc("Source::" . $institution) ?>">
    </div>
    <span class='library-card-ajax' data-card-id='<?=$card->id?>'
          data-action='<?=$action?>' data-callback='<?=$this->callback?>'>
    </span>
  <?php endforeach; ?>
<?php endif; ?>

<?=$this->inlineScript(\Laminas\View\Helper\HeadScript::SCRIPT, $loadJs, 'SET')?>
<noscript><?=$this->transEsc('Please enable JavaScript.')?></noscript>
