<div class="media" vocab="http://schema.org/" resource="#record" typeof="<?=$this->driver->getSchemaOrgFormats()?> Product">
<div class="row">
    <div class="col-md-6 library-detail">
        <!-- Library name -->
        <h1 property="name" class="record-title"><?=$this->escapeHtml($this->driver->getTitle())?></h1>
        <?php /* Display Main Details */ ?>
        <?php
            $formatter = $this->recordDataFormatter();
            $coreFields = $formatter->getData($driver, $formatter->getDefaults('library'));
        ?>
        <?php if (!empty($coreFields)): ?>
            <table class="table table-striped">
                <caption class="sr-only"><?=$this->transEsc('Library Details')?></caption>
                <?php foreach ($coreFields as $current): ?>
                  <?php if($current['context']['heading']):?>
                    <h2><i class="<?=$current['context']['icon']?>"></i> <?=$this->transEsc($current['label'])?></h2>
                    <p>
                  <?php else: ?>
                    <h2 class="hidden"><?=$this->transEsc($current['label'])?></h2>
                    <p class="<?=$current['context']['content-class']?>"><i class="<?=$current['context']['icon']?>"></i>
                  <?php endif; ?>
                  <?=$current['value']?></p>
                <?php endforeach; ?>
            </table>
        <?php endif; ?>
        <?php /* End Main Details */ ?>
    </div>

    <div class="col-md-6">
        <?php $coords = $this->driver->tryMethod('getGpsCoordinates'); if (!empty($coords)): ?>
            <div id="map"></div>
            <?php
              $apiKey = $this->config()->get('config')->GoogleMaps->apikey;
              $lat = $coords['lat'];
              $lng = $coords['lng'];
              $initMap = <<<JS
                function initMap() {
                  var myLatLng = {lat: 49.78, lng: 15.39};
                  var map = new google.maps.Map(document.getElementById('map'), {
                    zoom: 7,
                    center: myLatLng
                  });
                  var position = { lat: $lat, lng: $lng };
                  var marker = new google.maps.Marker({
                    position: position,
                    map: map,
                    title: 'name of library'
                  });
                }
JS;
            $googleMapsScript = "https://maps.googleapis.com/maps/api/js?key=" . $this->escapeUrl($apiKey) . "&callback=initMap";
            $this->inlineScript(\Laminas\View\Helper\HeadScript::SCRIPT, $initMap, 'SET');
            echo $this->inlineScript()->appendFile($googleMapsScript);
          ?>
        <?php endif; ?>
    </div>
</div>
