<?php if (!empty($data)): ?>
    <table class="table">
        <?php if (!empty($data['mo'])): ?>
            <tr>
                <th><?=$this->transEsc('Monday')?></th>
                <td>
                    <?=$this->escapeHtml($data['mo'])?>
                </td>
            </tr>
        <?php endif; ?>
        <?php if (!empty($data['tu'])): ?>
            <tr>
                <th><?=$this->transEsc('Tuesday')?></th>
                <td>
                    <?=$this->escapeHtml($data['tu'])?>
                </td>
            </tr>
        <?php endif; ?>
        <?php if (!empty($data['we'])): ?>
            <tr>
                <th><?=$this->transEsc('Wednesday')?></th>
                <td>
                    <?=$this->escapeHtml($data['we'])?>
                </td>
            </tr>
        <?php endif; ?>
        <?php if (!empty($data['th'])): ?>
            <tr>
                <th><?=$this->transEsc('Thursday')?></th>
                <td>
                    <?=$this->escapeHtml($data['th'])?>
                </td>
            </tr>
        <?php endif; ?>
        <?php if (!empty($data['fr'])): ?>
            <tr>
                <th><?=$this->transEsc('Friday')?></th>
                <td>
                    <?=$this->escapeHtml($data['fr'])?>
                </td>
            </tr>
        <?php endif; ?>
        <?php if (!empty($data['sa'])): ?>
            <tr>
                <th><?=$this->transEsc('Saturday')?></th>
                <td>
                    <?=$this->escapeHtml($data['sa'])?>
                </td>
            </tr>
        <?php endif; ?>
        <?php if (!empty($data['su'])): ?>
            <tr>
                <th><?=$this->transEsc('Sunday')?></th>
                <td>
                    <?=$this->escapeHtml($data['su'])?>
                </td>
            </tr>
        <?php endif; ?>
        <?php if (!empty($data['for'])): ?>
            <tr>
                <th><?=$this->transEsc('Next')?></th>
                <td>
                    <?=$this->escapeHtml($data['for'])?>
                </td>
            </tr>
        <?php endif; ?>
    </table>
<?php endif;
