<?php
if (!empty($data)):
    $filter = urlencode('~local_region_institution_facet_str_mv:"'. $data . '"'); ?>
    <a href='/Search/Results?lookFor[]=&type[]=AllFields&keepEnabledFilters=true&limit=<?=$this->layout()->limit?>&sort=<?=$this->layout()->sort?>&filter[]=<?=$filter?>' title='<?=$this->translate('Search in library')?>' >
        <?=$this->transEsc('Search in library')?>
    </a>
<?php endif;

