<?php $this->metadata()->generateMetatags($this->driver);?>
<div class="media" vocab="http://schema.org/" resource="#record" typeof="<?=$this->driver->getSchemaOrgFormats()?> Product">
  <?php
  $QRCode = $this->record($this->driver)->getQRCode('core');
  $coverDetails = $this->record($this->driver)->getCoverDetails('core', 'medium', $this->record($this->driver)->getThumbnail('large'));
  $cover = $coverDetails['html'];
  $preview = ($this->previewOverride ?? false)
    ? $this->previewOverride : $this->record($this->driver)->getPreviews();
  ?>
  <?php if ($QRCode || $cover || $preview): ?>
    <div class="media-left <?=$this->escapeHtmlAttr($coverDetails['size'])?> img-col">
      <?php /* Display thumbnail if appropriate: */ ?>
      <?php if($cover): ?>
        <?=$cover?>
      <?php endif; ?>

      <?php /* Display qrcode if appropriate: */ ?>
      <?php if($QRCode): ?>
        <span class="hidden-xs">
          <br><img alt="<?=$this->transEscAttr('QR Code')?>" class="qrcode" src="<?=$this->escapeHtmlAttr($QRCode);?>">
        </span>
      <?php endif; ?>

      <?php // if you have a preview tab but want to move or remove the preview link
      // from this area of the record view, this can be split into
      // getPreviewData() (should stay here) and
      // getPreviewLink() (can go in your desired tab) ?>
      <?php if ($preview): ?>
        <div class="record-previews">
          <?=$preview?>
        </div>
      <?php endif; ?>
    </div>
  <?php endif; ?>
  <div class="media-body">

    <h1 property="name"><?=$this->escapeHtml($this->driver->getShortTitle())?></h1>

    <?php if(!empty($this->extraControls)): ?>
      <?=$this->extraControls['actionControls'] ?? ''?>
      <?=$this->extraControls['availabilityInfo'] ?? ''?>
    <?php endif; ?>

    <?php if ($this->searchOptions($this->driver->getSourceIdentifier())->getVersionsAction()): ?>
      <?=$this->record($this->driver)->renderTemplate('versions-link.phtml')?>
    <?php endif; ?>

    <?php $summary = $this->driver->getSummary();
    $summary = isset($summary[0]) ? $this->escapeHtml($summary[0]) : false; ?>
    <?php if ($summary): ?>
      <p><?=$this->truncate($summary, 300)?></p>

      <?php if(strlen($summary) > 300): ?>
        <p><a href='<?=$this->recordLinker()->getTabUrl($this->driver, 'Description')?>#tabnav'><?=$this->transEsc('Full description')?></a></p>
      <?php endif; ?>
    <?php endif; ?>

    <?php if ($this->userlist()->getMode() !== 'disabled'): ?>
      <?php /* Display the lists that this record is saved to */ ?>
      <div class="savedLists">
        <strong><?=$this->transEsc('Saved in')?>:</strong>
      </div>
    <?php endif; ?>

    <?php /* Display Main Details */ ?>
    <?php
    $formatter = $this->recordDataFormatter();
    $coreFields = $formatter->getData($this->driver, $formatter->getDefaults('ziskej'));
    ?>
    <?php if (!empty($coreFields)): ?>
      <h4 class="sr-only"><?=$this->transEsc('Bibliographic Details')?></h4>
      <dl class="dl-horizontal">
        <?php foreach ($coreFields as $current): ?>
          <dt><?=$this->transEsc($current['label'])?>:</dt>
          <dd><?=$current['value']?></dd>
        <?php endforeach; ?>
      </dl>
    <?php endif; ?>
    <?php /* End Main Details */ ?>
  </div>
</div>
