<ul class="media-list">
  <?php

  use Mzk\ZiskejApi\Enum\StatusName;

  $itemIndex = 1;
  foreach ($ticketsData as $item):
    /** @var \Mzk\ZiskejApi\ResponseModel\TicketMvs $ticket */
    $ticket = $item['ticket'];
    /** @var ?\KnihovnyCz\RecordDriver\SolrLocal $record */
    $record = $item['record'];
    ?>
    <li class="media well" id="record_<?=$ticket->hid?>" data-ziskej="<?=$ticket->hid?>">
      <strong class="pull-left order"><?= $itemIndex++ ?>.</strong>
      <?php
      $thumbnail = false;
      if ($record) {
        $coverDetails = $this->record($record)->getCoverDetails('checkedout', 'small', $this->recordLinker()->getUrl($record));
        $cover = $coverDetails['html'];
        if ($cover) {
          ob_start();
          echo $cover;
          $thumbnail = ob_get_contents();
          ob_end_clean();
        }
      }
      ?>
      <?php if ($thumbnail): ?>
        <div class="media-left small">
          <?=$thumbnail?>
        </div>
      <?php endif ?>
      <div class="media-body">
        <h4 class="media-heading">
          <?php if ($record): ?>
            <?php
            $title = !empty($record->getTitle())
              ? $this->escapeHtml($record->getTitle())
              : $this->transEsc('Title not available');
            ?>
            <a href="<?=$this->recordLinker()->getUrl($record)?>" class="title"><?=$title?></a>
          <?php else: ?>
            <?=$this->transEsc('record_info_not_available')?>
          <?php endif; ?>
        </h4>
        <div>
          <dl class="dl-horizontal dl-left">
            <?php if ($record): ?>
              <?php $listAuthor = $record->getPrimaryAuthor() ?>
              <?php if (!empty($listAuthor)): ?>
                <dt><?=$this->transEsc('by')?>:</dt>
                <dd>
                  <a href="<?=$this->record($record)->getLink('author', $listAuthor)?>">
                    <?=$this->escapeHtml($listAuthor)?>
                  </a>
                </dd>
              <?php endif; ?>
              <?php if (is_countable($record->getFormats()) && count($record->getFormats()) > 0): ?>
                <dt><?=$this->transEsc('ZiskejMvs::label_document_type')?>:</dt>
                <dd><?=$this->record($record)->getFormatList()?></dd>
              <?php endif; ?>
            <?php endif; ?>
            <?php if ($ticket->createdAt): ?>
              <dt><?=$this->transEsc('ZiskejMvs::label_date_order')?>:</dt>
              <dd><?=$this->dateTime()->convertToDisplayDate('U', $ticket->createdAt->getTimestamp())?></dd>
            <?php endif; ?>
            <?php if ($ticket->requestedAt): ?>
              <dt><?=$this->transEsc('ZiskejMvs::label_date_deliver')?>:</dt>
              <dd><?=$this->dateTime()->convertToDisplayDate('U', $ticket->requestedAt->getTimestamp())?></dd>
            <?php endif; ?>
            <?php if ($ticket->returnAt): ?>
              <dt><?=$this->transEsc('ZiskejMvs::label_date_return')?>:</dt>
              <dd><?=$this->dateTime()->convertToDisplayDate('U', $ticket->returnAt->getTimestamp())?></dd>
            <?php endif; ?>
            <dt><?=$this->transEsc('ZiskejMvs::label_order_number')?>:</dt>
            <dd><?=$ticket->hid?></dd>

            <?php if ($ticket->status): ?>
              <dt><?=$this->transEsc('ZiskejMvs::label_order_status')?>:</dt>
              <dd>
                <span class="label label-<?=$this->ziskejMvs()->getStatusClass($ticket->status)?>">
                  <?=$this->transEsc('ZiskejMvs::order_status_' . $ticket->status->value)?>
                </span>
              </dd>
            <?php endif; ?>
          </dl>
          <div class="text-right">
            <?php if ($ticket->status == StatusName::CREATED && !empty($ticket->paymentUrl)): ?>
              <a class="btn btn-sm btn-warning" href="<?=$ticket->paymentUrl->getAbsoluteUrl()?>" target="_blank" title="<?=$this->transEsc("ZiskejMvs::btn_order_pay_title")?>">
                <?=$this->icon('ziskej-order')?> <?=$this->transEsc("ZiskejMvs::btn_order_pay")?>
              </a>
            <?php endif; ?>
            <a class="btn btn-sm btn-primary" href="<?=$this->url('myresearch-ziskej-mvs-ticket', ['eppnDomain' => $userCard->getEppnDomain(), 'ticketId' => $ticket->id])?>" title="<?=$this->transEsc("ZiskejMvs::btn_order_detail_title")?>">
              <?=$this->icon('ziskej-order-detail')?> <?=$this->transEsc("ZiskejMvs::btn_order_detail")?>
            </a>
          </div>
        </div>
      </div>
    </li>
  <?php endforeach; ?>
</ul>
