<?php
// Set up page title:
$this->headTitle($this->translate('ZiskejMvs::checked_out_items'));

// Set up breadcrumbs:
$this->layout()->breadcrumbs = '<li><a href="' . $this->url('myresearch-home') . '">' . $this->transEsc('Your Account') . '</a></li> <li class="active">' . $this->transEsc('ZiskejMvs::checked_out_items') . '</li>';

$loadJs = <<<JS
      function loadZiskej(element) {
        loadCovers();
      };
    JS;
?>

<a class="search-filter-toggle visible-xs" href="#myresearch-sidebar" data-toggle="offcanvas" title="Expand Sidebar">
  <?=$this->transEsc('Your Account') ?>
</a>

<div class="<?=$this->layoutClass('mainbody')?>">
  <?php $this->slot('ziskej-mvs-title')->start(); ?>
  <div class="context-help">
    <h2 class="context-text"><?=$this->transEsc('ZiskejMvs::checked_out_items')?></h2>
    <?=$this->contextHelp('ziskej_mvs', 'heading')?>
  </div>
  <?=$this->slot('ziskej-mvs-title')->end(); ?>
  <?=$this->flashmessages();?>
  <p>
    <?=$this->context($this)->renderInContext('librarycards/listcards.phtml', [
      'user' => $this->auth()->getUserObject(),
      'action' => $this->url('myresearchziskejmvs-listajax'),
      'callback' => 'loadZiskej',
    ]);
    ?>
  </p>
</div>

<div class="<?=$this->layoutClass('sidebar')?>" id="myresearch-sidebar">
  <?=$this->accountMenu()->render('ziskej')?>
</div>

<?=$this->inlineScript(\Laminas\View\Helper\HeadScript::SCRIPT, $loadJs, 'SET')?>
<noscript><?=$this->transEsc('Please enable JavaScript.')?></noscript>

