<?php
$this->layout()->searchbox = false;

/** @var \VuFind\Db\Row\UserCard $userCard */
$userCard = $this->userCard;

/** @var \Mzk\ZiskejApi\ResponseModel\Ticket $ticket */
$ticket = $this->ticket;

/** @var \Mzk\ZiskejApi\ResponseModel\MessageCollection $messages */
$messages = $this->messages;

/** @var \KnihovnyCz\View\Helper\KnihovnyCz\ZiskejMvs $viewHelperZiskej */
$viewHelperZiskej = $this->ziskejMvs();
?>
<?php
// Set up page title:
$this->headTitle($this->translate('ZiskejMvs::header_order_ziskej_num') . ' ' . $ticket->getHid());
?>

<div class="row">
  <div class="<?=$this->layoutClass('mainbody') ?>">

    <div class="clearfix">

      <h2 class="pull-left">
        <?=$this->transEsc('ZiskejMvs::header_order_ziskej_num') . ' ' . $ticket->getHid() ?>
      </h2>

      <div class="pull-left h2-label">
        <span class="label label-<?=$viewHelperZiskej->getStatusClass($ticket->getStatus()) ?>">
          <?=$this->translate('ZiskejMvs::order_status_' . $ticket->getStatus()) ?>
        </span>
      </div>

    </div>

    <?=$this->flashmessages() ?>

    <?php
    $status = $ticket->getStatus();
    $histories = $ticket->getStatusHistory();
    $historyArray = [];
    foreach ($histories as $history) {
      $historyArray[$history->getName()] = $this->dateTime()->convertToDisplayDate('U', $history->getCreatedAt()->getTimestamp());
    }

    $classDone = 'visited';
    $classActive = 'visited current';
    $classWaiting = '';

    ?>

    <div class="well">
      <ul class="nav-wizard row">
        <li class="part col-md-2">
          <?php if (isset($historyArray['created'])): ?>
            <span class="text-icon text-success"><?=$this->icon('ziskej-done')?></span>
          <?php else: ?>
            <span class="text-icon text-muted"><?=$this->icon('ziskej-waiting')?></span>
          <?php endif; ?>
          <?=$this->transEsc("ZiskejMvs::order_status_created") ?>
          <?php if (isset($historyArray['created'])): ?>
            <small><?=$historyArray['created'] ?></small>
          <?php endif; ?>
        </li>
        <li class="part col-md-2">
          <?php if (isset($historyArray['paid'])): ?>
            <span class="text-icon text-success"><?=$this->icon('ziskej-done')?></span>
          <?php else: ?>
            <span class="text-icon text-muted"><?=$this->icon('ziskej-waiting')?></span>
          <?php endif; ?>
          <?=$this->transEsc("ZiskejMvs::order_status_paid") ?>
          <?php if (isset($historyArray['paid'])): ?>
            <small><?=$historyArray['paid'] ?></small>
          <?php endif; ?>
        </li>
        <?php if (in_array($ticket->getStatus(), ['created', 'paid', 'accepted', 'prepared', 'lent', 'closed'])) : ?>
          <li class="part col-md-2">
            <?php if (isset($historyArray['accepted'])): ?>
              <span class="text-icon text-success"><?=$this->icon('ziskej-done')?></span>
            <?php else: ?>
              <span class="text-icon text-muted"><?=$this->icon('ziskej-waiting')?></span>
            <?php endif; ?>
            <?=$this->transEsc("ZiskejMvs::order_status_accepted") ?>
            <?php if (isset($historyArray['accepted'])): ?>
              <small><?=$historyArray['accepted'] ?></small>
            <?php endif; ?>
          </li>
          <li class="part col-md-2">
            <?php if (isset($historyArray['prepared'])): ?>
              <span class="text-icon text-success"><?=$this->icon('ziskej-done')?></span>
            <?php else: ?>
              <span class="text-icon text-muted"><?=$this->icon('ziskej-waiting')?></span>
            <?php endif; ?>
            <?=$this->transEsc("ZiskejMvs::order_status_prepared") ?>
            <?php if (isset($historyArray['prepared'])): ?>
              <small><?=$historyArray['prepared'] ?></small>
            <?php endif; ?>
          </li>
          <li class="part col-md-2">
            <?php if (isset($historyArray['lent'])): ?>
              <span class="text-icon text-success"><?=$this->icon('ziskej-done')?></span>
            <?php else: ?>
              <span class="text-icon text-muted"><?=$this->icon('ziskej-waiting')?></span>
            <?php endif; ?>
            <?=$this->transEsc("ZiskejMvs::order_status_lent") ?>
            <?php if (isset($historyArray['lent'])): ?>
              <small><?=$historyArray['lent'] ?></small>
            <?php endif; ?>
          </li>
          <li class="part col-md-2">
            <?php if (isset($historyArray['closed'])): ?>
              <span class="text-icon text-success"><?=$this->icon('ziskej-done')?></span>
            <?php else: ?>
              <span class="text-icon text-muted"><?=$this->icon('ziskej-waiting')?></span>
            <?php endif; ?>
            <?=$this->transEsc("ZiskejMvs::order_status_closed") ?>
            <?php if (isset($historyArray['closed'])): ?>
              <small><?=$historyArray['closed'] ?></small>
            <?php endif; ?>
          </li>
        <?php endif; ?>
        <?php if ($ticket->getStatus() == 'cancelled') : ?>
          <li class="part col-md-2">
            <?php if (isset($historyArray['cancelled'])): ?>
              <span class="text-icon text-success"><?=$this->icon('ziskej-done')?></span>
            <?php else: ?>
              <span class="text-icon text-muted"><?=$this->icon('ziskej-waiting')?></span>
            <?php endif; ?>
            <?=$this->transEsc("ZiskejMvs::order_status_cancelled") ?>
            <?php if (isset($historyArray['cancelled'])): ?>
              <small><?=$historyArray['cancelled'] ?></small>
            <?php endif; ?>
          </li>
        <?php endif; ?>
        <?php if ($ticket->getStatus() == 'rejected') : ?>
          <li class="part col-md-2">
            <?php if (isset($historyArray['rejected'])): ?>
              <span class="text-icon text-success"><?=$this->icon('ziskej-done')?></span>
            <?php else: ?>
              <span class="text-icon text-muted"><?=$this->icon('ziskej-waiting')?></span>
            <?php endif; ?>
            <?=$this->transEsc("ZiskejMvs::order_status_rejected") ?>
            <?php if (isset($historyArray['rejected'])): ?>
              <small><?=$historyArray['rejected'] ?></small>
            <?php endif; ?>
          </li>
        <?php endif; ?>
      </ul>
    </div>

    <?php if ($ticket->getStatus() == 'created'): ?>
      <div class="alert alert-warning">
        <?=$this->translate('ZiskejMvs::message_ziskej_message_wait_payment') ?>
      </div>
    <?php endif; ?>

    <div class="text-center well border mb-1">
      <?php if ($ticket->getStatus() == 'created'): ?>
        <a class="btn btn-primary" href="<?=$ticket->getPaymentUrl() ?>?lang=<?=$this->layout()->userLang ?>" title="<?=$this->transEsc("ZiskejMvs::btn_order_pay_title") ?>">
          <?=$this->icon('ziskej-order')?> <?=$this->transEsc("ZiskejMvs::btn_order_pay") ?>
        </a>
      <?php endif; ?>
      <?php if (in_array($ticket->getStatus(), ['created', 'paid'])): ?>
        <a id="cancelButton" class="btn btn-warning" href="<?=$this->url('myresearch-ziskej-mvs-ticket-cancel', ['eppnDomain' => $userCard->getEppnDomain(), 'ticketId' => $ticket->getId()]) ?>" title="<?=$this->transEsc("ZiskejMvs::btn_order_cancel_title") ?>">
          <?=$this->icon('ui-remove')?> <?=$this->transEsc("ZiskejMvs::btn_order_cancel") ?>
        </a>
      <?php endif; ?>
      <?php if ($ticket->getStatus() == 'cancelled'): ?>
        <div class="alert alert-info"><?=$this->transEsc("ZiskejMvs::msg_order_canceled") ?></div>
      <?php endif; ?>
      <a class="btn btn-info" href="#messages" title="<?=$this->transEsc("ZiskejMvs::btn_order_goto_messages_title") ?>">
        <?=$this->icon('ziskej-order-messages') ?> <?=$this->transEsc("ZiskejMvs::btn_order_goto_messages") ?>
      </a>
      <a class="btn btn-default" href="https://ziskej-info.techlib.cz/reklamace" target="_blank" title="<?=$this->transEsc("ZiskejMvs::btn_order_complaint_title") ?>">
        <?=$this->icon('ziskej-warning')?>
        <?=$this->transEsc("ZiskejMvs::btn_order_complaint") ?>
      </a>
    </div>

    <h3><?=$this->transEsc("ZiskejMvs::header_order_detail") ?></h3>
    <div class="well border">

      <dl class="dl-horizontal dl-left">
        <?php if (!empty($ticket->getCreatedAt())): ?>
          <dt><?=$this->transEsc('ZiskejMvs::date_ordered') ?>:</dt>
          <dd><?=$this->dateTime()->convertToDisplayDateAndTime('U', $ticket->getCreatedAt()->getTimestamp()) ?></dd>
        <?php endif; ?>

        <?php if (!empty($ticket->getUpdatedAt())
          && ($ticket->getUpdatedAt()->getTimestamp() != $ticket->getCreatedAt()->getTimestamp())): ?>
          <dt><?=$this->transEsc('ZiskejMvs::date_updated') ?>:</dt>
          <dd><?=$this->dateTime()->convertToDisplayDate('U', $ticket->getUpdatedAt()->getTimestamp()) ?></dd>
        <?php endif; ?>

        <?php if (!empty($ticket->getRequestedAt())): ?>
          <dt><?=$this->transEsc('ZiskejMvs::date_requested') ?>:</dt>
          <dd><?=$this->dateTime()->convertToDisplayDate('U', $ticket->getRequestedAt()->getTimestamp()) ?></dd>
        <?php endif; ?>

        <?php if (!empty($ticket->getReturnAt())): ?>
          <dt><?=$this->transEsc('ZiskejMvs::label_date_return') ?>:</dt>
          <dd><?=$this->dateTime()->convertToDisplayDate('U', $ticket->getReturnAt()->getTimestamp()) ?></dd>
        <?php endif; ?>
      </dl>
    </div>

    <h3><?=$this->transEsc("ZiskejMvs::header_order_document") ?></h3>
    <div class="well border">
      <?php if($this->driver): ?>
        <?=$this->render('_ziskejticket-core.phtml') ?>
        <div class="text-right">
          <a href="<?=$this->recordLinker()->getUrl($this->driver) ?>" class="title" title="<?=$this->transEsc("ZiskejMvs::btn_order_document_title") ?>"><?=$this->transEsc("ZiskejMvs::btn_order_document") ?></a>
        </div>
      <?php else: ?>
        <div class="alert alert-warning">
          <?=$this->transEsc('record_info_not_available')?>
        </div>
      <?php endif; ?>
    </div>

    <div id="messages">
      <h3>
        <?=$this->transEsc("ZiskejMvs::header_order_messages") ?>
        <?php if ($ticket->getCountMessages() > 0): ?>
          <span class="badge"><?=$ticket->getCountMessages() ?></span>
        <?php endif; ?>
      </h3>
      <div class="well border">
        <?php if (is_countable($messages->getAll()) && count($messages->getAll())): ?>
          <?php
          foreach ($messages->getAll() as $message): ?>
            <ul class="media-list">
              <li class="media">
                <div class="media-body">
                  <p class="media-heading">
                    <?php if ($message->getSender() == 'reader'): ?>
                      <span title="<?=$this->transEsc("ZiskejMvs::label_user") ?>"><?=$this->icon('profile')?></span>
                    <?php else: ?>
                      <?=$this->transEsc("ZiskejMvs::label_library") ?>
                    <?php endif; ?>
                    <?=$this->dateTime()->convertToDisplayDateAndTime('U', $message->getCreatedAt()->getTimestamp()) ?>
                  </p>
                  <div>
                    <?=$message->getText() ?>
                  </div>
                </div>
              </li>
            </ul>
          <?php endforeach; ?>
        <?php else: ?>
          <div class="alert alert-info">
            <?=$this->transEsc("ZiskejMvs::msg_order_no_messages") ?>
          </div>
        <?php endif; ?>

        <div>
          <hr>
          <h4><?=$this->transEsc("ZiskejMvs::header_order_new_message") ?></h4>
          <form method="post" action="<?=$this->url('myresearch-ziskej-mvs-message-post', ['eppnDomain' => $userCard->getEppnDomain(), 'ticketId' => $ticket->getId()]) ?>">
            <div class="form-group">
              <label for="ticketMessage"><?=$this->transEsc("ZiskejMvs::label_ticketMessage") ?>:</label>
              <textarea name="ticketMessage" id="ticketMessage" class="form-control" rows="3" required></textarea>
            </div>
            <button type="submit" class="btn btn-primary"><?=$this->transEsc("ZiskejMvs::btn_message_send") ?></button>
          </form>
        </div>
      </div>
    </div>

  </div>


  <div class="<?=$this->layoutClass('sidebar') ?>">
    <?=$this->context($this)->renderInContext("myresearch/menu.phtml", ['active' => 'ziskej']) ?>
  </div>

</div>
<?php
$confirmationText = $this->translate('ZiskejMvs::btn_order_cancel_confirm', ['%orderId' => $ticket->getHid()]);
$script = <<<JS
  $('#cancelButton').click(function confirmCancelTicket() {
    return confirm('$confirmationText');
  });
JS;
echo $this->inlineScript(\Laminas\View\Helper\HeadScript::SCRIPT, $script, 'SET');
