<?php

use Mzk\ZiskejApi\Enum\StatusName;

$this->layout()->searchbox = false;

/** @var \VuFind\Db\Row\UserCard $userCard */
$userCard = $this->userCard;

/** @var \Mzk\ZiskejApi\ResponseModel\TicketMvs $ticket */
$ticket = $this->ticket;

/** @var \Mzk\ZiskejApi\ResponseModel\MessageCollection $messages */
$messages = $this->messages;

/** @var \KnihovnyCz\View\Helper\KnihovnyCz\ZiskejMvs $viewHelperZiskej */
$viewHelperZiskej = $this->ziskejMvs();
?>
<?php
// Set up page title:
$this->headTitle($this->translate('ZiskejMvs::header_order_ziskej_num') . ' ' . $ticket->hid);
?>

<div class="<?=$this->layoutClass('mainbody') ?>">

  <h2>
    <?=$this->transEsc('ZiskejMvs::header_order_ziskej_num') . ' ' . $ticket->hid ?>
    <span class="badge text-bg-<?=$viewHelperZiskej->getStatusClass($ticket->status) ?>">
      <?=$this->translate('ZiskejMvs::order_status_' . $ticket->status->value) ?>
    </span>
  </h2>

  <?=$this->flashmessages() ?>

  <?php
  $histories = $ticket->statusHistory;
  $historyArray = [];
  foreach ($histories as $history) {
    $historyArray[$history->statusName->value] = $this->dateTime()->convertToDisplayDate('U', $history->createdAt->getTimestamp());
  }

  $classDone = 'visited';
  $classActive = 'visited current';
  $classWaiting = '';

  ?>

  <div class="well">
    <ul class="nav-wizard row">
      <li class="part col-md-2">
        <?php if (isset($historyArray[StatusName::CREATED->value])): ?>
          <span class="text-icon text-success"><?=$this->icon('ziskej-done')?></span>
        <?php else: ?>
          <span class="text-icon text-muted"><?=$this->icon('ziskej-waiting')?></span>
        <?php endif; ?>
        <?=$this->transEsc('ZiskejMvs::order_status_created') ?>
        <?php if (isset($historyArray[StatusName::CREATED->value])): ?>
          <small><?=$historyArray[StatusName::CREATED->value] ?></small>
        <?php endif; ?>
      </li>
      <li class="part col-md-2">
        <?php if (isset($historyArray[StatusName::PAID->value])): ?>
          <span class="text-icon text-success"><?=$this->icon('ziskej-done')?></span>
        <?php else: ?>
          <span class="text-icon text-muted"><?=$this->icon('ziskej-waiting')?></span>
        <?php endif; ?>
        <?=$this->transEsc('ZiskejMvs::order_status_paid') ?>
        <?php if (isset($historyArray[StatusName::PAID->value])): ?>
          <small><?=$historyArray[StatusName::PAID->value] ?></small>
        <?php endif; ?>
      </li>
      <?php
      if (in_array($ticket->status, [
        StatusName::CREATED,
        StatusName::PAID,
        StatusName::ACCEPTED,
        StatusName::PREPARED,
        StatusName::LENT,
        StatusName::CLOSED,
      ])): ?>
        <li class="part col-md-2">
          <?php if (isset($historyArray[StatusName::ACCEPTED->value])): ?>
            <span class="text-icon text-success"><?=$this->icon('ziskej-done')?></span>
          <?php else: ?>
            <span class="text-icon text-muted"><?=$this->icon('ziskej-waiting')?></span>
          <?php endif; ?>
          <?=$this->transEsc('ZiskejMvs::order_status_accepted') ?>
          <?php if (isset($historyArray[StatusName::ACCEPTED->value])): ?>
            <small><?=$historyArray[StatusName::ACCEPTED->value] ?></small>
          <?php endif; ?>
        </li>
        <li class="part col-md-2">
          <?php if (isset($historyArray[StatusName::PREPARED->value])): ?>
            <span class="text-icon text-success"><?=$this->icon('ziskej-done')?></span>
          <?php else: ?>
            <span class="text-icon text-muted"><?=$this->icon('ziskej-waiting')?></span>
          <?php endif; ?>
          <?=$this->transEsc('ZiskejMvs::order_status_prepared') ?>
          <?php if (isset($historyArray[StatusName::PREPARED->value])): ?>
            <small><?=$historyArray[StatusName::PREPARED->value] ?></small>
          <?php endif; ?>
        </li>
        <li class="part col-md-2">
          <?php if (isset($historyArray[StatusName::LENT->value])): ?>
            <span class="text-icon text-success"><?=$this->icon('ziskej-done')?></span>
          <?php else: ?>
            <span class="text-icon text-muted"><?=$this->icon('ziskej-waiting')?></span>
          <?php endif; ?>
          <?=$this->transEsc('ZiskejMvs::order_status_lent') ?>
          <?php if (isset($historyArray[StatusName::LENT->value])): ?>
            <small><?=$historyArray[StatusName::LENT->value] ?></small>
          <?php endif; ?>
        </li>
        <li class="part col-md-2">
          <?php if (isset($historyArray[StatusName::CLOSED->value])): ?>
            <span class="text-icon text-success"><?=$this->icon('ziskej-done')?></span>
          <?php else: ?>
            <span class="text-icon text-muted"><?=$this->icon('ziskej-waiting')?></span>
          <?php endif; ?>
          <?=$this->transEsc('ZiskejMvs::order_status_closed') ?>
          <?php if (isset($historyArray[StatusName::CLOSED->value])): ?>
            <small><?=$historyArray[StatusName::CLOSED->value] ?></small>
          <?php endif; ?>
        </li>
      <?php endif; ?>
      <?php if ($ticket->status == StatusName::CANCELLED) : ?>
        <li class="part col-md-2">
          <?php if (isset($historyArray[StatusName::CANCELLED->value])): ?>
            <span class="text-icon text-success"><?=$this->icon('ziskej-done')?></span>
          <?php else: ?>
            <span class="text-icon text-muted"><?=$this->icon('ziskej-waiting')?></span>
          <?php endif; ?>
          <?=$this->transEsc('ZiskejMvs::order_status_cancelled') ?>
          <?php if (isset($historyArray[StatusName::CANCELLED->value])): ?>
            <small><?=$historyArray[StatusName::CANCELLED->value] ?></small>
          <?php endif; ?>
        </li>
      <?php endif; ?>
      <?php if ($ticket->status == StatusName::REJECTED) : ?>
        <li class="part col-md-2">
          <?php if (isset($historyArray[StatusName::REJECTED->value])): ?>
            <span class="text-icon text-success"><?=$this->icon('ziskej-done')?></span>
          <?php else: ?>
            <span class="text-icon text-muted"><?=$this->icon('ziskej-waiting')?></span>
          <?php endif; ?>
          <?=$this->transEsc('ZiskejMvs::order_status_rejected') ?>
          <?php if (isset($historyArray[StatusName::REJECTED->value])): ?>
            <small><?=$historyArray[StatusName::REJECTED->value] ?></small>
          <?php endif; ?>
        </li>
      <?php endif; ?>
    </ul>
  </div>

  <?php if ($ticket->status == StatusName::CREATED): ?>
    <div class="alert alert-warning">
      <?=$this->translate('ZiskejMvs::message_ziskej_message_wait_payment') ?>
    </div>
  <?php endif; ?>

  <div class="text-center well border mb-1">
    <?php if ($ticket->status == StatusName::CREATED): ?>
      <a class="btn btn-primary" href="<?=$ticket->paymentUrl ?>?lang=<?=$this->layout()->userLang ?>" title="<?=$this->transEsc('ZiskejMvs::btn_order_pay_title') ?>">
        <?=$this->icon('ziskej-order')?> <?=$this->transEsc('ZiskejMvs::btn_order_pay') ?>
      </a>
    <?php endif; ?>
    <?php if (in_array($ticket->status->value, [StatusName::CREATED->value, StatusName::PAID->value])): ?>
      <a id="cancelButton" class="btn btn-warning" href="<?=$this->url('myresearch-ziskej-mvs-ticket-cancel', ['eppnDomain' => $userCard->getEppnDomain(), 'ticketId' => $ticket->id]) ?>" title="<?=$this->transEsc('ZiskejMvs::btn_order_cancel_title') ?>">
        <?=$this->icon('ui-remove')?> <?=$this->transEsc('ZiskejMvs::btn_order_cancel') ?>
      </a>
    <?php endif; ?>
    <?php if ($ticket->status == StatusName::CANCELLED): ?>
      <div class="alert alert-info"><?=$this->transEsc('ZiskejMvs::msg_order_canceled') ?></div>
    <?php endif; ?>
    <a class="btn btn-info" href="#messages" title="<?=$this->transEsc('ZiskejMvs::btn_order_goto_messages_title') ?>">
      <?=$this->icon('ziskej-order-messages') ?> <?=$this->transEsc('ZiskejMvs::btn_order_goto_messages') ?>
    </a>
    <a class="btn btn-default" href="https://ziskej-info.techlib.cz/reklamace" target="_blank" title="<?=$this->transEsc('ZiskejMvs::btn_order_complaint_title') ?>">
      <?=$this->icon('ziskej-warning')?>
      <?=$this->transEsc('ZiskejMvs::btn_order_complaint') ?>
    </a>
  </div>

  <h3><?=$this->transEsc('ZiskejMvs::header_order_detail') ?></h3>
  <div class="well border">

    <dl class="dl-horizontal dl-left">
      <?php if (!empty($ticket->createdAt)): ?>
        <dt><?=$this->transEsc('ZiskejMvs::date_ordered') ?>:</dt>
        <dd><?=$this->dateTime()->convertToDisplayDateAndTime('U', $ticket->createdAt->getTimestamp()) ?></dd>
      <?php endif; ?>

      <?php if (!empty($ticket->updatedAt)
        && ($ticket->updatedAt->getTimestamp() != $ticket->createdAt->getTimestamp())): ?>
        <dt><?=$this->transEsc('ZiskejMvs::date_updated') ?>:</dt>
        <dd><?=$this->dateTime()->convertToDisplayDate('U', $ticket->updatedAt->getTimestamp()) ?></dd>
      <?php endif; ?>

      <?php if (!empty($ticket->requestedAt)): ?>
        <dt><?=$this->transEsc('ZiskejMvs::date_requested') ?>:</dt>
        <dd><?=$this->dateTime()->convertToDisplayDate('U', $ticket->requestedAt->getTimestamp()) ?></dd>
      <?php endif; ?>

      <?php if (!empty($ticket->returnAt)): ?>
        <dt><?=$this->transEsc('ZiskejMvs::label_date_return') ?>:</dt>
        <dd><?=$this->dateTime()->convertToDisplayDate('U', $ticket->returnAt->getTimestamp()) ?></dd>
      <?php endif; ?>
    </dl>
  </div>

  <h3><?=$this->transEsc('ZiskejMvs::header_order_document') ?></h3>
  <div class="well border">
    <?php if ($this->driver): ?>
      <?=$this->render('_ziskejticket-core.phtml') ?>
      <div class="text-end">
        <a href="<?=$this->recordLinker()->getUrl($this->driver) ?>" class="title" title="<?=$this->transEsc('ZiskejMvs::btn_order_document_title') ?>"><?=$this->transEsc('ZiskejMvs::btn_order_document') ?></a>
      </div>
    <?php else: ?>
      <div class="alert alert-warning">
        <?=$this->transEsc('record_info_not_available')?>
      </div>
    <?php endif; ?>
  </div>

  <div id="messages">
    <h3>
      <?=$this->transEsc('ZiskejMvs::header_order_messages') ?>
      <?php if ($ticket->countMessages > 0): ?>
        <span class="badge"><?=$ticket->countMessages ?></span>
      <?php endif; ?>
    </h3>
    <div class="well border">
      <?php if (is_countable($messages->getAll()) && count($messages->getAll())): ?>
        <?php
        foreach ($messages->getAll() as $message): ?>
          <ul class="list-unstyled">
            <li class="media">
              <div class="media-body">
                <h4>
                  <?php if ($message->sender == 'reader'): //@todo create enum from 'reader' ?>
                    <span title="<?=$this->transEsc('ZiskejMvs::label_user') ?>"><?=$this->icon('profile')?></span>
                  <?php else: ?>
                    <?=$this->transEsc('ZiskejMvs::label_library') ?>
                  <?php endif; ?>
                  <?=$this->dateTime()->convertToDisplayDateAndTime('U', $message->createdAt->getTimestamp()) ?>
                </h4>
                <div>
                  <?=$message->text ?>
                </div>
              </div>
            </li>
          </ul>
        <?php endforeach; ?>
      <?php else: ?>
        <div class="alert alert-info">
          <?=$this->transEsc('ZiskejMvs::msg_order_no_messages') ?>
        </div>
      <?php endif; ?>

      <div>
        <hr>
        <h4><?=$this->transEsc('ZiskejMvs::header_order_new_message') ?></h4>
        <form method="post" action="<?=$this->url('myresearch-ziskej-mvs-message-post', ['eppnDomain' => $userCard->getEppnDomain(), 'ticketId' => $ticket->id]) ?>">
          <div class="form-group">
            <label for="ticketMessage"><?=$this->transEsc('ZiskejMvs::label_ticketMessage') ?>:</label>
            <textarea name="ticketMessage" id="ticketMessage" class="form-control" rows="3" required></textarea>
          </div>
          <button type="submit" class="btn btn-primary"><?=$this->transEsc('ZiskejMvs::btn_message_send') ?></button>
        </form>
      </div>
    </div>
  </div>

</div>

<div class="<?=$this->layoutClass('sidebar') ?>">
  <?=$this->accountMenu()->render('ziskej');?>
</div>

<?php
$confirmationText = $this->translate('ZiskejMvs::btn_order_cancel_confirm', ['%orderId' => $ticket->hid]);
$script = <<<JS
      $('#cancelButton').click(function confirmCancelTicket() {
        return confirm('$confirmationText');
      });
    JS;
echo $this->assetManager()->outputInlineScriptString($script);
