<?php
  $this->loginTarget = ($this->frontPage ?? false) ? $this->url('myresearch-frontpagelogin') : $this->url('myresearch-userlogin');
  $this->slot('inspiration-link')->set('');
?>
<?php $this->slot('registration-link')->start(); ?>
  <a href="https://www.lib.cas.cz/sluzby/vypujcni-sluzby/registrace/" class="btn btn-primary">
    <?=$this->icon('sign-up') ?>
    <?=$this->translate('registration_link_label')?>
  </a>
<?php $this->slot('registration-link')->end(); ?>
<?php include $this->parentTemplate('header.phtml');?>
