version: '2.2'
services:
    vufind6:
        image: "moravianlibrary/${IMAGE_NAME:-knihovny-cz-deploy}:${IMAGE_VERSION:-latest}"
        extends:
            file: docker-compose.yaml
            service: knihovny-cz
        env_file:
           - deploy.env
        build:
            context: "builds/knihovny-cz-source6"
            args:
                PARAM_VUFIND_BRANCH: ""
                PARAM_VUFIND_COMMIT_HASH: ""
        network_mode: bridge
