version: '2.2'
services:
    devel6:
        image: "localhost/${IMAGE_NAME:-knihovny-cz-devel}"
        extends:
            file: docker-compose.yaml
            service: knihovny-cz
        env_file:
           - devel.env
        build:
            context: "builds/knihovny-cz-source6"
            args:
                PARAM_VUFIND_BRANCH: ""
                PARAM_VUFIND_COMMIT_HASH: ""
        volumes:
            - "./data/devel/:/data/"
        network_mode: bridge
    devel6-10000:
        extends:
            service: devel
        container_name: "${CONTAINER_NAME:-vufind-devel6-10000}"
        environment:
            PARAM_VUFIND_SSL_PORT: "10000"
    devel6-10001:
        extends:
            service: devel
        container_name: "${CONTAINER_NAME:-vufind-devel6-10001}"
        environment:
            PARAM_VUFIND_SSL_PORT: "10001"
    devel6-10002:
        extends:
            service: devel
        container_name: "${CONTAINER_NAME:-vufind-devel6-10002}"
        environment:
            PARAM_VUFIND_SSL_PORT: "10002"
    devel6-10003:
        extends:
            service: devel
        container_name: "${CONTAINER_NAME:-vufind-devel6-10003}"
        environment:
            PARAM_VUFIND_SSL_PORT: "10003"
    devel6-10004:
        extends:
            service: devel
        container_name: "${CONTAINER_NAME:-vufind-devel6-10004}"
        environment:
            PARAM_VUFIND_SSL_PORT: "10004"
    devel6-10005:
        extends:
            service: devel
        container_name: "${CONTAINER_NAME:-vufind-devel6-10005}"
        environment:
            PARAM_VUFIND_SSL_PORT: "10005"
    devel6-10006:
        extends:
            service: devel
        container_name: "${CONTAINER_NAME:-vufind-devel6-10006}"
        environment:
            PARAM_VUFIND_SSL_PORT: "10006"
    devel6-10007:
        extends:
            service: devel
        container_name: "${CONTAINER_NAME:-vufind-devel6-10007}"
        environment:
            PARAM_VUFIND_SSL_PORT: "10007"
    devel6-10008:
        extends:
            service: devel
        container_name: "${CONTAINER_NAME:-vufind-devel6-10008}"
        environment:
            PARAM_VUFIND_SSL_PORT: "10008"
    devel6-10009:
        extends:
            service: devel
        container_name: "${CONTAINER_NAME:-vufind-devel6-10009}"
        environment:
            PARAM_VUFIND_SSL_PORT: "10009"
