<?php
  $configureDatePicker = null;
  if (!$this->initialized) {
    $lang = $this->layout()->userLang;
    $this->assetManager()->appendStyleLink('vendor/jquery-ui.min.css');
    $this->assetManager()->appendScriptLink('lib/jquery-ui/jquery-ui.min.js');
    $this->assetManager()->appendScriptLink("lib/jquery-ui/jquery-ui-i18n-datepicker-$lang.js");
    $dateFormat = $this->dateTime()->getDisplayDateFormatForJQuery();
    $configureDatePicker = <<<JS
          $(function jQueryReady($) {
            var options = $.extend(
              {},
              $.datepicker.regional["$lang"],
              { dateFormat: "$dateFormat" }
            );
            $.datepicker.setDefaults(options);
          });
        JS;
  }
  $formName = $this->formName ?? null;
  $selector = json_encode(($formName != null) ? "form[name='$formName']" : null);
?>
<?php if ($configureDatePicker != null): ?>
  <?=$this->assetManager()->outputInlineScriptString($configureDatePicker)?>
<?php endif; ?>
<?php
  $loadJs = <<<JS
        $(function jQueryReady($) {
          initDatePicker($selector);
        });
      JS;
?>
<?=$this->assetManager()->outputInlineScriptString($loadJs)?>
