<?php $similarRecords = $this->related->getResults(); ?>
<?php if (!empty($similarRecords)): ?>
  <h2><?=$this->transEsc('Similar Items')?></h2>
  <div class='similar-items-container list-group'>
    <?php foreach ($similarRecords as $data): ?>
      <?php
        $format = $data->format ?? null;
        $url = $this->recordLinker()->getUrl($data->id);
        $alt = $this->escapeHtmlAttr($data->title);
        $dataAttrs = '';
        foreach (['id', 'ean', 'cnb', 'isbn', 'issn', 'ismn', 'format'] as $attrName) {
          if (isset($data->$attrName)) {
            $value = is_array($data->$attrName) ? $data->$attrName[0] : $data->$attrName;
            $dataAttrs .= sprintf('data-%s="%s" ', $attrName, $value);
          }
        }
      ?>
      <div class="row list-group-item clearfix">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-3 similar-item">
          <a href="<?=$this->escapeHtmlAttr($url)?>" title='<?=$this->escapeHtml($data->title)?> (<?=$this->transEscWithPrefix('Format::', $format)?>)' tabindex='-1'>
              <div class="ajaxcoverobalkyknih">
                <?php if ($format !== null): ?>
                  <?php $formatClass = 'format-' . preg_replace('/[^a-z]/', '', strtolower($format)); ?>
                  <div class="spinner"><i class="cover-icon <?=$formatClass?>"></i></div>
                <?php else: ?>
                  <div class="spinner"><?=$this->icon('spinner') . $this->translate('loading_ellipsis')?></div>
                <?php endif; ?>
                <div class="cover-container">
                  <img <?=$dataAttrs?>  data-coversize="small" class="recordcover ajax" alt="<?=$alt ?>">
                </div>
              </div>
          </a>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-9 similar-item content">
          <h5 class="list-group-item-heading">
            <a href='<?=$this->escapeHtmlAttr($url)?>' title='<?=$this->escapeHtml($data->title)?> (<?=$this->transEscWithPrefix('Format::', $format)?>)'>
              <strong><?=$this->escapeHtml($data->title)?></strong>
            </a>
          </h5>
          <p class="list-group-item-text">
            <?php $author = $data->author ?? null;
            if (isset($author)): ?>
              <?=$this->escapeHtml($author);?>
            <?php endif; ?>
          </p>
        </div>
      </div>
    <?php endforeach; ?>
  </div>
<?php endif;
$this->headScript()->appendFile('obalkyknih.js');
