<?php $similarRecords = $this->related->getResults(); ?>
<?php if (!empty($similarRecords)): ?>
  <h2><?=$this->transEsc('Similar Items')?></h2>
  <div>
    <?php foreach ($similarRecords as $data): ?>
      <?php
        $format = $data->format ?? null;
        $url = $this->recordLinker()->getUrl($data->id);
        $alt = $this->escapeHtmlAttr($data->title);
        $dataAttrs = '';
        foreach (['id', 'ean', 'cnb', 'isbn', 'issn', 'ismn', 'format'] as $attrName) {
          if (isset($data->$attrName)) {
            $value = is_array($data->$attrName) ? $data->$attrName[0] : $data->$attrName;
            $dataAttrs .= sprintf('data-%s="%s" ', $attrName, $value);
          }
        }
      ?>
      <div class="card mb-1">
        <div class="row">
          <div class="col-md-4">
            <div class="card-body text-center">
              <a href="<?=$this->escapeHtmlAttr($url)?>" title='<?=$this->escapeHtml($data->title)?> (<?=$this->transEscWithPrefix('Format::', $format)?>)' tabindex='-1'>
                <div class="ajaxcoverobalkyknih">
                  <?php if ($format !== null): ?>
                    <?php $formatClass = 'format-' . preg_replace('/[^a-z]/', '', strtolower($format)); ?>
                    <div class="spinner"><i class="cover-icon <?=$formatClass?>"></i></div>
                  <?php else: ?>
                    <div class="spinner"><?=$this->icon('spinner') . $this->translate('loading_ellipsis')?></div>
                  <?php endif; ?>
                  <div class="cover-container">
                    <img <?=$dataAttrs?>  data-coversize="small" class="recordcover ajax" alt="<?=$alt ?>">
                  </div>
                </div>
              </a>
            </div>
          </div>
          <div class="col-md-8">
            <div class="card-body">
              <h5 class="card-title">
                <a href='<?=$this->escapeHtmlAttr($url)?>' title='<?=$this->escapeHtml($data->title)?> (<?=$this->transEscWithPrefix('Format::', $format)?>)'>
                  <?=$this->escapeHtml($data->title)?>
                </a>
              </h5>
              <?php $author = $data->author ?? null;
              if (isset($author)): ?>
                <p class="card-text">
                  <?=$this->escapeHtml($author);?>
                </p>
              <?php endif; ?>
            </div>
          </div>
        </div>
      </div>
    <?php endforeach; ?>
  </div>
<?php endif;
$this->assetManager()->appendScriptLink('obalkyknih.js');
