<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<?=$this->doctype() ?>
<html lang="<?=$this->layout()->userLang ?>"<?php if ($this->layout()->rtl): ?> dir="rtl"<?php endif; ?>>
<head>
  <?php $this->setupEmbeddedThemeResources(); ?>
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width,initial-scale=1.0">
  <?=$this->headTitle() ?>
  <?=$this->headMeta() ?>
  <?=$this->googleTagManager()->getHeadCode()?>
  <?=$this->headLink() ?>
  <?=$this->headStyle() ?>
  <?=$this->headScript() ?>
</head>
<body class="template-dir-<?=$this->templateDir?> template-name-<?=$this->templateName?> <?=$this->layoutClass('offcanvas-row')?><?php if ($this->layout()->rtl): ?> rtl<?php endif; ?>">
  <?=$this->content ?>
  <?=$this->footScript() ?>
</body>
</html>
