<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<?php
$alnum = new \Laminas\I18n\Filter\Alnum();

/** @var string $selectedRegion */
$selectedRegion = $this->selectedRegion;

/** @var string $selectedDistrict */
$selectedDistrict = $this->selectedDistrict;

/** @var array $tree Array of libraries (region -> district -> library */
$tree = $this->tree;

/** @var string $color Html anchor color */
$color = $this->color;

$headTitle = $this->translate('EmbeddedLibraries::base_head_title');
if (!empty($selectedRegion)) {
  $headSubtitle = $selectedRegion;
  if (!empty($selectedDistrict)) {
    $headSubtitle = $selectedDistrict . ', ' . $headSubtitle;
  }
  $headTitle = $headTitle . ': ' . $headSubtitle;
}
$this->headTitle($headTitle);

$this->headLink()->appendStylesheet('vendor/bootstrap.min.css');
$this->headLink()->appendStylesheet('vendor/font-awesome.min.css');
$this->headLink()->appendStylesheet('embedded-libraries.css');

$this->headScript()->appendFile('vendor/jquery.min.js');
$this->headScript()->appendFile('vendor/bootstrap.min.js');
$this->headScript()->appendFile('embedded-libraries.js');

$this->headStyle()->appendStyle("
    a {
      color: $color !important;
    }
    a:hover {
      filter: brightness(50%);
    }
    .text-primary {
      color: $color !important;
    }
  ");
?>
<div>
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <div class="row">
        <div class="col-xs-12">
          <div class="input-group">
            <div class="input-group-addon"><i class="fa fa-search" aria-hidden="true"></i></div>
            <input type="text" class="form-control" id="search" placeholder="<?= $this->translate('EmbeddedLibraries::search_input_placeholder') ?>">
            <div class="input-group-btn hidden">
              <button type="button" class="btn" id="btn_filter">Filter</button>
            </div>
          </div>
          <div class="search-checkbox-controls">
            <label class="checkbox-inline" for="is_professional">
              <input class="form-check-input" type="checkbox" id="is_professional">
              <?=$this->translate('EmbeddedLibraries::label_is_professional') ?>
            </label>
            <label class="checkbox-inline" for="is_nonprofessional">
              <input class="form-check-input" type="checkbox" id="is_nonprofessional">
              <?=$this->translate('EmbeddedLibraries::label_is_nonprofessional') ?>
            </label>
            <label class="checkbox-inline" for="is_regional">
              <input class="form-check-input" type="checkbox" value="true" id="is_regional">
              <?=$this->translate('EmbeddedLibraries::label_is_regional') ?>
            </label>
          </div>
        </div>
      </div>
    </div>
  </nav>

  <div class="container-fluid">
    <?php foreach ($tree as $region => $districts): ?>
      <h2><?=$region ?></h2>
      <?php if ($selectedRegion): ?>
        <ul class="nav nav-pills mb-0">
          <?php if ($selectedDistrict): ?>
            <li class="nav-item">
              <a class="nav-link" href="<?=$this->url('embedded-libraries', ['region' => $selectedRegion], ['query' => ['color' => $color]]) ?>">&laquo; <?=$this->translate('EmbeddedLibraries::btn_all_districts') ?></a>
            </li>
          <?php endif; ?>
          <?php foreach ($districts as $district => $libraries): ?>
            <li class="nav-item <?=($district === $selectedDistrict) ? 'active' : '' ?>">
              <a class="nav-link" href="<?=$this->url('embedded-libraries', ['region' => $selectedRegion, 'district' => $district], ['query' => ['color' => $color]]) ?>"><?=$district ?></a>
            </li>
          <?php endforeach; ?>
        </ul>
        <hr>
      <?php endif; ?>

      <?php foreach ($districts as $district => $libraries): ?>
        <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title" data-toggle="collapse" href="#collapse_<?=$alnum->filter($district) ?>">
              <?=$district ?>
            </h3>
          </div>
          <div id="collapse_<?=$alnum->filter($district) ?>" class="collapse in">
            <div class="panel-body">
              <?php if (count($libraries)): ?>
                <div class="row display-flex">
                  <?php foreach ($libraries as $library): ?>
                    <?php if ($library['is_regional']): ?>
                      <div class="col-xs-12 col-sm-6 col-md-6 col-lg-4 card-library" data-regional="<?= $library['is_regional'] ? 1 : 0 ?>" data-professional="<?= $library['is_professional'] ? 1 : 0 ?>">
                        <div class="panel panel-default">
                          <div class="panel-body">
                            <h4>
                              <?php if($library['is_professional']): ?>
                                <span class="pull-right text-primary" title="<?=$this->translate('EmbeddedLibraries::function_professional_library') ?>"><i class="fa fa-fw fa-building" aria-hidden="true"></i></span>
                              <?php endif; ?>
                              <span class="pull-right text-primary" title="<?=$this->translate('EmbeddedLibraries::function_regional_library') ?>"><i class="fa fa-fw fa-dot-circle-o" aria-hidden="true"></i></span>
                              <a href="<?=$this->url('search2record', ['id' => $library['link']]) ?>" target="_blank" title="<?=$library['title'] ?>">
                                <?=$library['title'] ?>
                              </a>
                            </h4>
                            <span class="text-muted"><i class="fa fa-fw fa-map-marker" aria-hidden="true"></i> <?=$library['town'] ?></span>
                          </div>
                        </div>
                      </div>
                    <?php endif; ?>
                  <?php endforeach; ?>

                  <?php foreach ($libraries as $library): ?>
                    <?php if (!$library['is_regional']): ?>
                      <div class="col-xs-12 col-sm-6 col-md-6 col-lg-4 card-library" data-regional="<?= $library['is_regional'] ? 1 : 0 ?>" data-professional="<?= $library['is_professional'] ? 1 : 0 ?>">
                        <div class="panel panel-default" data-filter="<?=$library['title'] ?> | <?=$library['town'] ?>">
                          <div class="panel-body">
                            <h4>
                              <?php if($library['is_professional']): ?>
                                <span class="pull-right text-primary" title="<?=$this->translate('EmbeddedLibraries::function_professional_library') ?>"><i class="fa fa-fw fa-building" aria-hidden="true"></i></span>
                              <?php endif; ?>
                              <a href="<?=$this->url('search2record', ['id' => $library['link']]) ?>" target="_blank" title="<?=$library['title'] ?>">
                                <?=$library['title'] ?>
                              </a>
                            </h4>
                            <span class="text-muted"><i class="fa fa-fw fa-map-marker" aria-hidden="true"></i> <?=$library['town'] ?></span>
                          </div>
                        </div>
                      </div>
                    <?php endif; ?>
                  <?php endforeach; ?>
                </div>
              <?php else: ?>
                <div class="alert alert-info">
                  <?=$this->translate('EmbeddedLibraries::no_items_region') ?>
                </div>
              <?php endif; ?>
            </div>
          </div>
        </div>
      <?php endforeach; ?>
    <?php endforeach; ?>
  </div>
</div>
<footer>
  <div class="container-fluid">
    <p class="text-center">
      <a class="link-image lang-<?=$this->layout()->userLang ?>" href="<?=$this->url('search2-results') ?>" target="_blank">
        <img class="knihovny-logo" src="<?=$this->render('layout/logoimagelink.phtml') ?>" alt="<?=$this->translate('logo_alt') ?>">
      </a>
    </p>
    <p class="text-right">
      <?=$this->translate('EmbeddedLibraries::data_by') ?>: <a href="https://www.nkp.cz/" target="_blank"><?=$this->translate('EmbeddedLibraries::nkp') ?></a>.
    </p>
  </div>
</footer>
