<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<?php
$this->headTitle($this->title);
$this->assetManager()->appendStyleLink('embedded-search.css');
$center = $this->position == 'top' ? 'center' : '';
$language = $this->language ?? $this->layout()->userLang;
$logo = $this->render('layout/logoimagelink.phtml', ['language' => $language]);
?>
<?php if (!empty($logo)): ?>
  <a href="<?=$this->baseUrl ?>" title="<?=$this->transEsc($this->title) ?>">
    <img class="logo <?=$center ?>" src="<?=$logo ?>" alt="<?=$this->translate('logo_alt') ?>">
  </a>
<?php endif; ?>
<form action="<?=$this->escapeHtmlAttr($this->link) ?>" method="get" class="search-body <?=$center ?>" target="_blank">
  <input type="hidden" name="type" value="<?=$this->escapeHtmlAttr($this->type) ?>">
  <input type="hidden" name="lng" value="<?=$this->escapeHtmlAttr($language) ?>">
  <?php if (!empty($filters)): ?>
    <?php foreach ($filters as $filter): ?>
      <input type="hidden" name="filter[]" value="<?=$this->escapeHtmlAttr($filter) ?>">
    <?php endforeach; ?>
  <?php endif; ?>
  <div class="input-group">
    <input class="form-control lookfor <?=$center ?>" type="text" name="lookfor" value="<?=$this->escapeHtmlAttr($this->lookfor) ?>">
    <button class="btn btn-primary" type="submit"><?=$this->translate('Find') ?></button>
  </div>
</form>
