<?php $this->slot('footer-linkbar')->start(); ?>
<div class="linkbar">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-6 col-md-4">
        <ul class="list-unstyled">
          <li><a href="<?=$this->url('inspiration-conspectus') ?>"><?=$this->transEsc('funds_thematic_map')?></a></li>
          <li><?=$this->footerLink('ochrana-osobnich-udaju') ?></li>
        </ul>
      </div>
      <div class="col-xs-12 col-sm-6 col-md-4">
        <ul class="list-unstyled">
          <li><?=$this->footerLink('napoveda') ?></li>
        </ul>
      </div>
      <div class="col-xs-12 col-sm-6 col-md-4">
        <ul class="list-unstyled">
          <li><a data-lightbox href="<?=$this->url('feedback-home') ?>"><?=$this->transEsc('Feedback')?></a></li>
        </ul>
      </div>
    </div>
  </div>
<?php $this->slot('footer-linkbar')->end(); ?>
<?php $this->slot('footer-credits')->start(); ?>
<h3><?=$this->translate('footer_heading_powered_by') ?></h3>
<div>
  <a href="https://www.knihovny.cz/" title="Knihovny.cz" target="_blank" rel="nofollow">
    <img class="logo" src="<?=$this->imageLink('logos/logo-knihovny.cz.svg') ?>" alt="Logo Knihovny.cz">
  </a>
</div>
<?=$this->slot('footer-credits')->end(); ?>
