<?php $this->render('footer-view-linkbar.phtml'); ?>
<?php $this->slot('footer-description')->start(); ?>
<p class="text"><?=$this->translate('Footer text') ?></p>
<?php $this->slot('footer-description')->end() ?>
<?php $this->slot('footer-follow-links')->start() ?>
<h3><?=$this->translate('Follow us') ?></h3>
<ul class="list-inline">
  <li class="list-inline-item">
    <a href="http://www.facebook.com/narodni.knihovna" title="<?=$this->translate('Facebook: Národní knihovna ČR') ?>" target="_blank">
      <?=$this->icon('facebook', 'fa-2x') ?>
    </a>
  </li>
  <li class="list-inline-item">
    <a href="https://x.com/narodniknihovna" title="<?=$this->translate('X: Národní knihovna ČR') ?>" target="_blank">
      <?=$this->icon('twitter', 'fa-2x') ?>
    </a>
  </li>
  <li class="list-inline-item">
    <a href="https://www.instagram.com/narodni_knihovna_cr" title="<?=$this->translate('Instagram: Národní knihovna ČR') ?>" target="_blank">
      <?=$this->icon('instagram', 'fa-2x') ?>
    </a>
  </li>
  <li class="list-inline-item">
    <a href="https://www.youtube.com/NarodniknihovnaCR" title="<?=$this->translate('YouTube: Národní knihovna ČR') ?>" target="_blank">
      <?=$this->icon('youtube', 'fa-2x') ?>
    </a>
  </li>
  <li class="list-inline-item">
    <a href="https://www.linkedin.com/company/n%C3%A1rodn%C3%AD-knihovna-%C4%8Desk%C3%A9-republiky" title="<?=$this->translate('LinkedIn: Národní knihovna České republiky') ?>" target="_blank">
      <?=$this->icon('linkedin', 'fa-2x') ?>
    </a>
  </li>
</ul>
<?php $this->slot('footer-follow-links')->end(); ?>
<?php include $this->parentTemplate('footer.phtml');?>
