<?php
  $formatClass = match($this->format) {
    'Audio Recording', 'Streaming Audio' => 'audio',
    'Book', 'Book Chapter' => 'books',
    'eBook' => 'ebook',
    'Computer File', 'Web Resource', 'Electronic Resource' => 'ebook',
    'Dissertation', 'Manuscript', 'Paper', 'Patent' => 'thesis',
    'Kit', 'Data Set' => 'other',
    'Image', 'Photograph' => 'visualdocuments',
    'Music Score' => 'musicalscores',
    'Map' => 'maps',
    'Video Recording', 'Video', 'Streaming Video' => 'video',
    'Standard' => 'norms',
    default => 'articles',
  };
  echo 'format-' . $formatClass;
