<h1>Geographic Search Tips</h1>
<dl class="Content">
  <dt></dt>
  <dd>
    <ul>
      <li>Click on the 'Draw Search Box' button.</li>
      <li>Click, drag and release the mouse button to select the rectangle on the map that defines the search area.</li>
      <li>Below the map, you can specify the scale of searched documents by entering numbers or dragging the slider.</li>
      <li>The search results will display cartographic documents related to the specified area and scale.</li>
      <li>Please be aware that the geographic search will only find cartographic documents whose bibliographic record contains GPS coordinates and scale.</li>
    </ul>
  </dd>
</dl>
