<?php
/*
 *  We need to find out if we're supposed to display an OpenURL link ($openUrlActive),
 *  but even if we don't plan to display the link, we still want to get the $openUrl
 *  value for use in generating a COinS (Z3988) tag -- see bottom of file.
 */
$openUrl = $this->driver->getOpenUrl();
?>

<span class="openurl" data-lazy="<?=($this->lazy)?'true':'false'?>" data-openurl="<?=$this->escapeHtml($openUrl)?>">
  <?php if($this->lazy): ?>
    <?=$this->transEsc("Check fulltext availability")?>
  <?php else: ?>
    <?=$this->icon('spinner')?>
  <?php endif; ?>
</span>
