<?php
$openUrl = $this->driver->getOpenUrl();
$accessUrl = $this->driver->getAccessUrl();
?>
<?php if($accessUrl != null): ?>
  <div class="records-in-libraries-title">
    <strong><?=$this->transEsc('Fulltext is free')?></strong>
    <ul class="list-unstyled">
      <li>
        <a href="<?=$this->escapeHtml($accessUrl)?>" title="<?=$this->translate('Fulltext')?>"><?=$this->transEsc('Fulltext')?></a>
      </li>
    </ul>
  </div>
<?php else: ?>
  <span class="openurl" data-lazy="<?=($this->lazy)?'true':'false'?>" data-openurl="<?=$this->escapeHtml($openUrl)?>">
    <?php if($this->lazy): ?>
      <button type="button" class="btn btn-success">
        <strong><?=$this->transEsc("Check fulltext availability")?></strong>
      </button>
    <?php else: ?>
      <?=$this->icon('spinner')?>
    <?php endif; ?>
  </span>
<?php endif; ?>
