<?php
  $this->metadata()->generateMetatags($this->driver);
?>
<div class="media"<?=$this->schemaOrg()->getAttributes(['vocab' => 'http://schema.org/', 'resource' => '#record', 'typeof' => $this->schemaOrg()->getRecordTypes($this->driver)])?>>
  <?php
    $sigla = $this->driver->tryMethod('getSiglaDisplay');
    $recordHelper = $this->record($this->driver);
    $QRCode = $recordHelper->getQRCode('core');
    $largeImage = $recordHelper->getThumbnail('large');
    $linkAttributes = $largeImage ? ['href' => $largeImage, 'data-lightbox-image' => 'true'] : [];
    $coverDetails = $recordHelper->getCoverDetails('core', 'medium', $linkAttributes);
    $cover = $coverDetails['html'];
    $preview = ($this->previewOverride ?? false)
      ? $this->previewOverride : $recordHelper->getPreviews();
    $rating = $this->driver->isRatingAllowed();
  ?>
  <?php if ($QRCode || $cover || $preview || $rating): ?>
    <div class="media-left <?=$this->escapeHtmlAttr($coverDetails['size'])?> img-col">
      <?php /* Display thumbnail if appropriate: */ ?>
      <?php if ($cover): ?>
        <?=$cover?>
      <?php endif; ?>

      <?php /* Display qrcode if appropriate: */ ?>
      <?php if ($QRCode): ?>
        <span class="record-qrcode">
          <br><img alt="<?=$this->transEscAttr('QR Code')?>" class="qrcode" src="<?=$this->escapeHtmlAttr($QRCode);?>">
        </span>
      <?php endif; ?>

      <?php /* Display rating if enabled: */ ?>
      <?php if ($rating): ?>
        <?=$recordHelper->renderTemplate('rating.phtml')?>
      <?php endif; ?>

      <?php // if you have a preview tab but want to move or remove the preview link
         // from this area of the record view, this can be split into
         // getPreviewData() (should stay here) and
         // getPreviewLink() (can go in your desired tab) ?>
      <?php if ($preview): ?>
        <div class="record-previews">
          <?=$preview?>
        </div>
      <?php endif; ?>
    </div>
  <?php endif; ?>
  <div class="media-body">
    <h1<?=$this->schemaOrg()->getAttributes(['property' => 'name'])?> class="record-title" data-sigla="<?=$sigla ?: 'undefined' ?>"><?=$this->escapeOrCleanHtml($this->driver->getShortTitle())?></h1>

    <?php if ($this->driver->getExtraDetail('cached_record') && !$this->translationEmpty('cached_record_warning')): ?>
      <div class="alert alert-warning">
        <?=$this->transEsc('cached_record_warning')?>
      </div>
    <?php endif; ?>
    <?=$this->record($this->driver)->getLabelList() ?>

    <?=$this->record($this->driver)->renderTemplate('wantit.phtml');?>

    <?php foreach ($this->driver->tryMethod('getFullTitlesAltScript', [], []) as $altTitle): ?>
      <div class="title-alt">
        <?=$this->escapeOrCleanHtml($altTitle, 'title-alt')?>
      </div>
    <?php endforeach; ?>

    <?php if (!empty($this->extraControls)): ?>
      <?=$this->extraControls['actionControls'] ?? ''?>
      <?=$this->extraControls['availabilityInfo'] ?? ''?>
    <?php endif; ?>

    <?php if ($this->searchOptions($this->driver->getSourceIdentifier())->getVersionsAction()): ?>
      <?=$recordHelper->renderTemplate('versions-link.phtml')?>
    <?php endif; ?>

    <?=$this->record($this->driver)->renderTemplate('summary.phtml', ['driver' => $this->driver, 'length' => 360, 'expandable' => true])?>

    <?php if ($this->userlist()->getMode() !== 'disabled'): ?>
      <?php /* Display the lists that this record is saved to */ ?>
      <div class="savedLists">
        <strong><?=$this->transEsc('Saved in')?>:</strong>
      </div>
    <?php endif; ?>

    <?php /* Display Main Details */ ?>
    <?=
      $recordHelper->renderTemplate(
          'core-fields.phtml',
          [
            'driver' => $this->driver,
            'defaults' => $this->driver->tryMethod('getRecordDataFormatterKey') ?? 'core',
            'caption' => $this->driver->tryMethod('getRecordDataTypeDescription') ?? 'Bibliographic Details',
          ]
      );
    ?>
    <?php /* End Main Details */ ?>

    <?php if (($link = $this->driver->tryMethod('getEodLink', [], null)) != null): ?>
      <?php
        $lang = $this->layout()->userLang;
        $imageLink = "externalLogos/eod_button_$lang.png";
      ?>
      <div>
        <a href="<?=$link?>" target="_blank" rel="nofollow noopener">
          <img src="<?=$this->imageLink($imageLink);?>" alt="<?=$this->transEsc('eod_link_alt_text')?>">
        </a>
      </div>
    <?php endif; ?>

  </div>
</div>
