<?php
  $this->metadata()->generateMetatags($this->driver);
?>
<div class="media" vocab="http://schema.org/" resource="#record" typeof="<?=$this->driver->getSchemaOrgFormats()?> Product">
  <?php
    $sigla = $this->driver->tryMethod('getSiglaDisplay');
    $QRCode = $this->record($this->driver)->getQRCode("core");
    $coverDetails = $this->record($this->driver)->getCoverDetails('core', 'medium', $this->record($this->driver)->getThumbnail('large'));
    $cover = $coverDetails['html'];
    $preview = ($this->previewOverride ?? false)
      ? $this->previewOverride : $this->record($this->driver)->getPreviews();
    $rating = $this->driver->isRatingAllowed();
  ?>
  <?php if ($QRCode || $cover || $preview || $rating): ?>
    <div class="media-left <?=$this->escapeHtmlAttr($coverDetails['size'])?> img-col">
      <?php /* Display thumbnail if appropriate: */ ?>
      <?php if ($cover): ?>
        <?=$cover?>
      <?php endif; ?>

      <?php /* Display qrcode if appropriate: */ ?>
      <?php if ($QRCode): ?>
        <span class="hidden-xs">
          <br/><img alt="<?=$this->transEscAttr('QR Code')?>" class="qrcode" src="<?=$this->escapeHtmlAttr($QRCode);?>"/>
        </span>
      <?php endif; ?>

      <?php /* Display rating if enabled: */ ?>
      <?php if ($rating): ?>
        <?=$this->record($this->driver)->renderTemplate('rating.phtml')?>
      <?php endif; ?>

      <?php // if you have a preview tab but want to move or remove the preview link
         // from this area of the record view, this can be split into
         // getPreviewData() (should stay here) and
         // getPreviewLink() (can go in your desired tab) ?>
      <?php if ($preview): ?>
        <div class="record-previews">
          <?=$preview?>
        </div>
      <?php endif; ?>
    </div>
  <?php endif; ?>
  <div class="media-body">
    <h1 property="name" class="record-title" data-sigla="<?=$sigla ?: 'undefined' ?>"><?=$this->escapeHtml($this->driver->getShortTitle())?></h1>
    <?=$this->record($this->driver)->renderTemplate('wantit.phtml');?>
    <?php foreach ($this->driver->tryMethod('getFullTitlesAltScript', [], []) as $altTitle): ?>
      <div class="title-alt">
        <?=$this->escapeHtml($altTitle)?>
      </div>
    <?php endforeach; ?>

    <?php if (!empty($this->extraControls)): ?>
      <?=$this->extraControls['actionControls'] ?? ''?>
      <?=$this->extraControls['availabilityInfo'] ?? ''?>
    <?php endif; ?>

    <?php if ($this->searchOptions($this->driver->getSourceIdentifier())->getVersionsAction()): ?>
      <?=$this->record($this->driver)->renderTemplate('versions-link.phtml')?>
    <?php endif; ?>

    <?=$this->record($this->driver)->renderTemplate('summary.phtml')?>

    <?php if ($this->userlist()->getMode() !== 'disabled'): ?>
      <?php /* Display the lists that this record is saved to */ ?>
      <div class="savedLists">
        <strong><?=$this->transEsc("Saved in")?>:</strong>
      </div>
    <?php endif; ?>

    <?php /* Display Main Details */ ?>
    <?=
      $this->record($this->driver)->renderTemplate(
          'core-fields.phtml',
          [
            'driver' => $this->driver,
            'defaults' => $this->driver->tryMethod('getRecordDataFormatterKey') ?? 'core',
            'caption' => $this->driver->tryMethod('getRecordDataTypeDescription') ?? 'Bibliographic Details',
          ]
      );
    ?>
    <?php /* End Main Details */ ?>
  </div>
</div>
