<?php $alt = $this->link ? trim($this->driver->tryMethod('getTitle') ?? '') : ''; ?>
<?php if ($this->link && !empty($alt)): ?><a href="<?=$this->escapeHtmlAttr($this->link)?>" class="record-cover-link"><?php endif; ?>
<?php /* Display thumbnail if appropriate: */ ?>
<?php if ($cover): ?>
  <img src="<?=$this->escapeHtmlAttr($cover); ?>" <?php if ($linkPreview): ?>data-linkpreview="true" <?php endif; ?>class="recordcover" alt="<?=$this->escapeHtmlAttr($alt); ?>" />
<?php elseif ($cover === false): ?>
  <img src="<?=$this->url('cover-unavailable')?>" <?php if ($linkPreview): ?>data-linkpreview="true" <?php endif; ?>class="recordcover" alt="" />
<?php else: ?>
  <?php
    $formats = $this->driver->getFormats();
    $format = end($formats);
    $formatClass = $this->record($this->driver)->getFormatClass($format);
  ?>
  <div class="ajaxcover">
    <div class="spinner"><i class="cover-icon <?=$formatClass?>"></i></div>
    <div class="cover-container">
      <img <?php if ($linkPreview): ?>data-linkpreview="true" <?php endif; ?>data-context="<?=$this->escapeHtmlAttr($this->context)?>" data-recordsource="<?=$this->escapeHtmlAttr($driver->getSourceIdentifier())?>" data-recordid="<?=$this->escapeHtmlAttr($driver->getUniqueID())?>" data-coversize="<?=$this->escapeHtmlAttr($size)?>" data-format="<?=$this->escapeHtmlAttr($formatClass)?>" class="recordcover ajax" alt="<?=$this->escapeHtmlAttr($alt); ?>" />
    </div>
  </div>
<?php endif; ?>
<?php if ($this->link && !empty($alt)): ?></a><?php endif; ?>
