<?php $summary = $this->driver->getSummary();
$summary = $summary[0] ?? false; ?>
<?php if ($summary): ?>
  <?php
    $splitText = $this->splitText($summary, $this->length ?? 360);
    $exp = $this->expandable ?? false;
  ?>
  <p>
    <span class="text-first"><?=$this->escapeOrCleanHtml($splitText->first())?><?=($splitText->last() && !$exp) ? '…' : '' ?></span>
    <?php if ($splitText->last() && $exp): ?>
      <span class="text-last hidden"><?=$this->escapeOrCleanHtml($splitText->last())?></span>
      <span class="btn-show-full-text">… <a href="#" title="<?=$this->transEsc('full_description')?>"><?=$this->transEsc('full_description')?></a></span>
    <?php endif; ?>
  </p>
<?php endif; ?>
