<?php
$this->assetManager()->appendScriptLink('https://platform-api.sharethis.com/js/sharethis.js#property=682472957c84420012f178b6&product=inline-share-buttons');
?>
<div class="card text-bg-light border-0 mb-5">
  <nav aria-label="<?=$this->transEscAttr('ajaxview_label_tools'); ?>">
    <ul class="nav flex-column">
      <?php if (count($this->driver->getCitationFormats()) > 0): ?>
        <li class="nav-item">
          <a class="cite-record nav-link" data-lightbox href="<?=$this->escapeHtmlAttr($this->recordLinker()->getActionUrl($this->driver, 'Cite'))?>" rel="nofollow">
            <?=$this->icon('cite') ?>
            <?=$this->transEsc('Cite this')?>
          </a>
        </li>
      <?php endif; ?>
      <?php if ($this->accountCapabilities()->getSmsSetting() !== 'disabled'): ?>
        <li class="nav-item">
          <a class="sms-record nav-link" data-lightbox href="<?=$this->escapeHtmlAttr($this->recordLinker()->getActionUrl($this->driver, 'SMS'))?>" rel="nofollow">
            <?=$this->icon('send-sms') ?>
            <?=$this->transEsc('Text this')?>
          </a>
        </li>
      <?php endif; ?>
      <?php if ($this->accountCapabilities()->isEmailActionAvailable()): ?>
        <li class="nav-item">
          <a class="mail-record nav-link" data-lightbox href="<?=$this->escapeHtmlAttr($this->recordLinker()->getActionUrl($this->driver, 'Email'))?>" rel="nofollow">
            <?=$this->icon('send-email') ?>
            <?=$this->transEsc('Email this')?>
          </a>
        </li>
      <?php endif; ?>
      <li class="nav-item">
        <a class="print-record nav-link" href="<?=$this->url()->addQueryParameters(['print' => true])?>" rel="nofollow">
          <?=$this->icon('print') ?>
          <?=$this->transEsc('Print')?>
        </a>
      </li>
      <?php $exportFormats = $this->export()->getFormatsForRecord($this->driver); ?>
      <?php if (count($exportFormats) > 0): ?>
        <li class="nav-item dropdown">
          <a class="export-toggle nav-link dropdown-toggle" data-bs-toggle="dropdown" aria-haspopup="true" href="<?=$this->escapeHtmlAttr($this->recordLinker()->getActionUrl($this->driver, 'Export', [], '', ['excludeSearchId' => true]))?>" rel="nofollow" aria-expanded="false" aria-controls="export-options">
            <?=$this->icon('export') ?>
            <?=$this->transEsc('Export Record') ?>
          </a>
          <ul class="dropdown-menu" id="export-options" role="menu">
            <?php foreach ($exportFormats as $exportFormat): ?>
              <li role="none">
                <a class="dropdown-item" <?php if ($this->export()->needsRedirect($exportFormat)): ?>target="<?=$this->escapeHtmlAttr($exportFormat)?>Main" <?php endif; ?>href="<?=$this->escapeHtmlAttr($this->recordLinker()->getActionUrl($this->driver, 'Export', [], '', ['excludeSearchId' => true]))?>?style=<?=$this->escapeHtmlAttr($exportFormat)?>" rel="nofollow" role="menuitem">
                  <?=$this->transEsc('export_to', ['%%target%%' => $this->translate($this->export()->getLabelForFormat($exportFormat))])?>
                </a>
              </li>
            <?php endforeach; ?>
          </ul>
        </li>
      <?php endif; ?>

      <?php if ($this->userlist()->getMode() !== 'disabled'): ?>
        <li class="nav-item">
          <?php if ($this->permission()->allowDisplay('feature.Favorites')): ?>
            <a class="save-record nav-link" data-lightbox href="<?=$this->escapeHtmlAttr($this->recordLinker()->getActionUrl($this->driver, 'Save'))?>" rel="nofollow">
              <?=$this->icon('user-favorites') ?>
              <?=$this->transEsc('Add to favorites')?>
            </a>
          <?php elseif ($block = $this->permission()->getAlternateContent('feature.Favorites')): ?>
            <?=$block ?>
          <?php endif; ?>
        </li>
      <?php endif; ?>

      <li class="nav-item">
        <a class="share-record nav-link" data-lightbox href="<?=$this->escapeHtmlAttr($this->recordLinker()->getActionUrl($this->driver, 'Share'))?>" rel="nofollow">
          <?=$this->icon('share-record', 'icon-link__icon') ?>
          <span class="icon-link__label"><?=$this->transEsc('share_btn_text')?></span>
        </a>
      </li>

      <?php if ($this->cart()->isActive()): ?>
        <?=$this->render('record/cart-buttons.phtml', ['id' => $this->driver->getUniqueId(), 'source' => $this->driver->getSourceIdentifier(), 'inToolbar' => true]); ?>
      <?php endif; ?>

      <?php if ($this->config()->get('config')->Record->permanent_link ?? true): ?>
        <li class="nav-item">
          <a class="permalink-record nav-link" data-lightbox href="<?=$this->escapeHtmlAttr($this->recordLinker()->getActionUrl($this->driver, 'Permalink'))?>" rel="nofollow">
            <?=$this->icon('external-link') ?>
            <?=$this->transEsc('permanent_link')?>
          </a>
        </li>
      <?php endif ?>
    </ul>
  </nav>
</div>


<?php
$title = $this->escapeJs($this->driver->getTitle());
$text = $this->driver->getSummary();
$text = isset($text[0]) ? $this->escapeJs($text[0]) : '';
$url = $this->escapeJs($this->serverUrl() . $this->recordLinker()->getUrl($this->driver));
$language = $this->escapeJs($this->layout()->userLang);
$js = <<<JS
    // share using navigator.share
    const shareData = {
      title: '$title',
      text: '$text',
      url: '$url'
    }

    const link = document.querySelector('.share-record');

    async function shareWithNavigator(shareData) {
        await navigator.share(shareData);
    }

    // clicking share button either let the modal open or stops modal from opening and shares using navigator.share
    link.addEventListener('click', function(event) {
        if (navigator.canShare instanceof Function && navigator.canShare(shareData)) {
            event.preventDefault();
            $(this).off('click');
            shareWithNavigator(shareData);
        }
    });

    // ininialize shathis buttons in modal after it opens
    var observer = new MutationObserver(function() {
        if (document.contains(document.getElementById('modal-sharethis-buttons'))) {
            window.__sharethis__.initialize();
      }
    });
    observer.observe(document, {attributes: false, childList: true, characterData: false, subtree:true});
    JS;
?>
<?=$this->assetManager()->outputInlineScriptString($js)?>

