<?php
  $addThis = $this->addThis();
  if (!empty($addThis)) {
    $this->headScript()->appendFile('https://s7.addthis.com/js/250/addthis_widget.js?pub=' . urlencode($addThis));
  }
  $this->headScript()->appendFile('https://unpkg.com/share-api-polyfill/dist/share-min.js');
?>
<nav class="record-nav" aria-label="<?=$this->transEscAttr('ajaxview_label_tools'); ?>">
  <ul class="nav nav-pills nav-stacked">
    <?php if (count($this->driver->getCitationFormats()) > 0): ?>
      <li role="none">
        <a class="cite-record" data-lightbox href="<?=$this->escapeHtmlAttr($this->recordLinker()->getActionUrl($this->driver, 'Cite'))?>" rel="nofollow">
          <?=$this->icon('cite', 'icon-link__icon') ?>
          <span class="icon-link__label"><?=$this->transEsc('Cite this')?></span>
        </a>
      </li>
    <?php endif; ?>

    <?php if ($this->accountCapabilities()->getSmsSetting() !== 'disabled'): ?>
      <li role="none">
        <a class="sms-record" data-lightbox href="<?=$this->escapeHtmlAttr($this->recordLinker()->getActionUrl($this->driver, 'SMS'))?>" rel="nofollow">
          <?=$this->icon('send-sms', 'icon-link__icon') ?>
          <span class="icon-link__label"><?=$this->transEsc('Text this')?></span>
        </a>
      </li>
    <?php endif; ?>

    <li role="none">
      <a class="mail-record" data-lightbox href="<?=$this->escapeHtmlAttr($this->recordLinker()->getActionUrl($this->driver, 'Email'))?>" rel="nofollow">
        <?=$this->icon('send-email', 'icon-link__icon') ?>
        <span class="icon-link__label"><?=$this->transEsc('Email this')?></span>
      </a>
    </li>

    <?php $exportFormats = $this->export()->getFormatsForRecord($this->driver); ?>
    <?php if (count($exportFormats) > 0): ?>
       <li role="none" class="dropdown">
         <a class="export-toggle dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" href="<?=$this->escapeHtmlAttr($this->recordLinker()->getActionUrl($this->driver, 'Export'))?>" rel="nofollow" aria-expanded="false" aria-controls="export-options">
          <?=$this->icon('export', 'icon-link__icon') ?>
          <span class="icon-link__label"><?=$this->transEsc('Export Record') ?></span>
        </a>
        <ul class="dropdown-menu" id="export-options" role="menu">
          <?php foreach ($exportFormats as $exportFormat): ?>
            <li role="none">
              <a class="dropdown-item" <?php if ($this->export()->needsRedirect($exportFormat)): ?>target="<?=$this->escapeHtmlAttr($exportFormat)?>Main" <?php endif; ?>href="<?=$this->escapeHtmlAttr($this->recordLinker()->getActionUrl($this->driver, 'Export', [], '', ['excludeSearchId' => true]))?>?style=<?=$this->escapeHtmlAttr($exportFormat)?>" rel="nofollow" role="menuitem">
                <?=$this->transEsc('export_to', ['%%target%%' => $this->translate($this->export()->getLabelForFormat($exportFormat))])?>
              </a>
            </li>
          <?php endforeach; ?>
        </ul>
      </li>
    <?php endif; ?>

    <li role="none">
      <a class="permalink-record" data-lightbox href="<?=$this->escapeHtmlAttr($this->recordLinker()->getActionUrl($this->driver, 'Permalink'))?>" rel="nofollow">
        <?=$this->icon('external-link', 'icon-link__icon') ?>
        <span class="icon-link__label"><?=$this->transEsc('permanent_link')?></span>
      </a>
    </li>

    <?php if ($this->userlist()->getMode() !== 'disabled'): ?>
      <li role="none">
        <?php if ($this->permission()->allowDisplay('feature.Favorites')): ?>
          <a class="save-record" data-lightbox href="<?=$this->escapeHtmlAttr($this->recordLinker()->getActionUrl($this->driver, 'Save'))?>" rel="nofollow">
            <?=$this->icon('user-list-add', 'icon-link__icon') ?>
            <span class="icon-link__label"><?=$this->transEsc('Add to favorites')?></span>
          </a>
        <?php elseif ($block = $this->permission()->getAlternateContent('feature.Favorites')): ?>
          <?=$block ?>
        <?php endif; ?>
      </li>
    <?php endif; ?>
    <?php if (!empty($addThis)): ?>
      <li role="none">
        <a class="addThis addthis_button" href="https://www.addthis.com/bookmark.php?v=250&amp;pub=<?=urlencode($addThis)?>">
          <?=$this->icon('addthis-bookmark', 'icon-link__icon') ?>
          <span class="icon-link__label"><?=$this->transEsc('Bookmark')?></span>
        </a>
      </li>
    <?php endif; ?>

    <li role="none">
      <a class="share-record">
        <?=$this->icon('share-record', 'icon-link__icon') ?>
        <span class="icon-link__label"><?=$this->transEsc('share_btn_text')?></span>
      </a>
    </li>

    <?php $cart = $this->cart(); ?>
    <?php if ($cart->isActive()): ?>
    <?php $cartId = $this->driver->getSourceIdentifier() . '|' . $this->driver->getUniqueId(); ?>
      <span class="btn-bookbag-toggle" data-cart-id="<?=$this->escapeHtmlAttr($this->driver->getUniqueId())?>" data-cart-source="<?=$this->escapeHtmlAttr($this->driver->getSourceIdentifier())?>">
        <a href="#" class="cart-add hidden<?php if(!$cart->contains($cartId)): ?> correct<?php endif ?>">
          <span class="cart-link-label"><?=$this->icon('cart-add', 'icon-link__icon fa-fw') ?> <span class="icon-link__label"><?=$this->transEsc('Add to Book Bag') ?></span></span>
        </a>
        <a href="#" class="cart-remove hidden<?php if($cart->contains($cartId)): ?> correct<?php endif ?>">
          <span class="cart-link-label"><?=$this->icon('cart-remove', 'icon-link__icon fa-fw') ?> <span class="icon-link__label"><?=$this->transEsc('Remove from Book Bag') ?></span></span>
        </a>
        <noscript>
          <form method="post" name="addForm" action="<?=$this->url('cart-processor')?>">
            <input type="hidden" name="ids[]" value="<?=$this->escapeHtmlAttr($cartId)?>">
            <?php if ($cart->contains($cartId)): ?>
              <input class="btn btn-default" type="submit" name="delete" value="<?=$this->transEscAttr('Remove from Book Bag')?>">
            <?php else: ?>
              <input class="btn btn-default" type="submit" name="add" value="<?=$this->transEscAttr('Add to Book Bag')?>">
            <?php endif; ?>
          </form>
        </noscript>
      </span>
    <?php endif; ?>

  </ul>
</nav>

<?php
$title = $this->escapeJs($this->driver->getTitle());
$text = $this->driver->getSummary();
$text = isset($text[0]) ? $this->escapeJs($text[0]) : '';
$url = $this->escapeJs($this->serverUrl() . $this->recordLinker()->getUrl($this->driver));
$language = $this->escapeJs($this->layout()->userLang);
$js = <<<JS
    const shareData = {
      title: '$title',
      text: '$text',
      url: '$url'
    }
    const polyfillSettings = {
        copy: false,
        email: true,
        print: true,
        sms: false,
        messenger: true,
        facebook: true,
        whatsapp: true,
        twitter: true,
        linkedin: false,
        telegram: false,
        skype: false,
        pinterest: false,
        language: '$language'
      }
    const link = document.querySelector('.share-record');

    link.addEventListener('click', async () => {
        await navigator.share(shareData, polyfillSettings);
    });
    JS;
?>
<?=$this->inlineScript(\Laminas\View\Helper\HeadScript::SCRIPT, $js, 'SET')?>

