# Key is the field name that can be requested. It has the following subkeys:
# - vufind.method: name to call (either in the SearchApiController class or the record driver)
# - vufind.default: true if the field is displayed by default when the request does not specify fields
# - OpenAPI 3 specification fields describing the returned data.
#
# See https://spec.openapis.org/oas/v3.0.3 for information on the format.
#
id:
  vufind.default: true
  description: Item identifier
  type: string
availability:
  vufind.default: true
  description: General availability information
  type: string
  enum:
    - available
    - on-loan
    - unavailable
    - unknown
availability_note:
  vufind.default: true
  description: Availability description
  type: string
duedate:
  vufind.default: true
  description: Due date if item is checked out
  type: string
opac_status:
  vufind.default: true
  description: Loan status
  type: string
location:
  description: Location
  type: string
ext:
  description: Extended information (for backwards compatibility)
  type: object
  properties:
    opac_status:
      description: Loan status
      type: string
