AllLibraries:
  DismaxFields:
    - name_search_txt^500
    - name_alt_search_txt_mv^400
    - code_search_txt^300
    - town_search_txt^100
    - address_search_txt_mv
    - note_search_txt
    - type_search_txt_mv
    - function_search_txt_mv
    - responsibility_search_txt_mv
    - services_search_txt_mv
    - projects_search_txt_mv
    - note2_search_txt
    - branch_search_txt
    - sigla_search_txt
    - cpk_code_search_txt
  FilterQuery: "recordtype:library"
  DismaxParams:
    - [bf, ord(library_relevance_str)^9999]
    - [bq, "inspiration:top_results^1"]
  DismaxHandler: edismax

Name:
  DismaxFields:
    - name_search_txt^150
    - name_alt_search_txt_mv^50
  FilterQuery: "recordtype:library"
  DismaxParams:
    - [bf, ord(library_relevance_str)^9999]
  DismaxHandler: edismax

Town:
  DismaxFields:
    - town_search_txt^100
    - address_search_txt_mv
  FilterQuery: "recordtype:library"
  DismaxParams:
    - [bf, ord(library_relevance_str)^9999]
  DismaxHandler: edismax

Sigla:
  DismaxFields:
    - sigla_search_txt
  FilterQuery: "recordtype:library"
  DismaxParams:
    - [bf, ord(library_relevance_str)^9999]
  DismaxHandler: edismax

People:
  DismaxFields:
    - responsibility_search_txt_mv
  FilterQuery: "recordtype:library"
  DismaxParams:
    - [bf, ord(library_relevance_str)^9999]
  DismaxHandler: edismax

adv_search_type:
  DismaxFields:
    - type_search_txt_mv
  FilterQuery: "recordtype:library"
  DismaxParams:
    - [bf, ord(library_relevance_str)^9999]
  DismaxHandler: edismax

adv_search_function:
  DismaxFields:
    - function_search_txt_mv
  FilterQuery: "recordtype:library"
  DismaxParams:
    - [bf, ord(library_relevance_str)^9999]
  DismaxHandler: edismax

adv_search_services:
  DismaxFields:
    - services_search_txt_mv
  FilterQuery: "recordtype:library"
  DismaxParams:
    - [bf, ord(library_relevance_str)^9999]
  DismaxHandler: edismax

adv_search_projects:
  DismaxFields:
    - projects_search_txt_mv
  FilterQuery: "recordtype:library"
  DismaxParams:
    - [bf, ord(library_relevance_str)^9999]
  DismaxHandler: edismax
