<?php
  $user = $this->auth()->isLoggedIn();
  $cardsSources = $user ? $user->getLibraryPrefixes() : [];
?>
<div class="alert alert-info <?=$this->class ?? ''?>">
  <?=$this->transEsc($this->mainMessage)?>
  <?php
  $deduplicatedRecords = $this->driver->tryMethod('getDeduplicatedRecords') ?? [];
  $records = array_filter($deduplicatedRecords, function ($record) use ($cardsSources) {
    return in_array($record['source'] ?? null, $cardsSources);
  });
  $availableRecords = array_map(function ($record) {
    return [
      'label' => $this->translate('Source::' . $record['source']),
      'url' => $this->recordLinker()->getUrl($record['id']),
    ];
  }, $records);
  ?>
  <?php if (!empty($availableRecords)): ?>
    <?=$this->transEsc('hold_available_in_other_libraries');?>
    <ul>
      <?php foreach($availableRecords as $ar): ?>
        <li><a href="<?=$ar['url']?>"><?=$ar['label']?></a></li>
      <?php endforeach; ?>
    </ul>
  <?php endif; ?>
  <?php if ($this->driver->tryMethod('getZiskejBoolean') ?? false): ?>
    <?=$this->translate("hold_available_in_ziskej", ['%%url%%' => $this->escapeHtmlAttr($this->recordLinker()->getTabUrl($this->driver, 'ZiskejMvs') . '#tabnav')])?>
  <?php endif;?>
</div>
