<?php
  $user = $this->auth()->getUserObject();
  $cardsSources = $user != null ? $user->getLibraryPrefixes() : [];
?>
<div class="alert alert-info <?=$this->class ?? ''?>">
  <?=$this->transEsc($this->mainMessage)?>
  <?php
  $availableRecords = [];
  $deduplicatedRecords = $this->driver->tryMethod('getDeduplicatedRecords') ?? [];
  foreach ($deduplicatedRecords as $source => $ids) {
    if (in_array($source, $cardsSources)) {
      foreach ($ids as $id) {
        if ($id != $this->driver->getUniqueID()) {
          $availableRecords[] = [
            'label' => $this->translate('Source::' . $source),
            'url' => $this->recordLinker()->getUrl($id),
          ];
        }
      }
    }
  }
  ?>
  <?php if (!empty($availableRecords)): ?>
    <?=$this->transEsc('hold_available_in_other_libraries');?>
    <ul>
      <?php foreach ($availableRecords as $ar): ?>
        <li><a href="<?=$ar['url']?>"><?=$ar['label']?></a></li>
      <?php endforeach; ?>
    </ul>
  <?php endif; ?>
  <?php if ($this->driver->tryMethod('getZiskejBoolean') ?? false): ?>
    <?=$this->translate('hold_available_in_ziskej', ['%%url%%' => $this->escapeHtmlAttr($this->recordLinker()->getTabUrl($this->driver, 'ZiskejMvs') . '#tabnav')])?>
  <?php endif;?>
</div>
