<?php
  // Set page title.
  $this->headTitle($this->translate('Institutions') . ': ' . $this->driver->getBreadcrumb());
  $records = $this->driver->tryMethod('getDeduplicatedRecords') ?? [];
?>
<?php if(!empty($records)): ?>
  <?php foreach ($records as $record): ?>
    <li>
      <a class="hover-overlay" href="<?=$this->escapeHtmlAttr($this->recordLinker()->getUrl($record['id']))?>">
        <?=$this->transEsc('Source::' . $record['source'])?>
      </a>
    </li>
  <?php endforeach; ?>
<?php endif;
