<ul>
  <?php foreach ($this->itemLinks as $itemLink):?>
    <?php
      $title = $itemLink['title'] ?? $itemLink['label'];
    ?>
    <li>
      <?php if (isset($itemLink['recordId'])):?>
        <a href="<?=$this->escapeHtmlAttr($this->recordLinker()->getUrl($itemLink['recordId']))?>">
          <?=$this->escapeHtml($title)?>
        </a>
      <?php else:?>
        <?=$this->escapeHtml($title)?>
      <?php endif;?>
    </li>
  <?php endforeach;?>
</ul>
