<?php
    // Set page title.
    $this->headTitle($this->translate('Services, projects and function') . ': ' . $this->driver->getBreadcrumb());
?>

<!-- Services -->
<?php $services = $this->driver->getService(); if (!empty($services)): ?>
    <h2><i class="fa fa-circle-thin"></i> <?=$this->translate('Services')?></h2>
    <ul>
        <?php foreach ($services as $service): ?><li><?=$this->escapeHtml($service)?></li><?php endforeach; ?>
    </ul>
<?php endif; ?>

<!-- Functions -->
<?php $functions = $this->driver->getFunction(); if (!empty($functions)): ?>
    <h2><i class="fa fa-circle-thin"></i> <?=$this->translate('Functions')?></h2>
    <ul>
        <?php foreach ($functions as $function): ?><li><?=$this->escapeHtml($function)?></li><?php endforeach; ?>
    </ul>
<?php endif; ?>

<!-- Projects -->
<?php $projects = $this->driver->getProject(); if (!empty($projects)): ?>
    <h2><i class="fa fa-circle-thin"></i> <?=$this->translate('Projects')?></h2>
    <ul>
        <?php foreach ($projects as $project): ?><li><?=$this->escapeHtml($project)?></li><?php endforeach; ?>
    </ul>
<?php endif; ?>
