<?php
    // Set page title.
    $this->headTitle($this->translate('Contacts') . ': ' . $this->driver->getBreadcrumb());
?>

<!-- Phones-->
<?php $phones = $this->driver->getPhone(); if (!empty($phones)): ?>
    <h2><i class="pr-communication-phonecall"></i> <?=$this->translate('Telephone')?></h2>
    <?php foreach ($phones as $phone): ?><?=$this->escapeHtml($phone)?><br/><?php endforeach; ?>
<?php endif; ?>

<!-- Emails-->
<?php $emailes = $this->driver->getEmail(); if (!empty($emailes)): ?>
    <h2><i class="pr-communication-emailenvelope"></i> <?=$this->translate('E-mail')?></h2>
    <?php foreach ($emailes as $email): ?><?=$this->escapeHtml($email)?><br/><?php endforeach; ?>
<?php endif; ?>

<!-- LibResponsibility-->
<?php $libresponsibilities = $this->driver->getLibResponsibility(); if (!empty($libresponsibilities)): ?>
    <h2><i class="pr-interface-circlerighttrue"></i> <?=$this->translate('LibResponsibility')?></h2>
    <?php foreach ($libresponsibilities as $libresponsibility): ?><?=$this->escapeHtml($libresponsibility)?><br/><?php endforeach; ?>
<?php endif; ?>
