<?php
    // Set page title.
    $this->headTitle($this->translate('Contacts') . ': ' . $this->driver->getBreadcrumb());
?>

<!-- Phones-->
<?php $phones = $this->driver->getPhone(); if (!empty($phones)): ?>
    <h2><i class="fa fa-phone"></i> <?=$this->translate('Telephone')?></h2>
    <?php foreach ($phones as $phone): ?><?=$this->escapeHtml($phone)?><br/><?php endforeach; ?>
<?php endif; ?>

<!-- Emails-->
<?php $emailes = $this->driver->getEmail(); if (!empty($emailes)): ?>
    <h2><i class="fa fa-envelope-o"></i> <?=$this->translate('E-mail')?></h2>
    <?php foreach ($emailes as $email): ?><a href="mailto:<?=$this->escapeHtmlAttr($email)?>"><?=$this->escapeHtml($email)?></a><br/><?php endforeach; ?>
<?php endif; ?>

<!-- ISDS-->
<?php $isds = $this->driver->getIsds(); if (!empty($isds)): ?>
  <h2><i class="fa fa-envelope-o"></i> <?=$this->translate('databox')?></h2>
  <?php foreach ($isds as $isd): ?><a href="<?=$this->escapeHtmlAttr($isd['url'])?>"><?=$this->escapeHtml($isd['value'])?></a><br/><?php endforeach; ?>
<?php endif; ?>

<!-- LibResponsibility-->
<?php $libresponsibilities = $this->driver->getLibResponsibility(); if (!empty($libresponsibilities)): ?>
    <h2><i class="fa fa-circle-thin"></i> <?=$this->translate('LibResponsibility')?></h2>
    <?php foreach ($libresponsibilities as $libresponsibility): ?><?=$this->escapeHtml($libresponsibility)?><br/><?php endforeach; ?>
<?php endif; ?>
