<?php
  // Set page title.
  $this->headTitle($this->translate('Branches') . ': ' . $this->driver->getBreadcrumb());
?>
<!-- BranchUrl-->
<?php $branchurls = $this->driver->getBranchUrl(); if (!empty($branchurls)): ?>
  <h2><i class="fa fa-circle-thin"></i> <?=$this->translate('Branch info')?></h2>
  <?php foreach ($branchurls as $branchurl): ?>
    <p><a href="<?=$this->escapeHtml($branchurl)?>" target="_blank"><?=$this->escapeHtml($branchurl)?></a></p>
  <?php endforeach; ?>
<?php endif; ?>

<!-- Branches-->
<?php $branches = $this->driver->getBranches(); if (!empty($branches)): ?>
  <h2><i class="fa fa-home"></i> <?=$this->translate('Departments')?></h2>
  <?php foreach ($branches as $branch): ?>
    <h3><?=$this->escapeHtml($branch['title'])?></h3>
    <ul>
      <?php foreach(['address', 'town', 'gps_display'] as $field):?>
        <?php if (($item = $branch[$field] ?? null) != null):?>
          <li><?=$this->escapeHtml($item)?></li>
        <?php endif; ?>
      <?php endforeach; ?>
    </ul>
  <?php endforeach; ?>
<?php endif;
