<?php
  // Set page title.
  $this->headTitle($this->driver->getBreadcrumb());
?>

<?php $sigla = $this->driver->getSigla(); if (!empty($sigla)): ?>
    <h2><i class="pr-interface-circlerighttrue"></i><?=$this->translate('Sigla')?></h2>
    <p><?=$this->escapeHtml($sigla)?></p>
<?php endif; ?>

<?php $lastupdated = $this->driver->getLastUpdated(); if (!empty($lastupdated)): ?>
    <h2><i class="pr-interface-circlerighttrue"></i><?=$this->translate('LastUpdated')?></h2>
    <p><?=$this->escapeHtml($lastupdated)?></p>
<? endif; ?>