<?php
  // Set page title.
  $this->headTitle($this->translate('Branches') . ': ' . $this->driver->getBreadcrumb());
?>
<!-- BranchUrl-->
<?php $branchurls = $this->driver->getBranchUrl(); if (!empty($branchurls)): ?>
    <h2><i class="pr-interface-circlerighttrue"></i> <?=$this->translate('Branch info')?></h2>
    <?php foreach ($branchurls as $branchurl): ?>
        <p><a href="<?=$this->escapeHtml($branchurl)?>" target="_blank"><?=$this->escapeHtml($branchurl)?></a></p>
    <?php endforeach; ?>
<?php endif; ?>

<!-- Branches-->
<?php $branches = $this->driver->getLibBranch(); if (!empty($branches)): ?>
    <h2><i class="pr-interface-househome"></i> <?=$this->translate('Departments')?></h2>
    <?php foreach ($branches as $branch): ?>
        <?php $branchInfo = explode('|', $branch);?>
            <?php $branchName = array_shift($branchInfo);?>
            <h3><?=$branchName?></h3>
            <?php if (!empty($branchInfo)):?>
                <ul>
                <?php foreach ($branchInfo as $infoItem):?>
                    <li><?=$this->escapeHtml($infoItem)?></li>
                <?php endforeach; ?>
                </ul>
            <?php endif; ?>
    <?php endforeach; ?>
<?php endif;
