<?php
/**
 * @var \KnihovnyCz\RecordTab\ZiskejEdd $tab
 */
$tab = $this->tab;

/**
 * @var \KnihovnyCz\RecordDriver\SolrLocal $driver
 */
$driver = $this->driver;

/**
 * @var \KnihovnyCz\View\Helper\KnihovnyCz\ZiskejEdd $ziskejViewHelper
 */
$ziskejViewHelper = $this->ziskejEdd();

/**
 * @var ?\KnihovnyCz\Db\Row\User $user
 */
$user = $this->auth()->isLoggedIn();

/**
 * @var \KnihovnyCz\Ziskej\ZiskejEdd $ziskejEdd
 */
$ziskejEdd = $tab->getZiskejEdd();

/**
 * @var string[] $dedupedRecordIds
 */
$dedupedRecordIds = $tab->getDedupedRecordIds();
?>
<?php if ($ziskejViewHelper->isEnabled()): ?>

  <?php if (!$user): ?>
    <div class="alert alert-info">
      <?php $loginUrl = $this->escapeHtmlAttr($this->recordLinker()->getTabUrl($this->driver, 'ZiskejEdd', ['login' => 'true'])); ?>
      <?=$this->translate('Ziskej::alert_not_logged_in', ['%%url%%' => $loginUrl])?>
    </div>
  <?php endif; ?>

  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title"><?=$this->translate('ZiskejEdd::service_header') ?></h3>
    </div>
    <div class="panel-body">
      <div class="col-md-9">
        <p><?=$this->translate('ZiskejEdd::service_description') ?></p>
      </div>
      <div class="col-md-3">
        <?php if (!empty($ziskejEdd->getCurrentZiskejTechlibFrontUrl())): ?>
          <form action="<?=$ziskejEdd->getCurrentZiskejTechlibFrontUrl() ?>/ticket_create" id="ziskejEddButton" method="post" target="_blank">
            <input type="hidden" name="service" value="edd">
            <input type="hidden" name="edd_subtype" value="<?=$driver->getEddSubtype() ?>">
            <input type="hidden" name="source_id" value="<?=$this->escapeHtmlAttr($tab->getServerName()) ?>">
            <input type="hidden" name="doc_id" value="<?=$this->escapeHtmlAttr($driver->getUniqueID()) ?>">
            <input type="hidden" name="entity_id" value="<?=$this->escapeHtmlAttr($tab->getEntityId()) ?>">
            <?php foreach ($dedupedRecordIds as $id): ?>
              <input type="hidden" name="doc_alt_ids[]" value="<?=$this->escapeHtmlAttr($id) ?>">
            <?php endforeach; ?>
            <input type="image" src="<?=$this->imageLink('logo-ziskej.png') ?>" alt="<?=$this->translate('ZiskejEdd::service_name') ?>">
          </form>
        <?php else: ?>
          <?php if (!empty($ziskejEdd->getZiskejTechlibUrl())): ?>
            <a href="<?=$ziskejEdd->getZiskejTechlibUrl() ?>" target="_blank">
              <img src="<?=$this->imageLink('logo-ziskej.png') ?>" alt="<?=$this->translate('ZiskejEdd::service_name') ?>">
            </a>
          <?php endif; ?>
        <?php endif; ?>
      </div>
    </div>
  </div>

  <?php if ($user): ?>
    <div class="panel panel-default">
      <div class="panel-heading">
        <h4 class="panel-title"><?=$this->translate('ZiskejEdd::connected_libraries') ?></h4>
      </div>
      <div class="panel-body">
        <?php if ($tab->isZiskejActive()): ?>
          <?php
            $libs = [];
            try {
              $libs = $tab->getConnectedLibs();
            } catch (\Exception $e) {
          ?>
            <div class="alert alert-warning"><?=$this->transEsc("ZiskejEdd::alert_api_error") ?></div>
          <?php
            }
          ?>
          <?php if (!empty($libs)): ?>
            <ul class="list-group">
              <?php foreach ($libs as $libId => $data): ?>
                <?php
                /** @var \KnihovnyCz\Db\Row\UserCard $userCard */
                $userCard = $data['userCard'];
                /** @var \Mzk\ZiskejApi\ResponseModel\Reader $ziskejReader */
                $ziskejReader = $data['ziskejReader'];
                ?>
                <li class="list-group-item clearfix">
                  <?=$this->translate('Source::' . $libId) ?>
                  <span class="pull-right">
                    <a class="btn btn-primary ziskej-order-btn" data-lightbox href="<?=$this->url('ziskej-edd-order', ['id' => $driver->getUniqueId(), 'eppnDomain' => $userCard->getEppnDomain()]) ?>">
                      <?=$this->icon('ziskej-order')?> <?=$this->transEsc("ZiskejEdd::btn_order") ?>
                    </a>
                </span>
                </li>
              <?php endforeach; ?>
            </ul>
          <?php else: ?>
            <div class="alert alert-warning text-center">
              <?=$this->transEsc("ZiskejEdd::alert_no_connected_libraries") ?>
            </div>
          <?php endif; ?>
        <?php else: ?>
          <div class="alert alert-warning text-center">
            <?=$this->transEsc("ZiskejEdd::warning_api_disconnected") ?>
          </div>
        <?php endif; ?>
      </div>
    </div>
  <?php endif; ?>
<?php endif; ?>
