<?php
/** @var \KnihovnyCz\RecordTab\Ziskej $tab */
$tab = $this->tab;

/** @var KnihovnyCz\RecordDriver\SolrLocal $driver */
$driver = $this->driver;

/** @var ?\KnihovnyCz\Db\Row\User $user */
$user = $tab->getUser();

/** @var \KnihovnyCz\Ziskej\ZiskejMvs $ziskejMvs */
$ziskejMvs = $tab->getZiskejMvs();

/** @var string[][] $deduperRecords
 */
$deduperRecords = $tab->getDeduperRecords();

?>
<?php if ($this->Ziskej()->isEnabled()): ?>
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title"><?=$this->translate('ziskej_desc_header') ?></h3>
    </div>
    <div class="panel-body">
      <div class="col-md-9">
        <p><?=$this->translate('ziskej_desc') ?></p>
        <p><?=$this->translate('ziskej_price') ?></p>
      </div>
      <div class="col-md-3">
        <?php if ($ziskejMvs->getCurrentZiskejTechlibFrontUrl()): ?>
          <form action="<?=$ziskejMvs->getCurrentZiskejTechlibFrontUrl() ?>/ticket_create" id="mvs" method="post" target="_blank">
            <input type="hidden" name="service" value="mvs">
            <input type="hidden" name="source_id" value="<?=$this->escapeHtmlAttr($tab->getServerName()) ?>">
            <input type="hidden" name="user_id" value="<?=$this->escapeHtmlAttr('') ?>">
            <input type="hidden" name="doc_id" value="<?=$this->escapeHtmlAttr($driver->getUniqueID()) ?>">
            <input type="hidden" name="entity_id" value="<?=$this->escapeHtmlAttr($tab->getEntityId()) ?>">
            <?php foreach ($deduperRecords as $record): ?>
              <input type="hidden" name="doc_alt_ids[]" value="<?=$this->escapeHtmlAttr($record['id']) ?>">
            <?php endforeach; ?>
            <input type="image" src="<?=$this->imageLink('logo-ziskej.png') ?>" alt="<?=$this->translate('ziskej') ?>">
          </form>
        <?php else: ?>
          <?php if (!empty($ziskejMvs->getZiskejTechlibUrl())): ?>
            <a href="<?=$ziskejMvs->getZiskejTechlibUrl() ?>" target="_blank">
              <img src="<?=$this->imageLink('logo-ziskej.png') ?>" alt="<?=$this->translate('ziskej') ?>">
            </a>
          <?php endif; ?>
        <?php endif; ?>
      </div>
    </div>
  </div>


  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title"><?=$this->translate('ziskej_users_connected_libraries') ?></h4>
    </div>
    <div class="panel-body">
      <?php if ($user): ?>
        <?php if ($tab->isZiskejActive()): ?>
          <?php if (!empty($tab->getConnectedLibs())): ?>
            <ul class="list-group">
              <?php foreach ($tab->getConnectedLibs() as $libId => $data): ?>
                <?php
                /** @var \KnihovnyCz\Db\Row\UserCard $userCard */
                $userCard = $data['userCard'];
                /** @var \Mzk\ZiskejApi\ResponseModel\Reader $ziskejReader */
                $ziskejReader = $data['ziskejReader'];
                ?>
                <li class="list-group-item clearfix">
                  <?=$this->translate('source_' . $libId) ?>
                  <span class="pull-right">
                    <a class="btn btn-primary ziskej-order-btn" data-lightbox href="<?=$this->url('ziskejOrder', ['id' => $driver->getUniqueId(), 'eppnDomain' => $userCard->getEppnDomain()]) ?>">
                      <i class="fa fa-shopping-cart"></i> <?=$this->transEsc("ziskej_btn_order") ?>
                    </a>
                </span>
                </li>
              <?php endforeach; ?>
            </ul>
          <?php else: ?>
            <div class="alert alert-warning text-center">
              <?=$this->transEsc("ziskej_alert_no_connected_libraries") ?>
            </div>
          <?php endif; ?>
        <?php else: ?>
          <div class="alert alert-warning text-center">
            <?=$this->transEsc("ziskej_warning_api_disconnected") ?>
          </div>
        <?php endif; ?>
      <?php else: ?>
        <div class="text-center">
          <div class="alert alert-info text-center">
            <?=$this->transEsc("ziskej_alert_not_logged_in") ?>
          </div>
          <a class="btn btn-default" href="<?=$this->url('myresearch-userlogin')?>">
            <i class="fa fa-sign-in"></i>
            <?=$this->transEsc("Institutional Login") ?>
          </a>
        </div>
      <?php endif; ?>
    </div>
  </div>
<?php endif; ?>
