<?php
/**
 * @var \KnihovnyCz\RecordTab\ZiskejMvs $tab
 */
$tab = $this->tab;

/**
 * @var KnihovnyCz\RecordDriver\SolrLocal $driver
 */
$driver = $this->driver;

/**
 * @var \KnihovnyCz\View\Helper\KnihovnyCz\ZiskejMvs $ziskejViewHelper
 */
$ziskejViewHelper = $this->ziskejMvs();

/**
 * @var ?\KnihovnyCz\Db\Row\User $user
 */
$user = $this->auth()->isLoggedIn();

/** @var \KnihovnyCz\Ziskej\ZiskejMvs $ziskejMvs */
$ziskejMvs = $tab->getZiskejMvs();

/**
 * @var string[] $dedupedRecordIds
 */
$dedupedRecordIds = $tab->getDedupedRecordIds();
?>
<?php if ($ziskejViewHelper->isEnabled()): ?>
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title"><?=$this->translate('Ziskej::service_header') ?></h3>
    </div>
    <div class="panel-body">
      <div class="col-md-9">
        <p><?=$this->translate('Ziskej::service_description') ?></p>
        <p><?=$this->translate('Ziskej::service_price') ?></p>
      </div>
      <div class="col-md-3">
        <?php if ($ziskejMvs->getCurrentZiskejTechlibFrontUrl()): ?>
          <form action="<?=$ziskejMvs->getCurrentZiskejTechlibFrontUrl() ?>/ticket_create" id="mvs" method="post" target="_blank">
            <input type="hidden" name="service" value="mvs">
            <input type="hidden" name="source_id" value="<?=$this->escapeHtmlAttr($tab->getServerName()) ?>">
            <input type="hidden" name="user_id" value="<?=$this->escapeHtmlAttr('') ?>">
            <input type="hidden" name="doc_id" value="<?=$this->escapeHtmlAttr($driver->getUniqueID()) ?>">
            <input type="hidden" name="entity_id" value="<?=$this->escapeHtmlAttr($tab->getEntityId()) ?>">
            <?php foreach ($dedupedRecordIds as $id): ?>
              <input type="hidden" name="doc_alt_ids[]" value="<?=$this->escapeHtmlAttr($id) ?>">
            <?php endforeach; ?>
            <input type="image" src="<?=$this->imageLink('logo-ziskej.png') ?>" alt="<?=$this->translate('Ziskej::service_name') ?>">
          </form>
        <?php else: ?>
          <?php if (!empty($ziskejMvs->getZiskejTechlibUrl())): ?>
            <a href="<?=$ziskejMvs->getZiskejTechlibUrl() ?>" target="_blank">
              <img src="<?=$this->imageLink('logo-ziskej.png') ?>" alt="<?=$this->translate('Ziskej::service_name') ?>">
            </a>
          <?php endif; ?>
        <?php endif; ?>
      </div>
    </div>
  </div>


  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title"><?=$this->translate('Ziskej::connected_libraries') ?></h4>
    </div>
    <div class="panel-body">
      <?php if ($user): ?>
        <?php if ($tab->isZiskejActive()): ?>
          <?php if (!empty($tab->getConnectedLibs())): ?>
            <ul class="list-group">
              <?php foreach ($tab->getConnectedLibs() as $libId => $data): ?>
                <?php
                /** @var \KnihovnyCz\Db\Row\UserCard $userCard */
                $userCard = $data['userCard'];
                /** @var \Mzk\ZiskejApi\ResponseModel\Reader $ziskejReader */
                $ziskejReader = $data['ziskejReader'];
                ?>
                <li class="list-group-item clearfix">
                  <?=$this->translate('Source::' . $libId) ?>
                  <span class="pull-right">
                    <a class="btn btn-primary ziskej-order-btn" data-lightbox href="<?=$this->url('ziskej-order', ['id' => $driver->getUniqueId(), 'eppnDomain' => $userCard->getEppnDomain()]) ?>">
                      <i class="fa fa-shopping-cart"></i> <?=$this->transEsc("Ziskej::btn_order") ?>
                    </a>
                </span>
                </li>
              <?php endforeach; ?>
            </ul>
          <?php else: ?>
            <div class="alert alert-warning text-center">
              <?=$this->transEsc("Ziskej::alert_no_connected_libraries") ?>
            </div>
          <?php endif; ?>
        <?php else: ?>
          <div class="alert alert-warning text-center">
            <?=$this->transEsc("Ziskej::warning_api_disconnected") ?>
          </div>
        <?php endif; ?>
      <?php else: ?>
        <div class="text-center">
          <div class="alert alert-info text-center">
            <?=$this->transEsc("Ziskej::alert_not_logged_in") ?>
          </div>
          <a class="btn btn-default" href="<?=$this->url('myresearch-userlogin')?>">
            <i class="fa fa-sign-in"></i>
            <?=$this->transEsc("Institutional Login") ?>
          </a>
        </div>
      <?php endif; ?>
    </div>
  </div>
<?php endif; ?>
