<?php
/**
 * @var \KnihovnyCz\RecordTab\ZiskejMvs $tab
 */
$tab = $this->tab;

/**
 * @var \KnihovnyCz\RecordDriver\SolrLocal $driver
 */
$driver = $this->driver;

/**
 * @var \KnihovnyCz\View\Helper\KnihovnyCz\ZiskejMvs $ziskejViewHelper
 */
$ziskejViewHelper = $this->ziskejMvs();

/**
 * @var ?\KnihovnyCz\Db\Row\User $user
 */
$user = $this->auth()->getUserObject();

/**
 * @var \KnihovnyCz\Ziskej\ZiskejMvs $ziskejMvs
 */
$ziskejMvs = $tab->getZiskejMvs();

/**
 * @var string[] $dedupedRecordIds
 */
$dedupedRecordIds = $tab->getDedupedRecordIds();
?>
<?php if ($ziskejViewHelper->isEnabled()): ?>

  <?php if ($tab->isApiDown()): ?>
    <div class="alert alert-danger text-center" role="alert">
      <?=$this->icon('ziskej-warning') ?>
      <?=$this->translate('ziskej_service_not_available') ?>
    </div>
  <?php endif; ?>

  <?php if ($user == null): ?>
    <div class="alert alert-info">
      <?php $loginUrl = $this->escapeHtmlAttr($this->recordLinker()->getTabUrl($this->driver, 'ZiskejMvs', ['login' => 'true'])); ?>
      <?=$this->translate('Ziskej::alert_not_logged_in', ['%%url%%' => $loginUrl])?>
    </div>
  <?php endif; ?>

  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title"><?=$this->translate('ZiskejMvs::service_header') ?></h3>
    </div>
    <div class="panel-body">
      <div class="col-md-9">
        <p><?=$this->translate('ZiskejMvs::service_description') ?></p>
        <p><?=$this->translate('ZiskejMvs::service_price') ?></p>
      </div>
      <div class="col-md-3">
        <?php if ($ziskejMvs->getCurrentZiskejTechlibFrontUrl()): ?>
          <form action="<?=$ziskejMvs->getCurrentZiskejTechlibFrontUrl() ?>/ticket_create" id="mvs" method="post" target="_blank">
            <input type="hidden" name="service" value="mvs">
            <input type="hidden" name="source_id" value="<?=$this->escapeHtmlAttr($tab->getServerName()) ?>">
            <input type="hidden" name="user_id" value="<?=$this->escapeHtmlAttr('') ?>">
            <input type="hidden" name="doc_id" value="<?=$this->escapeHtmlAttr($driver->getUniqueID()) ?>">
            <input type="hidden" name="entity_id" value="<?=$this->escapeHtmlAttr($tab->getEntityId()) ?>">
            <?php foreach ($dedupedRecordIds as $id): ?>
              <input type="hidden" name="doc_alt_ids[]" value="<?=$this->escapeHtmlAttr($id) ?>">
            <?php endforeach; ?>
            <input type="image" src="<?=$this->imageLink('logo-ziskej.png') ?>" alt="<?=$this->translate('ZiskejMvs::service_name') ?>">
          </form>
        <?php else: ?>
          <?php if (!empty($ziskejMvs->getZiskejTechlibUrl())): ?>
            <a href="<?=$ziskejMvs->getZiskejTechlibUrl() ?>" target="_blank">
              <img src="<?=$this->imageLink('logo-ziskej.png') ?>" alt="<?=$this->translate('ZiskejMvs::service_name') ?>">
            </a>
          <?php endif; ?>
        <?php endif; ?>
      </div>
    </div>
  </div>

  <?php if ($user != null): ?>
    <div class="panel panel-default">
      <div class="panel-heading">
        <h4 class="panel-title"><?=$this->translate('ZiskejMvs::connected_libraries') ?></h4>
      </div>
      <div class="panel-body">
        <?php if ($tab->isZiskejActive()): ?>
          <?php
            $libs = [];
            try {
              $libs = $tab->getConnectedLibs();
            } catch (\Exception $e) {
          ?>
            <div class="alert alert-warning"><?=$this->transEsc('ZiskejMvs::alert_api_error') ?></div>
          <?php
            }
          ?>
          <?php if (!empty($libs)): ?>
            <ul class="list-group">
              <?php foreach ($tab->getConnectedLibs() as $libId => $data): ?>
                <?php
                /** @var \KnihovnyCz\Db\Row\UserCard $userCard */
                $userCard = $data['userCard'];
                /** @var \Mzk\ZiskejApi\ResponseModel\Reader $ziskejReader */
                $ziskejReader = $data['ziskejReader'];
                ?>
                <li class="list-group-item clearfix">
                  <?=$this->translate('Source::' . $libId) ?>
                  <span class="pull-right">
                    <a class="btn btn-primary ziskej-order-btn" data-lightbox href="<?=$this->url('ziskej-mvs-order', ['id' => $driver->getUniqueId(), 'eppnDomain' => $userCard->getEppnDomain()]) ?>">
                      <?=$this->icon('ziskej-order')?> <?=$this->transEsc('ZiskejMvs::btn_order') ?>
                    </a>
                </span>
                </li>
              <?php endforeach; ?>
            </ul>
          <?php else: ?>
            <div class="alert alert-warning text-center">
              <?=$this->transEsc('ZiskejMvs::alert_no_connected_libraries') ?>
            </div>
          <?php endif; ?>
        <?php else: ?>
          <div class="alert alert-warning text-center">
            <?=$this->transEsc('ZiskejMvs::warning_api_disconnected') ?>
          </div>
        <?php endif; ?>
      </div>
    </div>
  <?php endif; ?>
<?php endif; ?>
