<?=$this->flashmessages()?>
<?php
  $itemIndex = 1;
  $this->headScript()->appendFile('checkouts.js');
?>
<?php if (!empty($this->transactions)): ?>
  <nav class="search-header hidden-print">
    <?php if ($this->paginator): ?>
      <div class="search-stats">
        <?php
          $abs = $this->paginator->getAbsoluteItemNumber($this->paginator->getItemCountPerPage());
          $end = min($abs, $this->paginator->getTotalItemCount());
          $itemIndex = $this->paginator->getAbsoluteItemNumber(1);
          $transParams = [
            '%%start%%' => $this->localizedNumber($this->paginator->getAbsoluteItemNumber(1)),
            '%%end%%' => $this->localizedNumber($end),
            '%%total%%' => $this->localizedNumber($this->paginator->getTotalItemCount()),
          ];
        ?>
        <?=$this->translate('showing_items_of_html', $transParams); ?>
      </div>
    <?php endif; ?>
    <?php if ($this->sortList): ?>
      <?=$this->context($this)->renderInContext('myresearch/controls/sort.phtml', ['sortList' => $this->sortList]); ?>
    <?php endif; ?>
  </nav>

<?php if ($purgeAllAllowed || $purgeSelectedAllowed): ?>
<form name="purge_history" method="post" action="<?=$this->url('checkouts-purgehistory')?>" id="purge_history" data-disable-on-submit>
  <input type="hidden" id="submitType" name="purgeSelected" value="1">
  <input type="hidden" name="csrf" value="<?=$this->escapeHtmlAttr($this->auth()->getManager()->getCsrfHash())?>">
  <div class="toolbar">
    <div class="checkbox">
      <?php if ($purgeSelectedAllowed): ?>
        <label>
          <input type="checkbox" name="selectAll" class="checkbox-select-all"/>
          <?=$this->transEsc('select_page')?>
        </label>
        <div class="btn-group">
          <input type="submit" id="purgeSelected" name="purgeSelected" value="<?=$this->transEscAttr('loan_history_purge_selected')?>" class="btn btn-default dropdown-toggle" data-toggle="dropdown" data-lightbox-ignore>
          <ul class="dropdown-menu">
            <li class="disabled"><span class="prompt-text"><?=$this->transEsc('loan_history_confirm_purge_selected')?></span></li>
            <li><a href="#" id="confirm_purge_selected_yes"><?=$this->transEsc('confirm_dialog_yes')?></a></li>
            <li><a href="#" class="confirm_purge_no"><?=$this->transEsc('confirm_dialog_no')?></a></li>
          </ul>
        </div>
      <?php endif; ?>
      <?php if ($purgeAllAllowed): ?>
        <div class="btn-group">
          <input type="submit" id="purgeAll" name="purgeAll" value="<?=$this->transEscAttr('loan_history_purge_all')?>" class="btn btn-default dropdown-toggle" data-toggle="dropdown" data-lightbox-ignore>
          <ul class="dropdown-menu">
            <li class="disabled"><span class="prompt-text"><?=$this->transEsc('loan_history_confirm_purge_all')?></span></li>
            <li><a href="#" id="confirm_purge_all_yes"><?=$this->transEsc('confirm_dialog_yes')?></a></li>
            <li><a href="#" class="confirm_purge_no"><?=$this->transEsc('confirm_dialog_no')?></a></li>
          </ul>
        </div>
      <?php endif; ?>
    </div>
  </div>
  <?php endif; ?>

  <ul class="record-list">
    <?php $i = 0;
    foreach ($this->transactions as $resource): ?>
      <?php $ilsDetails = $resource->getExtraDetail('ils_details'); ?>
      <li id="record<?=$this->escapeHtmlAttr($resource->getUniqueId())?>" class="result">
        <?php if ($this->purgeSelectedAllowed): ?>
          <div class="checkbox">
            <?php if (isset($ilsDetails['row_id'])): ?>
              <?php $safeId = preg_replace('/[^a-zA-Z0-9]/', '', $ilsDetails['row_id']); ?>
              <label>
                <input class="checkbox-select-item" type="checkbox" name="purgeSelectedIDs[]" value="<?=$this->escapeHtmlAttr($ilsDetails['row_id'])?>" id="checkbox_<?=$safeId?>" />
              </label>
            <?php else: ?>
              <label> </label>
            <?php endif; ?>
          </div>
        <?php endif; ?>
        <strong class="pull-left order"><?= $itemIndex++ ?>.</strong>
        <?php
          $coverDetails = $this->record($resource)->getCoverDetails('checkedout', 'small', $this->recordLinker()->getUrl($resource));
          $cover = $coverDetails['html'];
          $thumbnail = false;
          $thumbnailAlignment = $this->record($resource)->getThumbnailAlignment('account');
          if ($cover):
            ob_start(); ?>
            <div class="media-<?=$thumbnailAlignment ?> <?=$this->escapeHtmlAttr($coverDetails['size'])?>">
              <?=$cover ?>
            </div>
            <?php $thumbnail = ob_get_contents();
            ob_end_clean();
          endif; ?>
        <div class="media">
          <?php if ($thumbnail && $thumbnailAlignment == 'left'): ?>
            <?=$thumbnail ?>
          <?php endif ?>
          <div class="media-body">
            <?=$this->record($resource)->renderTemplate('account-entry.phtml')?>
            <?php if (!empty($ilsDetails['institution_name']) && (empty($ilsDetails['borrowingLocation']) || $ilsDetails['institution_name'] != $ilsDetails['borrowingLocation'])): ?>
              <strong><?=$this->transEscWithPrefix('location_', $ilsDetails['institution_name'])?></strong>
              <br>
            <?php endif; ?>

            <?php if (!empty($ilsDetails['borrowingLocation'])): ?>
              <strong><?=$this->transEsc('Borrowing Location')?>:</strong> <?=$this->transEscWithPrefix('location_', $ilsDetails['borrowingLocation'])?>
              <br>
            <?php endif; ?>

            <?php if (!empty($ilsDetails['checkoutDate'])): ?>
              <strong><?=$this->transEsc('Checkout Date')?>:</strong> <?=$this->escapeHtml($ilsDetails['checkoutDate'])?><?php if (isset($ilsDetails['checkoutTime'])): ?> <span class="checkout-time"><?=$this->escapeHtml($ilsDetails['checkoutTime'])?></span><?php endif; ?><br>
            <?php endif; ?>
            <?php if (!empty($ilsDetails['returnDate'])): ?>
              <strong><?=$this->transEsc('Return Date')?>:</strong> <?=$this->escapeHtml($ilsDetails['returnDate'])?><?php if (isset($ilsDetails['returnTime'])): ?> <span class="return-time"><?=$this->escapeHtml($ilsDetails['returnTime'])?></span><?php endif; ?><br>
            <?php endif; ?>
            <?php if (!empty($ilsDetails['dueDate'])): ?>
              <strong><?=$this->transEsc('Due Date')?>:</strong> <?=$this->escapeHtml($ilsDetails['dueDate'])?><?php if (isset($ilsDetails['dueTime'])): ?> <span class="due-time"><?=$this->escapeHtml($ilsDetails['dueTime'])?></span><?php endif; ?>
            <?php endif; ?>

            <?php if (isset($ilsDetails['message']) && !empty($ilsDetails['message'])): ?>
              <div class="alert alert-info"><?=$this->transEsc($ilsDetails['message'])?></div>
            <?php endif; ?>
          </div>
          <?php if ($thumbnail && $thumbnailAlignment == 'right'): ?>
            <?=$thumbnail ?>
          <?php endif ?>
        </div>
        <?=$resource->tryMethod('supportsCoinsOpenUrl') ? '<span class="Z3988" title="' . $this->escapeHtmlAttr($resource->getCoinsOpenUrl()) . '"></span>' : ''?>
      </li>
    <?php endforeach; ?>
  </ul>
  <?php if ($purgeAllAllowed || $purgeSelectedAllowed): ?>
    </form>
  <?php endif; ?>
  <?=$this->paginator ? $this->paginationControl($this->paginator, 'Sliding', 'Helpers/pagination.phtml', ['params' => $this->params]) : ''?>
<?php elseif (!(isset($this->error) && $this->error)): ?>
  <div class="alert alert-info">
    <?=$this->transEsc('loan_history_empty')?>
  </div>
<?php endif; ?>
