<?php
$center = $this->position == 'top' ? 'center' : '';
$logo = $this->logo;
$language = $this->language ?? $this->layout()->userLang;
if ($logo == null) {
  $logo = 'logo-knihovny.cz-' . $language . '.svg';
}
?>
<head>
  <meta name='viewport' content='width=device-width, initial-scale=1'>
  <link rel='stylesheet' type='text/css' href='/themes/<?=$this->theme?>/css/embedded-search.css'>
</head>
<body>

  <?php if ($logo != ''): ?>
    <a href='<?=$this->escapeHtmlAttr($link)?>' title='<?=$this->escapeHtmlAttr($title)?>'>
      <img class="logo <?=$center?>" src="<?=$this->imageLink($logo)?>" alt="<?= $this->translate('logo_alt') ?>">
    </a>
  <?php endif;?>

  <form action='<?=$this->escapeHtmlAttr($link)?>' method='get'  class='search-body <?=$center?>' target='_top'>
    <input class='form-control lookfor <?=$center?>'  type='text'  name='lookfor'  value=''>
    <input type='hidden' name='type' value='<?=$this->escapeHtmlAttr($this->type)?>'>
    <input type='hidden' name='lng' value='<?=$this->escapeHtmlAttr($language)?>'>
    <input class='form-control find-button' type='submit' value='<?=$this->translate('Find')?>'>
  </form>
</body>
