<?php
$center = $this->position == 'top' ? 'center' : '';
$language = $this->language ?? $this->layout()->userLang;
?>
<?=$this->doctype()?>

<html lang="<?=$this->layout()->userLang?>"<?php if ($this->layout()->rtl): ?> dir="rtl"<?php endif; ?>>
<head>
  <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
  <meta name="viewport" content="width=device-width,initial-scale=1.0"/>
  <link rel='stylesheet' type='text/css' href='/themes/<?=$this->theme?>/css/embedded-search.css'>
</head>
<body>
  <?php $logo = $this->render('layout/logoimagelink.phtml', ['language' => $language]);?>
  <?php if (!empty($logo)): ?>
    <a href='<?=$baseUrl?>' title='<?=$this->transEsc($this->title)?>'>
      <img class="logo <?=$center?>" src="<?=$logo?>" alt="<?=$this->translate('logo_alt') ?>">
    </a>
  <?php endif;?>

  <form action='<?=$this->escapeHtmlAttr($link)?>' method='get' class='search-body <?=$center?>' target='_top'>
    <input class='form-control lookfor <?=$center?>' type='text' name='lookfor' value='<?=$this->lookfor?>'>
    <input type='hidden' name='type' value='<?=$this->escapeHtmlAttr($this->type)?>'>
    <input type='hidden' name='lng' value='<?=$this->escapeHtmlAttr($language)?>'>
    <input class='form-control find-button' type='submit' value='<?=$this->translate('Find')?>'>
  </form>
</body>
</html>
