<?php
  // Set page title.
  $this->headTitle($this->translate('Search Home'));

  // Disable top search box -- this page has a special layout.
  $this->layout()->searchbox = false;

  // Set default value if necessary:
  if (!isset($this->searchClassId)) {
    $config = $this->config()->get('config');
    $this->searchClassId = $config->Site->defaultSearchBackend ?? 'Solr';
  }

  $this->layout()->breadcrumbs = false;
  $this->viewModel()->getRoot()->setVariable('frontPage', true);
?>
<?=$this->slot('search-home-title')->set('');?>
<div class="searchHomeContent">
  <?php $this->slot('search-home-hero')->start() ?>
    <?=$this->context($this)->renderInContext('search/searchbox.phtml', ['ignoreHiddenFilterMemory' => true])?>
    <?=$this->inlineScript(\Laminas\View\Helper\HeadScript::SCRIPT, '$("#searchForm_lookfor").focus();', 'SET'); ?>
  <?=$this->slot('search-home-hero')->end() ?>
</div>

<div class="row">
  <?=implode('', array_map([$this, 'contentBlock'], $blocks ?? []))?>
</div>
