#!/usr/bin/env bash

if [ ! -f /.dockerenv ]; then
    echo "This script needs to be run from container"
    exit 1
fi
exit 0

cd /var/www/knihovny-cz

echo "local/$PARAM_VUFIND_CONFIG_DIR"
VUFIND_LOCAL_DIR="local/$PARAM_VUFIND_CONFIG_DIR" VUFIND_LOCAL_MODULES="KnihovnyCz,KnihovnyCzConsole" php public/index.php util/clear_cache
