#!/usr/bin/env bash

cd /var/www/knihovny-cz

VUFIND_LOCAL_DIR="local/$PARAM_VUFIND_CONFIG_DIR" VUFIND_LOCAL_MODULES="KnihovnyCz,KnihovnyCzConsole,VuFindConsole" php public/index.php util/clear_cache
