#!/usr/bin/env bash
set -e

EXTENSION_DIR="/var/www/knihovny-cz-extension"

# Set default values to use in bootstrap scripts
if [[ -z "$PARAM_VUFIND_SRC" ]]; then
    export PARAM_VUFIND_SRC="/var/www/knihovny-cz"
fi;

if [ -z "$PARAM_VUFIND_CONFIG_DIR" ]; then
    export PARAM_VUFIND_CONFIG_DIR="knihovny.cz"
fi;

if [[ -n "$PARAM_VUFIND_ROBOTS_TXT" && -e "${EXTENSION_DIR}/public/$PARAM_VUFIND_ROBOTS_TXT" ]]; then
    ln -s -f "${EXTENSION_DIR}/public/$PARAM_VUFIND_ROBOTS_TXT" "${PARAM_VUFIND_SRC}/public/robots.txt"
fi;

# Export common configuration
PARAM_VUFIND_CONFIG_ABS_DIR="${PARAM_VUFIND_SRC}/local/${PARAM_VUFIND_CONFIG_DIR}"
export PARAM_VUFIND_CONFIG_ABS_DIR

# Make links to our extensions
EXTENSION_MODULE_DIR="${EXTENSION_DIR}/module"
VUFIND_MODULE_DIR="${PARAM_VUFIND_SRC}/module"
for modul in KnihovnyCz KnihovnyCzApi KnihovnyCzConsole KnihovnyCzCronApi; do
    if test ! -e "${VUFIND_MODULE_DIR}/${modul}"; then
        ln -s "${EXTENSION_MODULE_DIR}/${modul}/" "${VUFIND_MODULE_DIR}/${modul}"
    fi
done

# Themes
EXTENSION_THEME_DIR="${EXTENSION_DIR}/themes"
VUFIND_THEME_DIR="${PARAM_VUFIND_SRC}/themes"
for theme in ${EXTENSION_THEME_DIR}/*/; do
    name=$(basename "$theme")
    if test ! -e "${VUFIND_THEME_DIR}/${name}"; then
        ln -s "${EXTENSION_THEME_DIR}/${name}/" "${VUFIND_THEME_DIR}/${name}"
    fi
done

# XSL
EXTENSION_XSL_DIR="${EXTENSION_DIR}/xsl"
VUFIND_XSL_DIR="${PARAM_VUFIND_SRC}/xsl"
ln -s "${EXTENSION_XSL_DIR}/" "${VUFIND_XSL_DIR}"

# Compile CSS in themes
grunt less custom

# Local configs
for config in ${EXTENSION_DIR}/local/*/; do
    name=$(basename "$config")
    if test ! -e "${PARAM_VUFIND_SRC}/local/$name"; then
        ln -s "${EXTENSION_DIR}/local/$name/" "${PARAM_VUFIND_SRC}/local/$name"
    fi
    # Make cache dirs - if they not exist, the script clear-cache executed below
    # will create them - but with root:root as owner
    if [ ! -d "${PARAM_VUFIND_SRC}/local/$name/cache" ]; then
      mkdir "${PARAM_VUFIND_SRC}/local/$name/cache"
    fi
    # Make local data available to application
    chgrp -R www-data "${PARAM_VUFIND_SRC}/local/$name/"
    chmod -R g+w "${PARAM_VUFIND_SRC}/local/$name/"
done

# Run all start files
if test -d /onstart; then
    for FILE in /onstart/*; do
        if test -x "$FILE"; then
            "$FILE" || test "${IGNORE_BOOTSTRAP_FAILURE:-false}" == "true" || exit $?
        else
            echo "Warning: found non-executable file at '$FILE'" >&2
        fi
    done
fi

# Create place for logs
mkdir -p "${PARAM_VUFIND_SRC:-/var/www/src}/log"

# List all environment variables
# WARNING: possible threat of exploiting the secrets here (by saving `env` output to the docker logs)
env

clear-cache

# This has to be done so that the server can create caches & logs
chgrp -R www-data "/var/www"
chmod -R g+w "${EXTENSION_DIR}/themes"
chmod -R g+w "${PARAM_VUFIND_SRC:-/var/www/src}/log"

echo
echo " --- Bootstrapping done! "
echo

apache2-foreground || \
    test "${IGNORE_BOOTSTRAP_FAILURE:-false}" == "true" && \
    echo "ERROR: apache start failed !" >&2 && \
    while true; do sleep 1; done
