<?=$this->render('search/advanced/solr-facets.phtml')?>
<?php
  $class = isset($this->illustratedLimit) ? 'col-sm-4' : 'col-sm-6';
?>
<div class="row">
  <?php if (isset($this->illustratedLimit)): ?>
    <div class="<?=$class?>">
      <fieldset class="solr">
        <legend><?=$this->transEsc('Illustrated')?>:</legend>
        <?php foreach ($this->illustratedLimit as $current): ?>
          <input id="illustrated_<?=$this->escapeHtmlAttr($current['value'])?>" type="radio" name="illustration" value="<?=$this->escapeHtmlAttr($current['value'])?>"<?=$current['selected'] ? ' checked="checked" data-checked-by-default="true"' : ''?>>
          <label for="illustrated_<?=$this->escapeHtmlAttr($current['value'])?>"><?=$this->transEsc($current['text'])?></label><br>
        <?php endforeach; ?>
      </fieldset>
    </div>
  <?php endif; ?>
  <div class="<?=$class?>">
    <?=$this->render('search/advanced/ranges.phtml')?>
  </div>
  <div class="<?=$class?>">
    <?=$this->render('search/advanced/limit.phtml')?>
  </div>
</div>
