<div class="media" vocab="http://schema.org/" resource="#record" typeof="<?=$this->driver->getSchemaOrgFormats()?> Product">
  <?php
    $coverDetails = $this->record($this->driver)->getCoverDetails('core', 'medium', $this->record($this->driver)->getThumbnail('large'));
    $cover = $coverDetails['html'];
    $preview = ($this->previewOverride ?? false)
      ? $this->previewOverride : $this->record($this->driver)->getPreviews();
  ?>
  <?php if ($QRCode || $cover || $preview): ?>
    <div class="media-left <?=$this->escapeHtmlAttr($coverDetails['size'])?> img-col">
      <?php /* Display thumbnail if appropriate: */ ?>
      <?php if($cover): ?>
        <?=$cover?>
      <?php endif; ?>

      <?php /* Display qrcode if appropriate: */ ?>
      <?php if($QRCode): ?>
        <span class="hidden-xs">
          <br/><img alt="<?=$this->transEsc('QR Code')?>" class="qrcode" src="<?=$this->escapeHtmlAttr($QRCode);?>"/>
        </span>
      <?php endif; ?>

      <?php // if you have a preview tab but want to move or remove the preview link
      // from this area of the record view, this can be split into
      // getPreviewData() (should stay here) and
      // getPreviewLink() (can go in your desired tab) ?>
      <?php if ($preview): ?>
        <div class="record-previews">
          <?=$preview?>
        </div>
      <?php endif; ?>
    </div>
  <?php endif; ?>
  <div class="media-body">
    <h1 property="name" class="record-title"><?=$this->escapeHtml($this->driver->getTitle())?></h1>
    <?php /* Display Main Details */ ?>
    <?php
    $formatter = $this->recordDataFormatter();
    $coreFields = $formatter->getData($driver, $formatter->getDefaults('authority'));
    ?>
    <?php if (!empty($coreFields)): ?>
      <table class="table table-striped">
        <caption class="sr-only"><?=$this->transEsc('Authority Details')?></caption>
        <?php foreach ($coreFields as $current): ?>
          <tr><th><?=$this->transEsc($current['label'])?>:</th><td><?=$current['value']?></td></tr>
        <?php endforeach; ?>
      </table>
    <?php endif; ?>
    <?php /* End Main Details */ ?>
  </div>
</div>
