<ul class="media-list">
  <?php
  $itemIndex = 1;
  foreach ($ticketsData as $item):
    /** @var \Mzk\ZiskejApi\ResponseModel\Ticket $ticket */
    $ticket = $item['ticket'];
    /** @var ?\KnihovnyCz\RecordDriver\SolrLocal $record */
    $record = $item['record'];
    ?>
    <li class="media well" id="record_<?=$ticket->getHid()?>" data-ziskej="<?=$ticket->getHid()?>">
      <strong class="pull-left order"><?= $itemIndex++ ?>.</strong>
      <?php
      $thumbnail = false;
      if ($record) {
        $coverDetails = $this->record($record)->getCoverDetails('checkedout', 'small', $this->recordLink()->getUrl($record));
        $cover = $coverDetails['html'];
        if ($cover) {
          ob_start();
          echo $cover;
          $thumbnail = ob_get_contents();
          ob_end_clean();
        }
      }
      ?>
      <?php if ($thumbnail): ?>
        <div class="media-left small">
          <?=$thumbnail?>
        </div>
      <?php endif ?>
      <div class="media-body">
        <h4 class="media-heading">
          <?php if ($record): ?>
            <?php
            $title = !empty($record->getTitle())
              ? $this->escapeHtml($record->getTitle())
              : $this->transEsc('Title not available');
            ?>
            <a href="<?=$this->recordLink()->getUrl($record)?>" class="title"><?=$title?></a>
          <?php else: ?>
            <?=$this->transEsc('record_info_not_available')?>
          <?php endif; ?>
        </h4>
        <div>
          <dl class="dl-horizontal dl-left">
            <?php if ($record): ?>
              <?php $listAuthor = $record->getPrimaryAuthor() ?>
              <?php if (!empty($listAuthor)): ?>
                <dt><?=$this->transEsc('by')?>:</dt>
                <dd>
                  <a href="<?=$this->record($record)->getLink('author', $listAuthor)?>">
                    <?=$this->escapeHtml($listAuthor)?>
                  </a>
                </dd>
              <?php endif; ?>
              <?php if (is_countable($record->getFormats()) && count($record->getFormats()) > 0): ?>
                <dt><?=$this->transEsc('Ziskej::label_document_type')?>:</dt>
                <dd><?=$this->record($record)->getFormatList()?></dd>
              <?php endif; ?>
            <?php endif; ?>
            <?php if ($ticket->getCreatedAt()): ?>
              <dt><?=$this->transEsc('Ziskej::label_date_order')?>:</dt>
              <dd><?=$this->dateTime()->convertToDisplayDate('U', $ticket->getCreatedAt()->getTimestamp())?></dd>
            <?php endif; ?>
            <?php if ($ticket->getRequestedAt()): ?>
              <dt><?=$this->transEsc('Ziskej::label_date_deliver')?>:</dt>
              <dd><?=$this->dateTime()->convertToDisplayDate('U', $ticket->getRequestedAt()->getTimestamp())?></dd>
            <?php endif; ?>
            <?php if ($ticket->getReturnAt()): ?>
              <dt><?=$this->transEsc('Ziskej::label_date_return')?>:</dt>
              <dd><?=$this->dateTime()->convertToDisplayDate('U', $ticket->getReturnAt()->getTimestamp())?></dd>
            <?php endif; ?>
            <dt><?=$this->transEsc('Ziskej::label_order_number')?>:</dt>
            <dd><?=$ticket->getHid()?></dd>

            <?php if ($ticket->getStatus()): ?>
              <dt><?=$this->transEsc('Ziskej::label_order_status')?>:</dt>
              <dd>
                <span class="label label-<?=$this->ziskejMvs()->getStatusClass($ticket->getStatus())?>">
                  <?=$this->transEsc('Ziskej::order_status_' . $ticket->getStatus())?>
                </span>
              </dd>
            <?php endif; ?>
          </dl>
          <div class="text-right">
            <?php if ($ticket->getStatus() == 'created' && !empty($ticket->getPaymentUrl())): ?>
              <a class="btn btn-sm btn-warning" href="<?=$ticket->getPaymentUrl()?>" target="_blank" title="<?=$this->transEsc("Ziskej::btn_order_pay_title")?>">
                <i class="fa fa-shopping-cart"></i> <?=$this->transEsc("Ziskej::btn_order_pay")?>
              </a>
            <?php endif; ?>
            <a class="btn btn-sm btn-primary" href="<?=$this->url('myresearch-ziskej-ticket', ['eppnDomain' => $userCard->getEppnDomain(), 'ticketId' => $ticket->getId()])?>" title="<?=$this->transEsc("Ziskej::btn_order_detail_title")?>">
              <i class="fa fa-search"></i> <?=$this->transEsc("Ziskej::btn_order_detail")?>
            </a>
          </div>
        </div>
      </div>
    </li>
  <?php endforeach; ?>
</ul>
