<?php
// Set up page title:
$this->headTitle($this->translate('Checked Out Items'));

// Set up breadcrumbs:
$this->layout()->breadcrumbs = '<li><a href="' . $this->url('myresearch-home') . '">' . $this->transEsc('Your Account') . '</a></li> <li class="active">' . $this->transEsc('Checked Out Items') . '</li>';

/** @var \KnihovnyCz\Db\Row\UserCard $userCard */
$userCard = $this->userCard;
?>

<a class="search-filter-toggle visible-xs" href="#myresearch-sidebar" data-toggle="offcanvas" title="Expand Sidebar">
  <?=$this->transEsc('Your Account') ?>
</a>

<div class="<?=$this->layoutClass('mainbody') ?>">
  <h2><?=$this->transEsc('Aktuální výpůjčky ve službě Získej') ?></h2>
  <?=$this->flashmessages() ?>

  <?=$this->context($this)->renderInContext('librarycards/selectcard.phtml', ['user' => $this->auth()->isLoggedIn()]) ?>

  <h3 class="well row blickable" style="margin-bottom: 3px;">
    <?=$this->transEsc("source_" . $userCard->home_library, null, $userCard->home_library) ?>
    <? //<img class="pull-right" height="32" src="<?= $this->logos()->getLogo($userCard->home_library)"/> //@todo?>
  </h3>

  <?php if (!empty($reader)): ?>
    <div class="well">
      <i class="fa fa-fw fa-user text-muted"></i> <?=$reader->getFirstName() ?> <?=$reader->getLastName() ?>
      <br>
      <i class="fa fa-fw fa-envelope text-muted"></i> <?=$reader->getEmail() ?>
    </div>
  <?php endif; ?>

  <?php if (count($this->tickets)): ?>
    <ul class="media-list">
      <?php
      $i = 0;
      foreach ($this->tickets as $item):
        ++$i;
        /** @var \Mzk\ZiskejApi\ResponseModel\Ticket $ticket */
        $ticket = $item['ticket'];
        /** @var \KnihovnyCz\RecordDriver\SolrLocal $record */
        $record = $item['record'];
        ?>
        <li class="media well" id="record_<?=$ticket->getHid() ?>" data-ziskej="<?=$ticket->getHid() ?>">
          <div class="media-left text-center" style="min-width: 100px;">
            <?php
            $backLink = $this->serverUrl($this->recordLink()->getUrl($record));
            $formats = $record->getFormats();
            $recordId = preg_replace("/[\.:]/", "", $record->getUniqueId() . $i);
            ?>
            <div id="cover_<?=$recordId ?>" class="coverThumbnail">
              [image]
            </div>
          </div>
          <div class="media-body">
            <h4 class="media-heading">
              <?php if (is_a($record, \VuFind\RecordDriver\SolrDefault::class) && !is_a($record, \VuFind\RecordDriver\Missing::class)): ?>
                <?php
                $title = !empty($record->getTitle())
                  ? $this->escapeHtml($record->getTitle())
                  : $this->transEsc('Title not available');
                ?>
                <a href="<?=$this->recordLink()->getUrl($record) ?>" class="title"><?=$title?></a>
              <?php else: ?>
                <?=$this->transEsc('Title not available') ?>
              <?php endif; ?>
            </h4>
            <div>
              <dl class="dl-horizontal dl-left">
                <? $listAuthor = $record->getPrimaryAuthor() ?>
                <?php if (!empty($listAuthor)): ?>
                  <dt><?=$this->transEsc('by') ?>:</dt>
                  <dd>
                    <a href="<?=$this->record($record)->getLink('author', $listAuthor) ?>">
                      <?=$this->escapeHtml($listAuthor) ?>
                    </a>
                  </dd>
                <?php endif; ?>
                <?php if (count($record->getFormats()) > 0): ?>
                  <dt><?=$this->transEsc('ziskej_label_document_type') ?>:</dt>
                  <dd><?=$this->record($record)->getFormatList() ?></dd>
                <?php endif; ?>
                <?php if ($ticket->getCreatedAt()): ?>
                  <dt><?=$this->transEsc('ziskej_label_date_order') ?>:</dt>
                  <dd><?=$this->dateTime()->convertToDisplayDate('U', $ticket->getCreatedAt()->getTimestamp()) ?></dd>
                <?php endif; ?>
                <?php if ($ticket->getRequestedAt()): ?>
                  <dt><?=$this->transEsc('ziskej_label_date_deliver') ?>:</dt>
                  <dd><?=$this->dateTime()->convertToDisplayDate('U', $ticket->getRequestedAt()->getTimestamp()) ?></dd>
                <?php endif; ?>
                <?php if ($ticket->getReturnAt()): ?>
                  <dt><?=$this->transEsc('ziskej_label_date_return') ?>:</dt>
                  <dd><?=$this->dateTime()->convertToDisplayDate('U', $ticket->getReturnAt()->getTimestamp()) ?></dd>
                <?php endif; ?>
                <dt><?=$this->transEsc('ziskej_label_order_number') ?>:</dt>
                <dd><?=$ticket->getHid() ?></dd>

                <?php if ($ticket->getStatus()): ?>
                  <dt><?=$this->transEsc('ziskej_label_order_status') ?>:</dt>
                  <dd>
                      <span class="label label-<?//=$this->Order()->getStatusClass($ticket->getStatus())  //@todo!!! ?>">
                        <?=$this->translate('ziskej_order_status_' . $ticket->getStatus()) ?>
                      </span>
                  </dd>
                <?php endif; ?>
              </dl>
              <div class="text-right">
                <?php if ($ticket->getStatus() == 'created' && !empty($ticket->getPaymentUrl())): ?>
                  <a class="btn btn-sm btn-warning" href="<?=$ticket->getPaymentUrl() ?>" target="_blank" title="<?=$this->transEsc("btn_order_pay_title") ?>">
                    <i class="fa fa-shopping-cart"></i> <?=$this->transEsc("btn_order_pay") ?>
                  </a>
                <?php endif; ?>
                <a class="btn btn-sm btn-primary" href="<?=$this->url('myresearch-ziskej-ticket', ['eppnDomain' => $userCard->getEppnDomain(), 'ticketId' => $ticket->getId()]) ?>" title="<?=$this->transEsc("btn_order_detail_title") ?>">
                  <i class="fa fa-search"></i> <?=$this->transEsc("btn_order_detail") ?>
                </a>
              </div>
            </div>
          </div>
        </li>
      <?php endforeach; ?>
    </ul>
  <?php else: ?>
    <div class="panel">
      <div class="panel-body">
        <div class="alert alert-info">
          <?=$this->transEsc('ziskej_info_no_items') ?>
        </div>
      </div>
    </div>
  <?php endif; ?>
</div>

<div class="<?=$this->layoutClass('sidebar') ?>" id="myresearch-sidebar">
  <?=$this->context($this)->renderInContext("myresearch/menu.phtml", ['active' => 'ziskej']) ?>
</div>
