<?=$this->flashmessages()?>

<?php
/** @var \KnihovnyCz\Db\Row\UserCard $userCard */
$userCard = $this->userCard;
?>
<?php if ($userCard && $userCard->eppn): ?>
  <?php if ($this->isZiskejModeEnabled): ?>
    <?php if ($this->isLibraryInZiskej): ?>
      <?php
      /** @var \Mzk\ZiskejApi\ResponseModel\Reader|null $reader */
      $reader = $this->reader;
      ?>
      <?php if ($reader): ?>
        <div class="well">
          <i class="fa fa-fw fa-user text-muted"></i> <?=$reader->getFirstName()?> <?=$reader->getLastName()?>
          <br>
          <i class="fa fa-fw fa-envelope text-muted"></i> <?=$reader->getEmail()?>
        </div>
        <?php if (count($this->tickets)): ?>
          <ul class="media-list">
            <?php
            $i = 0;
            foreach ($this->tickets as $item):
              ++$i;
              /** @var \Mzk\ZiskejApi\ResponseModel\Ticket $ticket */
              $ticket = $item['ticket'];
              /** @var \KnihovnyCz\RecordDriver\SolrLocal $record */
              $record = $item['record'];
              ?>
              <li class="media well" id="record_<?=$ticket->getHid()?>" data-ziskej="<?=$ticket->getHid()?>">
                <?php
                $coverDetails = $this->record($record)->getCoverDetails('checkedout', 'small', $this->recordLink()->getUrl($record));
                $cover = $coverDetails['html'];
                $thumbnail = false;
                $thumbnailAlignment = $this->record($record)->getThumbnailAlignment('account');
                if ($cover):
                  ob_start(); ?>
                  <div class="media-<?=$thumbnailAlignment ?> <?=$this->escapeHtmlAttr($coverDetails['size'])?>">
                    <?=$cover ?>
                  </div>
                  <?php $thumbnail = ob_get_contents(); ?>
                  <?php ob_end_clean(); ?>
                <?php endif; ?>
                <?php if ($thumbnail && $thumbnailAlignment == 'left'): ?>
                  <?=$thumbnail ?>
                <?php endif ?>
                <div class="media-body">
                  <h4 class="media-heading">
                    <?php if (is_a($record, \VuFind\RecordDriver\SolrDefault::class) && !is_a($record, \VuFind\RecordDriver\Missing::class)): ?>
                      <?php
                      $title = !empty($record->getTitle())
                        ? $this->escapeHtml($record->getTitle())
                        : $this->transEsc('Title not available');
                      ?>
                      <a href="<?=$this->recordLink()->getUrl($record)?>" class="title"><?=$title?></a>
                    <?php else: ?>
                      <?=$this->transEsc('Title not available')?>
                    <?php endif; ?>
                  </h4>
                  <div>
                    <dl class="dl-horizontal dl-left">
                      <?php $listAuthor = $record->getPrimaryAuthor() ?>
                      <?php if (!empty($listAuthor)): ?>
                        <dt><?=$this->transEsc('by')?>:</dt>
                        <dd>
                          <a href="<?=$this->record($record)->getLink('author', $listAuthor)?>">
                            <?=$this->escapeHtml($listAuthor)?>
                          </a>
                        </dd>
                      <?php endif; ?>
                      <?php if (count($record->getFormats()) > 0): ?>
                        <dt><?=$this->transEsc('Ziskej::label_document_type')?>:</dt>
                        <dd><?=$this->record($record)->getFormatList()?></dd>
                      <?php endif; ?>
                      <?php if ($ticket->getCreatedAt()): ?>
                        <dt><?=$this->transEsc('Ziskej::label_date_order')?>:</dt>
                        <dd><?=$this->dateTime()->convertToDisplayDate('U', $ticket->getCreatedAt()->getTimestamp())?></dd>
                      <?php endif; ?>
                      <?php if ($ticket->getRequestedAt()): ?>
                        <dt><?=$this->transEsc('Ziskej::label_date_deliver')?>:</dt>
                        <dd><?=$this->dateTime()->convertToDisplayDate('U', $ticket->getRequestedAt()->getTimestamp())?></dd>
                      <?php endif; ?>
                      <?php if ($ticket->getReturnAt()): ?>
                        <dt><?=$this->transEsc('Ziskej::label_date_return')?>:</dt>
                        <dd><?=$this->dateTime()->convertToDisplayDate('U', $ticket->getReturnAt()->getTimestamp())?></dd>
                      <?php endif; ?>
                      <dt><?=$this->transEsc('Ziskej::label_order_number')?>:</dt>
                      <dd><?=$ticket->getHid()?></dd>

                      <?php if ($ticket->getStatus()): ?>
                        <dt><?=$this->transEsc('Ziskej::label_order_status')?>:</dt>
                        <dd>
                          <span class="label label-<?=$this->ziskejMvs()->getStatusClass($ticket->getStatus()) ?>">
                            <?=$this->transEsc('Ziskej::order_status_' . $ticket->getStatus())?>
                          </span>
                        </dd>
                      <?php endif; ?>
                    </dl>
                    <div class="text-right">
                      <?php if ($ticket->getStatus() == 'created' && !empty($ticket->getPaymentUrl())): ?>
                        <a class="btn btn-sm btn-warning" href="<?=$ticket->getPaymentUrl()?>" target="_blank" title="<?=$this->transEsc("Ziskej::btn_order_pay_title")?>">
                          <i class="fa fa-shopping-cart"></i> <?=$this->transEsc("Ziskej::btn_order_pay")?>
                        </a>
                      <?php endif; ?>
                      <a class="btn btn-sm btn-primary" href="<?=$this->url('myresearch-ziskej-ticket', ['eppnDomain' => $userCard->getEppnDomain(), 'ticketId' => $ticket->getId()])?>" title="<?=$this->transEsc("Ziskej::btn_order_detail_title")?>">
                        <i class="fa fa-search"></i> <?=$this->transEsc("Ziskej::btn_order_detail")?>
                      </a>
                    </div>
                  </div>
                </div>
                <?php if ($thumbnail && $thumbnailAlignment == 'right'): ?>
                  <?=$thumbnail ?>
                <?php endif ?>
              </li>
            <?php endforeach; ?>
          </ul>
        <?php else: ?>
          <div class="alert alert-info">
            <?=$this->transEsc('Ziskej::info_no_items')?>
          </div>
        <?php endif; ?>
      <?php else: ?>
        <div class="alert alert-danger">
          <?=$this->transEsc('Ziskej::reader_disabled_in_ziskej')?>
        </div>
      <?php endif; ?>
    <?php else: ?>
      <div class="alert alert-danger">
        <?=$this->transEsc('Ziskej::library_not_found_in_ziskej')?>
      </div>
    <?php endif; ?>
  <?php else: ?>
    <div class="alert alert-danger">
      <?=$this->transEsc('Ziskej::mode_disabled')?>
    </div>
  <?php endif; ?>
<?php else: ?>
  <div class="alert alert-danger">
    <?=$this->transEsc('Ziskej::user_card_not_found')?>
  </div>
<?php endif; ?>
