<?php
// Set up page title:
$this->headTitle($this->translate('Ziskej::checked_out_items'));

// Set up breadcrumbs:
$this->layout()->breadcrumbs = '<li><a href="' . $this->url('myresearch-home') . '">' . $this->transEsc('Your Account') . '</a></li> <li class="active">' . $this->transEsc('Ziskej::checked_out_items') . '</li>';

$loadJs = <<<JS
  function loadZiskej(element) {
    loadCovers();
  };
JS;
?>

<a class="search-filter-toggle visible-xs" href="#myresearch-sidebar" data-toggle="offcanvas" title="Expand Sidebar">
  <?=$this->transEsc('Your Account') ?>
</a>

<div class="<?=$this->layoutClass('mainbody')?>">
  <?=$this->flashmessages();?>

  <h2><?=$this->transEsc('Ziskej::checked_out_items')?></h2>
  <p>
    <?=$this->context($this)->renderInContext('librarycards/listcards.phtml', [
      'user' => $this->auth()->isLoggedIn(),
      'action' => $this->url('myresearchziskej-listajax'),
      'callback' => 'loadZiskej',
    ]);
    ?>
  </p>
</div>

<div class="<?=$this->layoutClass('sidebar')?>" id="myresearch-sidebar">
  <?=$this->context($this)->renderInContext("myresearch/menu.phtml", ['active' => 'ziskej'])?>
</div>

<?=$this->inlineScript(\Laminas\View\Helper\HeadScript::SCRIPT, $loadJs, 'SET')?>
<noscript><?=$this->transEsc('Please enable JavaScript.')?></noscript>

