# If this file is empty or missing, default settings will be used, matching
# the examples provided below. The format of this configuration is as follows:
# array keys for every menu item could be:
#   - name: name of an item
#   - label: the text shown as link, will be translated - required
#   - route: route name used to generate link target - required
#   - icon: icon used for the item, has to be defined in theme config
#   - iconMethod: method to dynamically create the icon name; ignored when
#     icon is explicitly set.
#   - checkMethod: the name of an AccountMenu view helper method to perform
#     a check whether to show the item. If omitted, item will always display.
#   - status: whether to show status label, defaults to false

MenuItems:
  - name: checkedout
    label: Checked Out Items
    route: myresearch-checkedout
    icon: user-checked-out
    status: true
    checkMethod: checkCheckedout

  - name: holds
    label: Holds and Recalls
    route: holds-list
    icon: user-holds
    status: true
    checkMethod: checkHolds

  - name: fines
    label: Fines
    route: myresearch-fines
    status: true
    checkMethod: checkFines
    iconMethod: finesIcon

  - name: shortloans
    label: short_loan_title_text
    route: myresearch-shortloans
    icon: short-loans
    checkMethod: checkShortloans

  - name: ILLRequests
    label: Interlibrary Loan Requests
    route: myresearch-illrequests
    icon: user-ill-requests
    status: true
    checkMethod: checkILLRequests

  - name: ziskej
    label: ZiskejMvs::service_name
    route: myresearch-ziskej-mvs-home
    icon: user-ziskej
    status: true
    checkMethod: checkZiskejMvs

  - name: ziskej-edd
    label: ZiskejEdd::service_name
    route: myresearch-ziskej-edd-home
    icon: user-ziskej-edd
    status: true
    checkMethod: checkZiskejEdd

  - name: historicloans
    label: Loan History
    route: checkouts-history
    icon: user-loan-history
    checkMethod: checkHistoricloans

  - name: profile
    label: Profile
    route: myresearch-profile
    icon: profile

  - name: history
    label: Search History
    route: search-history
    icon: search
    checkMethod: checkHistory

  - name: favorites
    label: Favorites
    route: myresearch-favorites
    icon: user-favorites
    checkMethod: checkFavorites

  - name: logout
    label: Log Out
    route: myresearch-logout
    icon: sign-out
    checkMethod: checkLogout

  - name: notifications
    label: Notifications::Manage notifications
    route: notifications
    icon: notifications-management
    checkMethod: checkNotifications
