<?php
  // Set page title.
  $this->headTitle($this->translate('Cite this'));

  // Set up breadcrumbs:
  $this->layout()->breadcrumbs = $this->searchMemory()->getLastSearchLink($this->transEsc('Search'), '<li>', '</li> ')
    . '<li><a href="' . $this->url('cart-cite') . '">' . $this->transEsc('Cart') . '</a></li> '
    . '<li class="active">' . $this->transEsc('Cite this') . '</li>';
?>
<h2><?=$this->transEsc('Cite this') ?></h2>
<?=
  $this->context($this)->renderInContext(
      'cite/cite.phtml',
      [
      'citationStyles' => $this->citationStyles,
      'citations' => $this->citations,
    ]
  );
?>