<?php
  $currentRecordId = $this->driver->tryMethod('getUniqueID');
  $currentSource = $this->driver->tryMethod('getSourceId');
  preg_match('/[a-z]+\.([A-Z0-9]+)-[0-9]*/', $currentRecordId, $matches);
  $currentBase = $matches[1] ?? '';

  $logosPostfix = '_small';
  $records = $this->driver->tryMethod('getDeduplicatedRecords', [], false);
  $recordMissing = $records !== false && empty($records);
  if ($records === false) {
    $records = [];
  } elseif (empty($records)) {
      $records = [$currentSource => [$currentRecordId]];
  } else {
    if (!isset($records[$currentSource])) {
      $records[$currentSource] = [$currentRecordId];
      $recordMissing = true;
    }
    if (!in_array($currentRecordId, $records[$currentSource])) {
      $records[$currentSource][] = $currentRecordId;
      $recordMissing = true;
    }
  }
  $data = [];
  $bases = [];
  foreach ($records as $source => $ids) {
    $imageSrc = $this->imageLink(
        'institutions/logos/' . $source . '/' . $source
      . $logosPostfix . '.png'
    );
    sort($ids);
    foreach ($ids as $id) {
      preg_match('/[a-z]+\.([A-Z0-9]+)-[0-9]*/', $id, $matches);
      $base = $matches[1] ?? '';
      if (!isset($bases[$base])) {
        $bases[$base] = ['count' => 0, 'index' => 1];
      }
      $bases[$base]['count']++;
      $text = ($source === 'nkp' && $base !== '')
        ? $this->transEsc('Base::facet_base_' . $base)
        : $this->translate('Source::' . $source);
      $data[] = [
        'id' => $id,
        'href' => $this->recordLinker()->getUrl($id),
        'selected' => $currentRecordId == $id,
        'text' => $text,
        'logoAltText' => $this->translate('logo_of', ['%%source%%' => $this->translate('Source::' . $source)]),
        'base' => $base,
      ];
    }
  }
  foreach ($data as &$record) {
    if ($bases[$record['base']]['count'] > 1) {
      $record['text'] .= ' - ' . $this->transEsc('record') . ' ' . ($bases[$record['base']]['index']++);
    }
  }
  $recordsCount = count($data);
  $showInstitutionPanel = $this->showInstitutionPanel ?? true;
?>
<?php if ($recordsCount >= 1): ?>
  <div class="card panel-select-institution">
    <div class="card-body">
      <?php if ($showInstitutionPanel): ?>
        <?php if ($recordsCount > 1): ?>
          <h3><label for="institutions"><?=$this->translate('Select institution');?></label>:</h3>
          <div class="d-sm-flex gap-1">
            <select id="institutions" class="form-select form-select-lg w-100" name="institutions"></select>
            <?php if ($libraryId = $this->driver->getOwningLibraryId()): ?>
              <?=$this->render('library-detail-link.phtml', ['libraryId' => $libraryId, 'base' => $currentBase])?>
            <?php endif; ?>
          </div>
        <?php elseif ($recordsCount == 1): ?>
          <h3><?=$this->translate('Institution');?>:</h3>
          <div class="d-sm-flex gap-1">
            <span class="select2 select2-container select2-container--bootstrap3 w-100">
              <span class="select2-selection select2-selection--single select2-text" role="combobox" aria-haspopup="true" aria-expanded="false" tabindex="0" aria-disabled="false" aria-labelledby="select2-institutions-container">
                <span class="select2-selection__rendered" id="select2-institutions-container" role="textbox" aria-readonly="true" title="<?=$data[0]['text']?>">
                  <span class="institutions-selector">
                    <span class="text"><?=$data[0]['text']?></span>
                  </span>
                </span>
              </span>
            </span>
            <?php if ($libraryId = $this->driver->getOwningLibraryId()): ?>
              <?=$this->render('library-detail-link.phtml', ['libraryId' => $libraryId, 'base' => $currentBase])?>
            <?php endif; ?>
          </div>
        <?php endif; ?>
      <?php endif; ?>
      <?php if ($recordMissing): ?>
      <div class="alert alert-warning" role="alert">
        <?php if (($link = $this->recordLinker()->getLinkToMainPortal($this->driver)) != null) : ?>
          <?=$this->translate('record_missing_in_view_with_link', ['%%url%%' => $link])?>
        <?php else: ?>
          <?=$this->translate('record_missing_in_view')?>
        <?php endif; ?>
      </div>
    <?php endif; ?>
    </div>
  </div>
<?php endif;?>

<?php
if ($showInstitutionPanel && $recordsCount > 1) {
  $dataJson = json_encode($data);
  $placeholder = $this->transEsc('institutions_search_placeholder');
  $select2 = <<<JS
      var options = $dataJson;
      function template(option) {
        return $('<span class="institutions-selector"><span class="text">' + option.text + '</span></span>');
      }

      jQuery(document).ready(function($) {
        $('#institutions').select2({
          language: document.documentElement.lang,
          data: options,
          theme: 'bootstrap3',
          templateResult: template,
      		templateSelection: template
        });
        $('#institutions').on('select2:select', function (e) {
          window.location.href = e.params.data.href;
        });
        $('#institutions').on('select2:open', function (e) {
          $('.select2-search__field').attr('placeholder', '$placeholder');
        });
      });
      JS;
  echo $this->assetManager()->outputInlineScriptString($select2);
}
