<?php $this->headTitle($this->driver->getShortTitle()); ?>
<?php $this->assetManager()->appendStyleLink('select2.min.css'); ?>
<?php $this->assetManager()->appendStyleLink('select2-bootstrap3.min.css'); ?>
<?php $this->assetManager()->appendScriptLink('lib/select2/select2.min.js'); ?>
<?php $this->assetManager()->appendScriptLink('lib/select2/en.js'); ?>
<?php $this->assetManager()->appendScriptLink('lib/select2/cs.js'); ?>
<?php
  // Set a default page title; this will usually be overridden when a tab is
  // loaded, but it may be useful if there are no tabs, or when tabs are loaded
  // via AJAX:
  $this->headTitle($this->driver->getBreadcrumb());

  // Set up standard record scripts:
  $this->assetManager()->appendScriptLink('record.js');
  $this->assetManager()->appendScriptLink('check_save_statuses.js');
  // Activate Syndetics Plus if necessary:
  if ($this->syndeticsPlus()->isActive()) {
    $this->assetManager()->appendScriptLink($this->syndeticsPlus()->getScript());
  }
  // Add any extra scripts the tabs require:
  foreach ($this->tabsExtraScripts as $script) {
    $this->assetManager()->appendScriptLink($script);
  }

  // Add RDF header link if applicable:
  if ($this->export()->recordSupportsFormat($this->driver, 'RDF')) {
    $this->headLink()->appendAlternate($this->recordLinker()->getActionUrl($this->driver, 'RDF', options: ['excludeSearchId' => true]), 'application/rdf+xml', 'RDF Representation');
  }

  // Add canonical header link for SEO:
  $canonicalUrl = $this->recordLinker()->getUrl($this->driver, ['excludeSearchId' => true]);
  $this->headLink(['rel' => 'canonical', 'href' => $canonicalUrl]);

  // Set up breadcrumbs:
  $this->breadcrumbs()->reset();
  if ($url = $this->searchMemory()->getLastSearchUrl()) {
    $this->breadcrumbs()->add($this->translate('Search'), $url);
  }
  $this->breadcrumbs()->add(...$this->recordLinker()->getBreadcrumbParams($this->driver), active: true);
  $this->layout()->title = $this->driver->getShortTitle();
?>

<?php if (isset($this->scrollData) && ($this->scrollData['previousRecord'] || $this->scrollData['nextRecord'])): ?>
  <?=$this->render('record/prev-next.phtml'); ?>
<?php endif; ?>

<div class="row">
  <div class="col-sm-9">
    <div class="record source<?=$this->escapeHtmlAttr($this->driver->getSourceIdentifier())?>">
      <?php $sidebarList = $this->related()->getList($this->driver); ?>
      <div class="mainbody solo">
        <input type="hidden" value="<?=$this->escapeHtmlAttr($this->driver->getUniqueId())?>" class="hiddenId">
        <input type="hidden" value="<?=$this->escapeHtmlAttr($this->driver->getSourceIdentifier())?>" class="hiddenSource">
        <?=$this->flashmessages()?>
        <div class="card">
          <div class="card-body">
            <?=$this->record($this->driver)->getCoreMetadata()?>
          </div>
        </div>

        <?php if (count($this->tabs) > 0): ?>
          <a id="tabnav"></a>
          <div class="record-tabs">

            <div class="card card-with-tabs">
              <div class="card-header">
                <ul class="nav nav-tabs card-header-tabs">
                  <?php foreach ($this->tabs as $tab => $obj): ?>
                    <?php
                    $desc = $obj->getDescription();
                    $tabName = preg_replace("/\W/", '-', strtolower($tab));
                    $liClasses = [ 'nav-item', 'record-tab', $tabName ];
                    $aAttrs = $this->htmlAttributes([
                      'class' => 'nav-link',
                      'role' => 'tab',
                      'href' => $this->recordLinker()->getTabUrl($this->driver, $tab) . '#tabnav',
                      'data-bs-target' => '.tab-pane.' . $tabName,
                      'data-lightbox-ignore' => true,
                    ]);
                    if (0 === strcasecmp($this->activeTab, $tab)) {
                      if (!$this->loadInitialTabWithAjax || !$obj->supportsAjax()) {
                        $aAttrs->add('class', 'active');
                        $aAttrs->add('aria-selected', 'true');
                      }
                      $liClasses[] = 'initiallyActive';
                      $activeTabName = $tabName;
                      $activeTabObj = $obj;
                    }
                    if (!$obj->isVisible()) {
                      $liClasses[] = 'hidden';
                    }
                    if (!$obj->supportsAjax()) {
                      $liClasses[] = 'noajax';
                    }
                    ?>
                    <li role="presentation" id="record-tab-<?=$this->escapeHtmlAttr($tabName)?>" class="<?=implode(' ', $liClasses)?>" data-tab="<?=$this->escapeHtmlAttr($tabName)?>"<?php if ($obj->supportsAjax() && in_array($tab, $this->backgroundTabs)):?> data-background<?php endif ?>>
                      <a<?=$aAttrs?>>
                        <?=$this->transEsc($desc)?>
                        <?php if (method_exists($obj, 'isApiDown') && $obj->isApiDown()): ?>
                          <?=$this->icon('ziskej-warning', 'text-danger') ?>
                        <?php endif; ?>
                      </a>
                    </li>
                  <?php endforeach; ?>
                </ul>
              </div>
              <div class="card-body tab-content">
                <?php if (!$this->loadInitialTabWithAjax || !isset($activeTabObj) || !$activeTabObj->supportsAjax()): ?>
                  <div role="tabpanel" class="tab-pane active <?=$this->escapeHtmlAttr($this->activeTab) ?>-tab" aria-labelledby="record-tab-<?=$this->escapeHtmlAttr($activeTabName ?? '')?>">
                    <?=isset($activeTabObj) ? $this->record($this->driver)->getTab($activeTabObj) : '' ?>
                  </div>
                <?php endif; ?>
              </div>
            </div>
          </div>
        <?php endif; ?>

        <?=$this->driver->supportsCoinsOpenURL() ? '<span class="Z3988" aria-hidden="true" title="' . $this->escapeHtmlAttr($this->driver->getCoinsOpenURL()) . '"></span>' : ''?>
      </div>

    </div>
  </div>
  <div class="col-sm-3">
    <?=$this->record($this->driver)->getToolbar()?>
    <?php if ($sidebarList): ?>
    <div class="<?=$this->layoutClass('sidebar')?>" role="region" aria-label="<?=$this->translate('Related Items')?>">
      <?php foreach ($sidebarList as $current): ?>
        <?=$this->related()->render($current)?>
      <?php endforeach; ?>
    </div>
    <?php endif; ?>
  </div>
</div>
<?=$this->assetManager()->outputInlineScriptString('$(document).ready(recordDocReady);'); ?>
