<?php
[$min, $max] = $this->selectedMapScale;
$fromScale = $this->escapeHtmlAttr($this->mapScaleField) . '_from';
$toScale = $this->escapeHtmlAttr($this->mapScaleField) . '_to';
?>
<div class="map-scale">
  <form class="map-scale-range-form" name="<?=$this->escapeHtmlAttr($this->mapScaleField)?>Filter" id="<?=$this->escapeHtmlAttr($this->mapScaleField)?>Filter">
    <?=$results->getUrlQuery()->asHiddenFields(['page' => '/./', 'filter' => "/^{$this->mapScaleField}:.*/"])?>
    <input type="hidden" name="filter[]" id="map-scale-filter">
    <div class="map-scale-from">
      <label for="<?=$fromScale?>">
        <?=$this->transEsc('map_scale_from')?>
      </label>
      1:
      <span class="map-scale-input">
        <input type="text" size="10" form="" class="form-control" name="<?=$fromScale?>" id="<?=$fromScale?>" value="<?=$this->escapeHtmlAttr($min)?>">
      </span>
    </div>
    <div class="map-scale-to">
      <label for="<?=$toScale?>">
        <?=$this->transEsc('map_scale_to')?>
      </label>
      1:
      <span class="map-scale-input">
        <input type="text" size="10" form=""  class="form-control" name="<?=$toScale?>" id="<?=$toScale?>" value="<?=$this->escapeHtmlAttr($max)?>">
      </span>
    </div>
    <div class="slider-container">
      <div id="noUiScaleSlider"></div>
    </div>
    <input id="map-scale-submit" class="btn btn-default" type="submit" value="<?=$this->transEscAttr('Set')?>">
  </form>
</div>
<?php $this->assetManager()->appendScriptLink('vendor/nouislider.min.js'); ?>
<?php $this->assetManager()->appendStyleLink('vendor/nouislider.min.css'); ?>
<?php
$script = <<<JS
      $(document).ready(function() {
        const scaleSliderElement = document.getElementById('noUiScaleSlider');
        const fromScaleField = $('#{$fromScale}');
        const toScaleField = $('#{$toScale}');
        const scaleBase = Math.pow(10, 0.05);

        let sliderToScaleField = function(number) {
          var scale = Math.pow(scaleBase, number);
          var power = Math.floor(Math.log(scale) / Math.log(10));
          return Math.round(scale / Math.pow(10, power)) * Math.pow(10, power);
        };

        let scaleFieldToSlider = function(number) {
          return Math.log(number) / Math.log(scaleBase);
        };

        let onChange = function(elm, disableScalerUpdate = false) {
          var fromValue = Number(fromScaleField.val());
          var toValue = Number(toScaleField.val());
          const from = isNaN(fromValue) || fromValue <= 0 ? {$min} : fromValue;
          const to = isNaN(toValue) || toValue <= 0 ? {$max} : toValue;
          $('#map-scale-filter').val('{$this->mapScaleField}:[' + from + ' TO ' + to + ']');
          if (!disableScalerUpdate) {
            scaleSliderElement.noUiSlider.set([scaleFieldToSlider(from), scaleFieldToSlider(to)]);
          }
        };

        let fillScaleFields = function() {
          var v = scaleSliderElement.noUiSlider.get();
          fromScaleField.val(sliderToScaleField(v[0]));
          toScaleField.val(sliderToScaleField(v[1]));
          onChange(null, true);
        };

        fromScaleField.change(onChange);
        toScaleField.change(onChange);

        noUiSlider.create(scaleSliderElement, {
          start: [scaleFieldToSlider({$min}), scaleFieldToSlider({$max})],
          connect: false,
          range: {
            'min': 1,
            'max': 160
          }
        });

        scaleSliderElement.noUiSlider.on('update', fillScaleFields);

      });
    JS;
?>
<?=$this->assetManager()->outputInlineScriptString($script)?>
