<?php if ($this->recommend->isActive()) :?>
  <?php
    // Add translation strings
    $this->jsTranslations()->addStrings([
      'rectangle_center_message' => 'rectangle_center_message',
    ]);

    $this->assetManager()->appendScriptLink('vendor/leaflet/leaflet.js');
    $this->assetManager()->appendScriptLink('vendor/leaflet/leaflet.draw.js');
    $this->assetManager()->appendScriptLink('vendor/leaflet/leaflet.markercluster.js');
    $this->assetManager()->appendScriptLink('map_selection_leaflet.js');
    $this->assetManager()->appendStyleLink('vendor/leaflet/leaflet.css');
    $this->assetManager()->appendStyleLink('vendor/leaflet/leaflet.draw.css');
    $this->assetManager()->appendStyleLink('vendor/leaflet/MarkerCluster.css');
    $this->assetManager()->appendStyleLink('vendor/leaflet/MarkerCluster.Default.css');
    $this->assetManager()->appendStyleLink('geofeatures.css');

    $basemap = $this->recommend->getBasemap();
    $geoField = $this->recommend->getGeoField();
    $height = $this->recommend->getHeight();
    $baseUrl = $this->url('home');
    $urlpath = $this->url('search-results');
    $searchParams = $this->recommend->getSearchParams();
    $coordinates = $this->recommend->getSelectedCoordinates()
        ?? $this->recommend->getDefaultCoordinates();
    $selectBoundingBox = $this->recommend->getSelectedCoordinates() != null;

    $resultsCoords = $this->recommend->getMapResultCoordinates();
    $params = [
      json_encode($geoField), json_encode($coordinates),
      json_encode($selectBoundingBox), json_encode($urlpath),
      json_encode($baseUrl), json_encode($searchParams),
      json_encode($resultsCoords), json_encode($basemap),
    ];

    $jsParams = implode(', ', $params);
    $jsLoad = 'loadMapSelection(' . $jsParams . ');';
  ?>
  <div class="context-help">
    <h2 class="context-text "><?=$this->transEsc('Geographic Search') ?></h2>
    <?=$this->contextHelp('geosearch', 'heading')?>
  </div>
  <div class="authorbox">
    <div id="geo_search" style="display: none;">
      <button id="draw_box"><?php echo $this->transEsc('Draw Search Box')?></button>
      <div id="geo_search_map" style="height: <?php echo $height?>px;"></div>
    </div>
    <?=$this->assetManager()->outputInlineScriptString($jsLoad)?>
    <?=
    $this->context($this)->renderInContext(
        'Recommend/MapScale.phtml',
        [
        'mapScaleField' => $this->recommend->getMapScaleField(),
        'selectedMapScale' => $this->recommend->getSelectedMapScale(),
      ]
    );
    ?>
  </div>
  <?php
    // Overwrite leaflet.draw.js tooltips with international translations
    $loadTranslations
      = 'L.drawLocal.draw.handlers.rectangle.tooltip.start = "' . $this->transEsc('draw_searchbox_start') . '";'
      . 'L.drawLocal.draw.handlers.simpleshape.tooltip.end = "' . $this->transEsc('draw_searchbox_end') . '";'
  ?>
  <?=$this->assetManager()->outputInlineScriptString($loadTranslations)?>
<?php endif; ?>
