<?php if ($this->recommend->isActive()) :?>
  <?php
    $dateRanges = $this->recommend->getDateRanges();
    $dateField = $this->recommend->getDateField();
    $loadJs = <<<JS
        $(document).ready(function onReady() {
          $('#newItemsFilter select').on('change', function onChange() {
            $('#newItemsFilter').submit();
          });
        });
        JS;
  ?>

  <div class="authorbox">
    <form name='newItemsFilter' id='newItemsFilter' class='form-inline' method='get'>
      <div class="form-group form-group-inline">
        <?=
          $results->getUrlQuery()->asHiddenFields(['page' => '/./', 'filter' => "/^{$dateField}:.*/"]);
          $selectedDateRangeFilter = $this->recommend->getSelectedDateRangeFilter();
        ?>
        <label for="<?=$this->escapeHtml($dateField)?>">
          <?=$this->translate('New items since')?>:&nbsp;
        </label>
        <select id="<?=$this->escapeHtml($dateField)?>" name="filter[]" class="jumpMenu form-select w-auto">
          <option value="" selected disabled hidden></option>
          <?php foreach ($dateRanges as $key => $filter):?>
            <option value="<?=$this->escapeHtml($filter)?>" <?php if ($filter == $selectedDateRangeFilter):?> selected <?php endif; ?>><?=$this->escapeHtml($key);?> </option>
          <?php endforeach;?>
        </select>
        <noscript>
          <input type="submit" class="btn btn-default">
        </noscript>
        <?=$this->assetManager()->outputInlineScriptString($loadJs)?>
      </div>
    </form>
  </div>
<?php endif; ?>
