<?php
  $tabConfig = is_object($this->params)
    ? $this->searchTabs()->getTabConfigForParams($this->params) : [];
  $js = '';
?>
<?php if (count($tabConfig) > 0): ?>
  <div class="alert alert-info">
    <?=$this->transEsc('nohit_change_tab', ['%%activeTab%%' => $this->translate($this->recommend->getActiveTab($tabConfig)['label'])])?>
    <ul>
    <?php $inactiveTabs = $this->recommend->getInactiveTabs($tabConfig); ?>
    <?php foreach ($inactiveTabs as $tab): ?>
      <li>
        <?php if (!$tab['selected']): ?><a id="switchTab<?=$tab['id']?>" href="<?=$this->escapeHtmlAttr($tab['url'])?>"><?php endif; ?>
          <?=$this->transEsc($tab['label']); ?>
        <?php if (!$tab['selected']): ?><span></span></a><?php endif; ?>
        <?php $js .= $this->resultsCount()->getAjaxCode($tab['url'], "#switchTab${tab['id']} span"); ?>
      </li>
    <?php endforeach; ?>
    </ul>
  </div>
<?php endif; ?>
<?=$this->inlineScript(\Laminas\View\Helper\HeadScript::SCRIPT, $js, 'SET')?>
