<?php
  // Set page title.
  $this->headTitle($this->translate('Record Citations'));

  // Set up breadcrumbs:
  $this->layout()->breadcrumbs = $this->searchMemory()->getLastSearchLink($this->transEsc('Search'), '<li>', '</li> ')
    . '<li>' . $this->recordLinker()->getBreadcrumbHtml($this->driver) . '</li> '
    . '<li class="active">' . $this->transEsc('Record Citations') . '</li>';

  // Collect citation data:
  $citation = $this->driver->getCitation($this->style);
  $citationStyles = $this->driver->getCitationFormats();
  $citationLink = $this->driver->getCitationLink();
  $currentStyle = array_key_exists($this->style, $citationStyles) ? $this->style : $this->driver->getDefaultCitationStyle();
  $recordId = $driver->getUniqueID();
  ?>
  <h2><?=$this->transEsc('Record Citations') ?>: <span class="title-in-heading"><?=$this->escapeHtml($this->driver->getBreadcrumb())?></span></h2>
  <?=
    $this->context($this)->renderInContext(
        'cite/cite.phtml',
        [
            'citationStyles' => $citationStyles,
            'citations' => [ $driver->getUniqueID() => $citation ],
            'citationLink' => $driver->getCitationLink(),
            'currentStyle' => $currentStyle,
        ]
    );
  ?>
