<?php $comments = $this->driver->getComments(); ?>
<?php if (empty($comments) || count($comments) == 0): ?>
<?php else: ?>
    <?php foreach ($comments as $comment): ?>
        <div class="comment row">
            <div class="col-sm-3 name">
                <strong>
                    <?php if ($this->socialUser): ?>
                        <?= $this->transEsc($this->socialUser) ?>
                    <?php else: ?>
                        <?php $this->escapeHtml(trim($comment->firstname . ' ' . $comment->lastname)); ?>
                    <?php endif; ?>
                </strong>
                <br/>
                <small>
                    <?= $this->escapeHtml($comment->created) ?>
                    <?php if (($user = $this->auth()->isLoggedIn()) && $comment->user_id == $user->id): ?>
                        <a href="<?= $this->recordLink()->getActionUrl($this->driver, 'DeleteComment') ?>?delete=<?= urlencode($comment->id) ?>"
                           id="recordComment<?= $this->escapeHtml($comment->id) ?>"
                           class="delete text-danger"><?= $this->transEsc('Delete') ?></a>
                    <?php endif; ?>
                </small>
            </div>
            <div class="col-sm-9">
                <?= $this->escapeHtml($comment->comment) ?>
            </div>
        </div>
    <?php endforeach; ?>
<?php endif; ?>

<?php $obalkyComments = $this->driver->tryMethod('getObalkyKnihComments') //FIXME not implemented yet?>
<?php if ((empty($obalkyComments) || count($obalkyComments) == 0) && (empty($comments) || count($comments) == 0)): ?>
    <div class="alert alert-info"><?=$this->transEsc('Be the first to leave a comment')?>!</div>
<?php else: ?>
    <?php foreach ($obalkyComments as $comment): ?>
        <div class="comment row">
            <div class="col-sm-3 name">
                <strong><?=$this->escapeHtml(trim($comment->library))?></strong><br/>
                <small>
                    <?php $parsedDate = strtotime($comment->created); ?>
                    <?php if ($parsedDate): ?>
                        <?php $date = date('j. n. Y H:i', $parsedDate); ?>
                        <?=$this->escapeHtml($date)?>
                    <?php else: ?>
                        <?=$this->escapeHtml($comment->created)?>
                    <?php endif; ?>
                </small>
            </div>
            <div class="col-sm-9">
                <?=$this->escapeHtml($comment->comment)?>
            </div>
        </div>
    <?php endforeach; ?>
<?php endif; ?>