<?php
  $currentRecordId = $this->driver->getUniqueID();
  $currentSource = $this->driver->tryMethod('getSourceId');
  $logosPostfix = '_small';
  $data = [];
  $records = $this->driver->tryMethod('getDeduplicatedRecords', [], false);
  $recordMissing = $records !== false && empty($records);
  if ($records === false) {
    $records = [];
  } elseif (empty($records)) {
      $records = [$currentSource => [$currentRecordId]];
  } elseif (!empty($records)) {
    if (!isset($records[$currentSource])) {
      $records[$currentSource] = [$currentRecordId];
      $recordMissing = true;
    }
    if (!in_array($currentRecordId, $records[$currentSource])) {
      $records[$currentSource][] = $currentRecordId;
      $recordMissing = true;
    }
  }
  foreach ($records as $source => $ids) {
    $imageSrc = $this->imageLink(
        'institutions/logos/' . $source . '/' . $source
      . $logosPostfix . '.png'
    );
    $recordId = $ids[0];
    $data[] = [
      'id' => $recordId,
      'image' => $imageSrc,
      'href' => $this->recordLinker()->getUrl($recordId),
      'selected' => $source == $currentSource,
      'text' => $this->translate('Source::' . $source),
      'logoAltText' => $this->translate('logo_of', ['%%source%%' => $this->translate('Source::' . $source)]),
    ];
  }
  $internalMultiplicity = $records[$currentSource] ?? [];
  $internalMultiplicityCount = count($internalMultiplicity);
  $recordsCount = count($records);
  $showInstitutionPanel = $recordsCount >= 1 || $internalMultiplicityCount > 1;
?>
<?php if ($showInstitutionPanel): ?>
  <div class="well panel-select-institution">
    <?php if ($recordsCount > 1): ?>
      <h3><label for="institutions"><?=$this->translate('Select institution');?></label>:</h3>
      <div id="records-in-groups-container">
        <div class="input-group input-group-lg">
          <select id="institutions" class="form-control" style="width: 100%" name="institutions"></select>
          <?php if ($libraryId = $this->driver->getOwningLibraryId()): ?>
            <?=$this->render('library-detail-link.phtml', ['libraryId' => $libraryId])?>
          <?php endif; ?>
        </div>
      </div>
    <?php elseif ($recordsCount === 1): ?>
      <h3><?=$this->translate('Institution');?>:</h3>
      <div class="input-group input-group-lg">
        <span class="select2 select2-container select2-container--bootstrap3">
            <span class="select2-selection select2-selection--single select2-text" role="combobox" aria-haspopup="true" aria-expanded="false" tabindex="0" aria-disabled="false" aria-labelledby="select2-institutions-container">
              <span class="select2-selection__rendered" id="select2-institutions-container" role="textbox" aria-readonly="true" title="<?=$data[0]['text']?>">
                <span class="institutions-selector">
                  <span class="image">
                    <?php if (!empty($data[0]['image'])): ?>
                      <img src="<?=$data[0]['image']?>">
                    <?php endif; ?>
                  </span>
                  <span class="text"><?=$data[0]['text']?></span>
                </span>
              </span>
            </span>
        </span>
        <?php if ($libraryId = $this->driver->getOwningLibraryId()): ?>
          <?=$this->render('library-detail-link.phtml', ['libraryId' => $libraryId])?>
        <?php endif; ?>
      </div>
    <?php endif; ?>
    <br>
    <?php
      $count = count($internalMultiplicity);
    ?>
    <?php if ($count > 1): ?>
      <span>
      <?=$this->translate('The library has another record(s) for this publication');?>
        <?php foreach ($internalMultiplicity as $index => $recordId): ?>
          <?php
             $sep = ($count == $index + 1) ? '' : ', ';
             $href = $this->recordLinker()->getUrl($recordId);
             $title = $this->transEscAttr('Source::' . $this->driver->getSourceId());
             $label = $this->transEsc('record') . ' ' . ($index + 1);
             $link = true;
             if ($recordId == $this->driver->getUniqueID()) {
               $label .= ' (' . $this->transEsc('current record') . ')';
               $link = false;
             }
          ?>
          <?php if ($link): ?>
            <a href="<?=$href?>" title="<?=$title?>"><?=$label?></a><?=$sep?>
          <?php else: ?>
            <?=$label?><?=$sep?>
          <?php endif; ?>
        <?php endforeach;?>
      </span>
    <?php endif;?>
    <?php if ($recordMissing): ?>
      <div class="alert alert-warning" role="alert">
        <?php if (($link = $this->recordLinker()->getLinkToMainPortal($this->driver)) != null) : ?>
          <?=$this->translate('record_missing_in_view_with_link', ['%%url%%' => $link])?>
        <?php else: ?>
          <?=$this->translate('record_missing_in_view')?>
        <?php endif; ?>
      </div>
    <?php endif; ?>
  </div>
<?php endif;?>

<?php
if ($recordsCount > 1) {
  $dataJson = json_encode($data);
  $placeholder = $this->transEsc('institutions_search_placeholder');
  $select2 = <<<JS
var options = $dataJson;
function template(option) {
  if (option.image) {
    return $('<span class="institutions-selector"><span class="image"><img src="' + option.image + '" alt="' + option.logoAltText + '"></span><span class="text">' + option.text + '</span></span>');
  }
  return $('<span class="institutions-selector"><span class="image"></span><span class="text">' + option.text + '</span></span>');
}

jQuery(document).ready(function($) {
  $('#institutions').select2({
    language: document.documentElement.lang,
    data: options,
    theme: 'bootstrap3',
    templateResult: template,
		templateSelection: template
  });
  $('#institutions').on('select2:select', function (e) {
    window.location.href = e.params.data.href;
  });
  $('#institutions').on('select2:open', function (e) {
    $('.select2-search__field').attr('placeholder', '$placeholder');
  });
});
JS;
  echo $this->inlineScript(\Laminas\View\Helper\HeadScript::SCRIPT, $select2, 'SET');
}
