<?php
  $recordId = $this->driver->getUniqueID();
  $logosPostfix = '_small';
  $data = [];
  $records = $this->driver->getDeduplicatedRecords();
  $recordsCount = count($records);
  if (!empty($records)) {
    foreach ($records as $record) {
      $imageSrc = $this->imageLink(
        'institutions/logos/' . $record['source'] . '/' . $record['source']
        . $logosPostfix . '.png'
      );
      $recordUrl = $this->recordLinker()->getUrl($record['id']);
      $data[] = [
        'id' => $record['id'],
        'image' => $imageSrc,
        'href' => $recordUrl,
        'selected' => ($record['id'] == $recordId) ? true : false,
        'text' => $this->translate('Source::' . $record['source']),
      ];
    }
  }
  ?>
<div class="well panel-select-institution">
  <?php if ($recordsCount > 1): ?>
    <h3><?=$this->translate('Select institution');?>:</h3>
    <div id="records-in-groups-container">
      <div class="input-group input-group-lg">
        <select id="institutions" class="form-control" style="width: 100%"></select>
        <?php if ($libraryId = $this->driver->getOwningLibraryId()): ?>
          <?=$this->render('library-detail-link.phtml', ['libraryId' => $libraryId])?>
        <?php endif; ?>
      </div>
    </div>
  <?php elseif ($recordsCount === 1): ?>
    <h3><?=$this->translate('Institution');?>:</h3>
    <div class="input-group input-group-lg">
      <span class="select2 select2-container select2-container--bootstrap3">
          <span class="select2-selection select2-selection--single select2-text" role="combobox" aria-haspopup="true" aria-expanded="false" tabindex="0" aria-disabled="false" aria-labelledby="select2-institutions-container">
            <span class="select2-selection__rendered" id="select2-institutions-container" role="textbox" aria-readonly="true" title="Moravská zemská knihovna v Brně">
              <span class="institutions-selector">
                <span class="image">
                  <img src="<?=$data[0]['image']?>">
                </span>
                <span class="text"><?=$data[0]['text']?></span>
              </span>
            </span>
          </span>
      </span>
      <?php if ($libraryId = $this->driver->getOwningLibraryId()): ?>
        <?=$this->render('library-detail-link.phtml', ['libraryId' => $libraryId])?>
      <?php endif; ?>
    </div>
  <?php endif; ?>
</div>

<?php
if ($recordsCount > 1) {
  $dataJson = json_encode($data);
  $select2 = <<<JS
var options = $dataJson;
function template(option) {
  return $('<span class="institutions-selector"><span class="image"><img src="' + option.image + '"></span><span class="text">' + option.text + '</span></span>');
}

jQuery(document).ready(function($) {
  $('#institutions').select2({
    language: "cs",
    data: options,
    theme: 'bootstrap3',
    templateResult: template,
		templateSelection: template
  });
  $('#institutions').on('select2:select', function (e) {
    window.location.href = e.params.data.href;
  });
});
JS;
  echo $this->inlineScript(\Laminas\View\Helper\HeadScript::SCRIPT, $select2, 'SET');
}
