<?php
$id = urlencode($this->driver->getUniqueID());
$anchor = '';
foreach ($data as $field) {
  if (!empty($field['t']) || !empty($field['g']) || !empty($field['x'])) {
    if (!empty($field['t'])) {
      $anchor .= $field['t'];
    }
    if (!empty($field['x'])) {
      $isn = $field['x'];
      if (substr($isn, 0, 1) === 'M') {
        $isnPrefix = "ISMN";
      } elseif ((strlen($isn) === 8) or (strlen($isn) === 9)) {
        $isnPrefix = "ISSN";
      } else { // (strlen($isn) === 10) OR (strlen($isn) === 13)
        $isnPrefix = "ISBN";
      }

      $anchor .= '. -- ' . $isnPrefix . ' ' . $field['x'];
    }
    if (!empty($field['g'])) {
      $anchor .= '. -- ' . $field['g'];
    }
  }
  $linkTemplate = '/Search/Results?join=AND&bool0[]=AND&lookfor0[]="%s"&type0[]=isn&bool1[]=NOT&lookfor1[]="%s"&type1[]=id&sort=title&view=list';
  if (!empty($field['x']) || !empty($field['z']) || !empty($field['t'])) {
    $link = '';
    if (!empty($field['x'])) {
      $link = sprintf($linkTemplate, $field['x'], $id);
    } elseif (!empty($field['z'])) {
      $link = sprintf($linkTemplate, $field['z'], $id);
    } elseif (!empty($field['t'])) {
      $link = sprintf($linkTemplate, $field['t'], $id);
    }
    ?>
    <a href='<?=$link?>' title="<?=$anchor?>"><?=$anchor?></a><br />
<?php
  } else {
    ?>
    <?=$anchor?><br />
<?php
  }
}
