<?php
$id = urlencode($this->driver->getUniqueID());
$anchor = '';
foreach ($data as $field) {
  if (!empty($field['t']) || !empty($field['g']) || !empty($field['x'])) {
    if (!empty($field['t'])) {
      $anchor .= $field['t'];
    }
    if (!empty($field['x'])) {
      $isn = $field['x'];
      if (substr($isn, 0, 1) === 'M') {
        $isnPrefix = "ISMN";
      } elseif ((strlen($isn) === 8) or (strlen($isn) === 9)) {
        $isnPrefix = "ISSN";
      } else { // (strlen($isn) === 10) OR (strlen($isn) === 13)
        $isnPrefix = "ISBN";
      }

      $anchor .= '. -- ' . $isnPrefix . ' ' . $field['x'];
    }
    if (!empty($field['g'])) {
      $anchor .= '. -- ' . $field['g'];
    }
  }
  if (!empty($field['x']) || !empty($field['z']) || !empty($field['t'])) {
    $fieldName = 'adv_search_isbn_issn_ismn';
    if (!empty($field['x'])) {
      $fieldValue = $field['x'];
    } elseif (!empty($field['z'])) {
      $fieldValue = $field['z'];
    } else {
      $fieldName = 'adv_search_title_series';
      $fieldValue = $field['t'];
    }
    $searchParams = [
      'join' => 'AND',
      'bool0' => ['AND'],
      'lookfor0' => [$fieldValue],
      'type0' => [$fieldName],
      'bool1' => ['NOT'],
      'lookfor1' => [$id],
      'type1' => ['adv_search_001'],
    ];
    $link = $this->url('search-results', [], ['query' => $searchParams]);
    ?>
    <a href='<?=$link?>' title="<?=$anchor?>"><?=$anchor?></a><br>
<?php
  } else {
    ?>
    <?=$anchor?><br>
<?php
  }
}
