<h3><?=$this->transEsc('Electronic')?></h3>
<table class="table table-striped">
  <?php foreach ($this->holdings as $item): ?>
    <tr>
      <td class="fullLocation">
        <?php $locationTextEsc = $this->transEscWithPrefix('location_', $item['location']); ?>
        <?php if ($item['locationhref'] ?? false): ?>
          <a href="<?=$this->escapeHtmlAttr($item['locationhref'])?>" target="_blank"><?=$locationTextEsc?></a>
        <?php else: ?>
          <?=$locationTextEsc?>
        <?php endif; ?>
      </td>
      <?php
        $itemStatus = !empty($item['status']) ? $this->transEsc('HoldingStatus::' . $item['status']) : $this->transEsc('HoldingStatus::' . 'Available');
      ?>
      <td class="fullAvailability">
        <?php if ($item['use_unknown_message'] ?? false): ?>
          <span><?=$this->transEsc('status_unknown_message')?></span>
        <?php elseif ((int)$item['availability'] === \VuFind\ILS\Logic\ItemStatus::STATUS_UNAVAILABLE): ?>
          <span class="text-danger"><?=$this->transEsc($itemStatus)?></span>
        <?php elseif ((int)$item['availability'] === \VuFind\ILS\Logic\ItemStatus::STATUS_UNCERTAIN): ?>
          <span class="text-warning"><?=$this->transEsc($itemStatus)?></span>
	<?php else: ?>
          <span class="text-success"><?=$this->transEsc($itemStatus)?></span>
        <?php endif; ?>
        <?php if (isset($item['item_notes'])): ?>
          <div class="item-notes">
            <b><?=$this->transEsc("Item Notes")?>:</b>
            <ul>
              <?php foreach ($item['item_notes'] as $item_note): ?>
                <li><?=$this->escapeHtml($item_note) ?></li>
              <?php endforeach; ?>
            </ul>
          </div>
        <?php endif; ?>
      </td>
    </tr>
  <?php endforeach; ?>
</table>
