<tr vocab="http://schema.org/" typeof="Offer"
  id="holding_item_<?=$this->escapeHtml($holding['item_id'] ?? $holding['copy_number'])?>"
  data-item-id="<?=$this->escapeHtml($holding['item_id'])?>"
  data-copy-number="<?=$this->escapeHtml($holding['copy_number'])?>"
  data-volume="<?=$this->escapeHtml($holding['volume'])?>"
  data-year="<?=$this->escapeHtml($holding['year'])?>"
  data-ajax-status="waiting">

  <td data-type="availability" data-title="<?=$this->transEsc('Availability')?>">
    <div class="jt" title="<?=$this->transEsc('Availability')?>">
      <?php
      $availabilityStatus = '';
      $status = $availability = $holding['status'] ?? '';
      if (!empty($availability)) {
        $text = 'HoldingStatus::' . $source . '_' . $availability;
        $availabilityStatus = $this->transEsc($text, [], $text);
        if ($availabilityStatus == $text) {
          $text = 'HoldingStatus::' . $availability;
          $availabilityStatus = $this->transEsc($text, [], $availability);
        }
      }
    ?>
    <div><?=$availabilityStatus?></div>
  </td>
  <td data-type="status" data-title="<?=$this->transEsc('Status')?>">
    <?php
      $status = '';
      if (!empty($holding['catalog_link'])) {
        $status = sprintf('<a href="%s" target="_blank">%s</a>', $holding['catalog_link'], $this->translate('caslin_tab_link'));
      }
    ?>
    <div><?=$status?></div>
  </td>
  <td data-type="request">
    <?php if ($ajax): ?>
      <div class='status-loader'><?=$this->icon('spinner', 'fa-fw') . $this->translate('loading_ellipsis') ?></div>
    <?php endif; ?>
  </td>
  <td data-title="<?=$this->transEsc('Department')?>" data-type="location">
    <div>
      <?php if (!empty($holding['location'])):?>
        <?=$this->escapeHtml($holding['location'])?>
      <?php endif; ?>
    </div>
	</td>
  <td data-title="<?=$this->transEsc('Collection')?>" data-type="collection_desc">
    <div>
      <?php if (!empty($holding['collection_desc'])):?>
        <?=$this->escapeHtml($holding['collection_desc'])?>
      <?php endif; ?>
    </div>
  </td>
  <td data-title="<?=$this->transEsc('Location')?>" data-type="callnumber_second">
    <?php if (!empty($holding['callnumber_second'] && (empty($holding['callnumber']) || ($holding['callnumber_second'] != $holding['callnumber'])))):?>
      <?=$this->escapeHtml($holding['callnumber_second'])?>
    <?php endif;?>
  </td>
	<td data-title="<?=$this->transEsc('Description')?>" data-type="description">
    <?php if (!empty($holding['description'])):?>
      <?=$this->escapeHtml($holding['description']);?>
    <?php endif;?>
  </td>
  <td data-title="<?=$this->transEsc('Item notes')?>" data-type="item_notes">
    <?php if (!empty($holding['item_notes'])):?>
      <?=$this->escapeHtml($holding['item_notes'])?>
    <?php endif;?>
  </td>
  <td data-title="<?=$this->transEsc('callnumber_abbrev')?>" data-type="callnumber">
    <?php if (!empty($holding['callnumber'])):?>
      <?=$this->escapeHtml($holding['callnumber'])?>
    <?php endif;?>
  </td>
</tr>
