<?php
  $check = $holding['check'] ?? false;
  $checkStorageRetrievalRequest = $holding['checkStorageRetrievalRequest'] ?? false;
  $checkILLRequest = $holding['checkILLRequest'] ?? false;
?>
<tr vocab="http://schema.org/" typeof="Offer"
  id="holding_item_<?=$this->escapeHtml($holding['item_id'])?>"
  data-item-id="<?=$this->escapeHtml($holding['item_id'])?>"
  data-copy-number="<?=$this->escapeHtml($holding['copy_number'])?>">
  <td data-title="<?=$this->transEsc("Availability")?>">
    <div data-type="availability" class="jt" title="<?=$this->transEsc('Availability')?>">
      <?php
      $status = $availability = $holding['status'] ?? '';
      if (!empty($availability)) {
        $text = 'HoldingStatus::' . $source . '_' . $availability;
        $status = $this->transEsc($text, [], $text);
        if ($status == $text) {
          $text = 'HoldingStatus::' . $availability;
          $status = $this->transEsc($text, [], $availability);
        }
      }
      ?>
      <span class="availability"><?=$status?></span>
    </div>
  <td data-type="status" data-title="<?=$this->transEsc("Status")?>">
  </td>
  <td data-type="request">
    <div class='status-loader'><i class="fa fa-spinner fa-spin fa-fw"></i> <?=$this->translate('Loading')?></div>
  </td>
  <td data-title="<?=$this->transEsc("Department")?>" data-type="location">
    <div>
      <?php if(!empty($holding['location'])):?>
        <?=$this->escapeHtml($holding['location'])?>
      <?php endif; ?>
    </div>
	</td>
  <td data-title="<?=$this->transEsc("Collection")?>" data-type="collection_desc">
    <div>
      <?php if(!empty($holding['collection_desc'])):?>
        <?=$this->escapeHtml($holding['collection_desc'])?>
      <?php endif; ?>
    </div>
  </td>
  <td data-title="<?=$this->transEsc("Location")?>" data-type="callnumber_second">
    <?php if (!empty($holding['callnumber_second'] && (empty($holding['callnumber']) || ($holding['callnumber_second'] != $holding['callnumber'])))):?>
      <?=$this->escapeHtml($holding['callnumber_second'])?>
    <?php endif;?>
  </td>
	<td data-title="<?=$this->transEsc("Description")?>" data-type="description">
    <?php if (!empty($holding['description'])):?>
      <?=$this->escapeHtml($holding['description']);?>
    <?php endif;?>
  </td>
  <td data-title="<?=$this->transEsc("callnumber_abbrev")?>" data-type="callnumber">
    <?php if (!empty($holding['callnumber'])):?>
      <?=$this->escapeHtml($holding['callnumber'])?>
    <?php endif;?>
  </td>
</tr>
